### ISSUE TITLE
context using the properties file, pwd can't be accessed

### ISSUE THREAD

**Issue by jichangfeng67** [spring-projects/spring-integration#1763]
**modified**
### the gradle
```gradle
  compile("org.springframework.integration:spring-integration-core")
  compile("org.springframework.integration:spring-integration-ftp:4.2.5.RELEASE")
```
### the properties named <i>ftp_cfg.properties</i>
```properties
host=localhost
port=21
user=gpadmin
pwd=nishengri
```
### the `xml` 
```xml
  <context:property-placeholder location="classpath:ftp_cfg.properties"/>

  <bean id="ftpClientFactory" class="org.springframework.integration.ftp.session.DefaultFtpSessionFactory">
    <property name="host" value="${host}"/>
    <property name="port" value="${port}"/>
    <property name="username" value="${user}"/>
    <property name="password" value="${pwd}"/>
  </bean>
```
### the kickoff `java`
```java
  public static void kickoff(){
	    ConfigurableApplicationContext ctx = new ClassPathXmlApplicationContext("ftp/integration.xml");

	    PollableChannel ftpChannel = ctx.getBean("ftpChannel", PollableChannel.class);

	    ftpChannel.receive();
  }
```
### the console content
```console
Apr 07, 2016 11:54:28 AM org.springframework.integration.endpoint.SourcePollingChannelAdapter start
INFO: started ftpInbound
Apr 07, 2016 11:54:31 AM org.springframework.integration.handler.LoggingHandler handleMessageInternal
SEVERE: org.springframework.messaging.MessagingException: Problem occurred while synchronizing remote to local directory; nested exception is org.springframework.messaging.MessagingException: Failed to execute on session; nested exception is java.lang.IllegalStateException: failed to create FTPClient
	at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizer.synchronizeToLocalDirectory(AbstractInboundFileSynchronizer.java:266)
	at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizingMessageSource.doReceive(AbstractInboundFileSynchronizingMessageSource.java:193)
	at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizingMessageSource.doReceive(AbstractInboundFileSynchronizingMessageSource.java:59)
	at org.springframework.integration.endpoint.AbstractMessageSource.receive(AbstractMessageSource.java:134)
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.receiveMessage(SourcePollingChannelAdapter.java:175)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:224)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.access$000(AbstractPollingEndpoint.java:57)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$1.call(AbstractPollingEndpoint.java:176)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$1.call(AbstractPollingEndpoint.java:173)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller$1.run(AbstractPollingEndpoint.java:330)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor$1.run(ErrorHandlingTaskExecutor.java:55)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:51)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller.run(AbstractPollingEndpoint.java:324)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.messaging.MessagingException: Failed to execute on session; nested exception is java.lang.IllegalStateException: failed to create FTPClient
	at org.springframework.integration.file.remote.RemoteFileTemplate.execute(RemoteFileTemplate.java:419)
	at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizer.synchronizeToLocalDirectory(AbstractInboundFileSynchronizer.java:223)
	... 22 more
Caused by: java.lang.IllegalStateException: failed to create FTPClient
	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.getSession(AbstractFtpSessionFactory.java:171)
	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.getSession(AbstractFtpSessionFactory.java:41)
	at org.springframework.integration.file.remote.RemoteFileTemplate.execute(RemoteFileTemplate.java:408)
	... 23 more
Caused by: java.lang.IllegalStateException: Login failed. The respponse from the server is: 530 Login incorrect.

	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.createClient(AbstractFtpSessionFactory.java:204)
	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.getSession(AbstractFtpSessionFactory.java:168)
	... 25 more
```

However, the wired thing is: when I change the `key` in the properties file from `pwd` to `password`,
everything is good.

**Comment by garyrussell** [comment]
Can you provide (a lot) more context for this issue? - including your configuration.

**Comment by jichangfeng67** [comment]
hey, @garyrussell , I just updated the question. thanks.

**Comment by artembilan** [comment]
Well, the `PWD` might be your `ENV` var which doesn't meet the FTP server requirements.
So, try this:
````xml
 <context:property-placeholder location="classpath:ftp_cfg.properties" 
            system-properties-mode="FALLBACK"/>
````

**Comment by jichangfeng67** [comment]
@artembilan Yes, thanks a lot. it works.
And for the proxy things, I think it's a issue for JVM.
thanks.

**Comment by artembilan** [comment]
Great! Always happy to be helpful :smile: 

In the future consider to share similar issues on the [StackOverflow](http://stackoverflow.com/):
1. We really should confirm that it is a bug before raising a GH issue.
2. That really might not be a bug, but just some misconfiguration like this.
3. We not always may be here (but there on SO :wink: ), so anyone else from the Community can help you there and sometimes more quickly than we here :smile:

**Comment by jichangfeng67** [comment]
Okay, no problem. I will.
And I didn't only because the editor in SO sucks. 
And once more, Good job for the Integration. We talked a lot in the company about your products.
