### ISSUE TITLE
spring-integration-sftp, NoSuchFieldError:EXPRESSION_PARSER

### ISSUE THREAD

**Issue by kexiuru** [spring-projects/spring-integration#2023]
using versin: spring-integration-sftp-4.3.0.RELEASE
configuration as below:
`	<bean id="sftpSessionFactory" class="org.springframework.integration.file.remote.session.CachingSessionFactory">
		<constructor-arg ref="defaultSessionFactory" />
	</bean>
	
	<int-sftp:inbound-channel-adapter id="sftpInbondAdapter"
		session-factory="sftpSessionFactory"
		channel="receiveChannel"
		filename-pattern="*.csv"
		preserve-timestamp="true"
		remote-directory="${batch.sftp.remote.status.dir}"
		local-directory="${batch.input.source.status.dir}"
		auto-create-local-directory="true"
		temporary-file-suffix=".writing"
		delete-remote-files="false">
		<int:poller fixed-rate="100" />	
	</int-sftp:inbound-channel-adapter>
	
	<int:channel id="receiveChannel">
		<int:queue />
	</int:channel>`
and, when I run the test case, get error as below:
`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#16aad23': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.integration.sftp.inbound.SftpInboundFileSynchronizer]: Constructor threw exception; nested exception is java.lang.NoSuchFieldError: EXPRESSION_PARSER
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:279)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:299)
	... 45 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.integration.sftp.inbound.SftpInboundFileSynchronizer]: Constructor threw exception; nested exception is java.lang.NoSuchFieldError: EXPRESSION_PARSER
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:159)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
	... 50 more
Caused by: java.lang.NoSuchFieldError: EXPRESSION_PARSER
	at org.springframework.integration.file.DefaultFileNameGenerator.<init>(DefaultFileNameGenerator.java:45)
	at org.springframework.integration.file.remote.RemoteFileTemplate.<init>(RemoteFileTemplate.java:81)
	at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizer.<init>(AbstractInboundFileSynchronizer.java:113)
	at org.springframework.integration.sftp.inbound.SftpInboundFileSynchronizer.<init>(SftpInboundFileSynchronizer.java:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 52 more`

After checking, can't find any definition of  EXPRESSION_PARSER. May I know how to fixed this issue?

**Comment by garyrussell** [comment]
You have mis-matched jars on your classpath - `spring-integration-core` must the the same version as `spring-integration-sftp`; your version must be < 4.3 because that's when `EXPRESSION_PARSER` was added. If you use maven or gradle to manage your dependencies, the right version will be pulled-in transitively.

>using versin: spring-integration-sftp-4.3.0.RELEASE

I also suggest you use the latest - 4.3.6.RELEASE.

**Comment by kexiuru** [comment]
@Gary.  
Thanks for you comment. Fixed. 
After checking maven dependencies, found it's using spring-integration-core-4.0.1.RELEASE(did not add it's dependency in the pom.xml)  , and EXPRESSION_PARSER did not be defined in this version.
