### ISSUE TITLE
MQTT client attemps to reconnect indefinitely

### ISSUE THREAD

**Issue by joaqapr** [spring-projects/spring-integration#2046]
I have tried to connect two MQTT clients with the same ID to the same broker without knowing that the clientID must be unique. In this situation both clients tries indefinitely to connect to the broker (normal behaviour) but when you stop one of them, the other one goes on attemping to reconnect with the debug message "MqttPahoMessageDrivenChannelAdapter : Attempting reconnect" forever. The only way to solve the problem is restart the application.

I don't know if this is a bug or the expected behaviour. These are the logs for the error of the instance that remains attemping to reconnect.

```
2017-02-02 14:50:39.487 DEBUG 27039 --- [nio-8081-exec-2] o.s.b.w.f.OrderedRequestContextFilter    : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@696f298c
2017-02-02 14:50:45.384 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:45.384 DEBUG 27039 --- [mtfsParserInput] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'taskScheduler'
2017-02-02 14:50:45.385 DEBUG 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:45.432 DEBUG 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Connected and subscribed to [mtfs-connector/tap]
2017-02-02 14:50:45.450 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:45.450 DEBUG 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:45.565 ERROR 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Error connecting or subscribing to [mtfs-connector/tap]

org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 common frames omitted

2017-02-02 14:50:45.566 ERROR 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Exception while connecting and subscribing

org.eclipse.paho.client.mqttv3.MqttException: Client is currently disconnecting
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.disconnect(ClientComms.java:455)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:632)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:601)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:608)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.connectAndSubscribe(MqttPahoMessageDrivenChannelAdapter.java:246)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.access$300(MqttPahoMessageDrivenChannelAdapter.java:47)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter$1.run(MqttPahoMessageDrivenChannelAdapter.java:287)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2017-02-02 14:50:45.568 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:45.569 DEBUG 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:45.700 ERROR 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Error connecting or subscribing to [mtfs-connector/tap]

org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 common frames omitted

2017-02-02 14:50:45.701 ERROR 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Exception while connecting and subscribing

org.eclipse.paho.client.mqttv3.MqttException: Client is disconnected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.disconnect(ClientComms.java:451)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:632)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:601)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:608)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.connectAndSubscribe(MqttPahoMessageDrivenChannelAdapter.java:246)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.access$300(MqttPahoMessageDrivenChannelAdapter.java:47)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter$1.run(MqttPahoMessageDrivenChannelAdapter.java:287)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

.
.
.

2017-02-02 14:50:46.462 DEBUG 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:46.548 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:46.549 DEBUG 27039 --- [ask-scheduler-8] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:46.549 ERROR 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Error connecting or subscribing to [mtfs-connector/tap]

org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 common frames omitted

2017-02-02 14:50:46.549 ERROR 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Exception while connecting and subscribing

org.eclipse.paho.client.mqttv3.MqttException: Client is disconnected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.disconnect(ClientComms.java:451)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:632)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:601)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:608)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.connectAndSubscribe(MqttPahoMessageDrivenChannelAdapter.java:246)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.access$300(MqttPahoMessageDrivenChannelAdapter.java:47)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter$1.run(MqttPahoMessageDrivenChannelAdapter.java:287)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2017-02-02 14:50:46.621 DEBUG 27039 --- [ask-scheduler-8] .m.i.MqttPahoMessageDrivenChannelAdapter : Connected and subscribed to [mtfs-connector/tap]
2017-02-02 14:50:46.637 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:46.639 DEBUG 27039 --- [ask-scheduler-5] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:46.699 DEBUG 27039 --- [ask-scheduler-5] .m.i.MqttPahoMessageDrivenChannelAdapter : Connected and subscribed to [mtfs-connector/tap]
2017-02-02 14:50:46.721 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:46.721 DEBUG 27039 --- [ask-scheduler-4] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:46.823 DEBUG 27039 --- [ask-scheduler-4] .m.i.MqttPahoMessageDrivenChannelAdapter : Connected and subscribed to [mtfs-connector/tap]
2017-02-02 14:50:46.824 ERROR 27039 --- [mtfsParserInput] .m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection:Connection lost; retrying...
2017-02-02 14:50:46.825 DEBUG 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:46.909 DEBUG 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Connected and subscribed to [mtfs-connector/tap]
2017-02-02 14:50:49.490 DEBUG 27039 --- [nio-8081-exec-3] o.s.b.w.f.OrderedRequestContextFilter    : Bound request context to thread: org.apache.catalina.connector.RequestFacade@696f298c
2017-02-02 14:50:49.490 DEBUG 27039 --- [nio-8081-exec-3] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing GET request for [/health]
2017-02-02 14:50:49.490 DEBUG 27039 --- [nio-8081-exec-3] o.s.b.a.e.mvc.EndpointHandlerMapping     : Looking up handler method for path /health
2017-02-02 14:50:49.491 DEBUG 27039 --- [nio-8081-exec-3] o.s.b.a.e.mvc.EndpointHandlerMapping     : Returning handler method [public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.invoke(java.security.Principal)]
2017-02-02 14:50:49.491 DEBUG 27039 --- [nio-8081-exec-3] o.s.web.servlet.DispatcherServlet        : Last-Modified value for [/health] is: -1
2017-02-02 14:50:49.519 DEBUG 27039 --- [nio-8081-exec-3] m.m.a.RequestResponseBodyMethodProcessor : Written [UP {discoveryComposite=UP {discoveryClient=UP {services=[MtfsParser, consul]}}, diskSpace=UP {total=486303457280, free=411104645120, threshold=10485760}, refreshScope=UP {}, hystrix=UP {}, consul=UP {services={MtfsParser=[], consul=[]}, advertiseAddress=127.0.0.1, datacenter=mtfs-test, domain=consul., nodeName=os-lin-jra, bindAddress=0.0.0.0, clientAddress=127.0.0.1}}] as "application/json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@7530090a]
2017-02-02 14:50:49.519 DEBUG 27039 --- [nio-8081-exec-3] o.s.web.servlet.DispatcherServlet        : Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2017-02-02 14:50:49.519 DEBUG 27039 --- [nio-8081-exec-3] o.s.web.servlet.DispatcherServlet        : Successfully completed request
2017-02-02 14:50:49.520 DEBUG 27039 --- [nio-8081-exec-3] o.s.b.w.f.OrderedRequestContextFilter    : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@696f298c
2017-02-02 14:50:55.566 DEBUG 27039 --- [ask-scheduler-6] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:55.701 DEBUG 27039 --- [ask-scheduler-7] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:55.933 DEBUG 27039 --- [ask-scheduler-3] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:56.016 DEBUG 27039 --- [ask-scheduler-8] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:56.115 DEBUG 27039 --- [ask-scheduler-5] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:56.206 DEBUG 27039 --- [ask-scheduler-4] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:56.342 DEBUG 27039 --- [ask-scheduler-2] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:56.462 DEBUG 27039 --- [sk-scheduler-10] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
2017-02-02 14:50:56.550 DEBUG 27039 --- [ask-scheduler-9] .m.i.MqttPahoMessageDrivenChannelAdapter : Attempting reconnect
```

**Comment by garyrussell** [comment]
This sounds like a question (or bug) for the [paho folks](https://eclipse.org/paho/clients/java/) we are just delegating to that.

**Comment by garyrussell** [comment]
Oh; hang on - I didn't see that the reconnect was successful; I'll take a look.

**Comment by artembilan** [comment]
I wonder if this is related: https://jira.spring.io/browse/INT-3923

**Comment by garyrussell** [comment]
Probably yes; we schedule the reconnect on a fixed delay and then cancel the `ScheduledFuture` when we successfully connect and subscribe; it looks like it should work, but there must be a race that I'm not immediately seeing.

It will probably be better to just schedule a single task and reschedule on failure rather than having it run on a regular schedule.

**Comment by artembilan** [comment]
+1 for the reschedule on failure instead.

**Comment by garyrussell** [comment]
I see what the problem is; if we get a 

    Lost connection:Connection lost; retrying...

while the schedule is running, we start another scheduled task.

You can track the fix via the above JIRA issue.
