### ISSUE TITLE
Trying to use RedisMetadataStore on a Redis cluster

### ISSUE THREAD

**Issue by tkvangorder** [spring-projects/spring-integration#2207]
Using
Spring Integration 4.3.8
Spring Boot 1.4.5
Spring Core 4.3.7

We have a cluster of servers that are are monitoring a shared network mount for processing EDI files. We recently added code to use the RedisMetadataStore as follows: 

```java

	@Bean
	public ConcurrentMetadataStore metadataStore() {
        return new RedisMetadataStore(redisConnectionFactory);
     }

	@Bean 
	public FileSystemPersistentAcceptOnceFileListFilter persistentAcceptOnceFileFilter() {
		return new FileSystemPersistentAcceptOnceFileListFilter(metadataStore(), "edi-file-locks");
	}

	@Bean
	public IntegrationFlow flowInboundNetTransferFile(
			@Value("${edi.incoming.directory.netTransfers}") String inboundDirectory,
			@Value("${edi.incoming.age-before-ready-seconds:30}") int ageBeforeReadySeconds,
			@Value("${taskExecutor.inboundFile.corePoolSize:4}") int corePoolSize,
			@Qualifier("taskExecutorInboundFile") TaskExecutor taskExecutor) {
		
		//Setup a filter to only pick up a files older than a certain age, relative to the current time. This prevents cases
		//where something is writing to the file as the EDI processor is moving that file. 
		LastModifiedFileListFilter lastModifiedFilter = new LastModifiedFileListFilter();
		lastModifiedFilter.setAge(ageBeforeReadySeconds);
        return IntegrationFlows
        		.from(
        			Files
        				.inboundAdapter(new File(inboundDirectory))
        				.locker(ediDocumentLocker())
        				.filter(new ChainFileListFilter<File>())
        				.filter(new IgnoreHiddenFileListFilter())
        				.filter(lastModifiedFilter)
        				.filter(persistentAcceptOnceFileFilter()),
        			e -> e.poller(Pollers.fixedDelay(20000).maxMessagesPerPoll(corePoolSize).taskExecutor(taskExecutor)))
                .channel(channelInboundFile())
                .get();		
    }
```

This was working fine in our lower environments, however, we use a Redis cluster in our production environment and when we deployed to that environment we got the following exception: 

```java
org.springframework.dao.InvalidDataAccessApiUsageException: WATCH is currently not supported in cluster mode.
	at org.springframework.data.redis.connection.jedis.JedisClusterConnection.watch(JedisClusterConnection.java:2450)
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.watch(DefaultStringRedisConnection.java:951)
	at org.springframework.data.redis.core.RedisTemplate$24.doInRedis(RedisTemplate.java:885)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:204)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:166)
	at org.springframework.data.redis.core.RedisTemplate.watch(RedisTemplate.java:882)
	at org.springframework.data.redis.support.collections.DefaultRedisMap$2.execute(DefaultRedisMap.java:225)
	at org.springframework.data.redis.support.collections.DefaultRedisMap$2.execute(DefaultRedisMap.java:221)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:226)
	at org.springframework.data.redis.support.collections.DefaultRedisMap.replace(DefaultRedisMap.java:221)
	at org.springframework.data.redis.support.collections.RedisProperties.replace(RedisProperties.java:238)
	at org.springframework.integration.redis.metadata.RedisMetadataStore.replace(RedisMetadataStore.java:154)
	at org.springframework.integration.file.filters.AbstractPersistentAcceptOnceFileListFilter.accept(AbstractPersistentAcceptOnceFileListFilter.java:83)
	at org.springframework.integration.file.filters.AbstractFileListFilter.filterFiles(AbstractFileListFilter.java:40)
	at org.springframework.integration.file.filters.ChainFileListFilter.filterFiles(ChainFileListFilter.java:50)
	at org.springframework.integration.file.DefaultDirectoryScanner.listFiles(DefaultDirectoryScanner.java:95)
	at org.springframework.integration.file.FileReadingMessageSource.scanInputDirectory(FileReadingMessageSource.java:387)
	at org.springframework.integration.file.FileReadingMessageSource.receive(FileReadingMessageSource.java:366)
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.receiveMessage(SourcePollingChannelAdapter.java:224)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:245)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.access$000(AbstractPollingEndpoint.java:58)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$1.call(AbstractPollingEndpoint.java:190)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$1.call(AbstractPollingEndpoint.java:186)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller$1.run(AbstractPollingEndpoint.java:353)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor$1.run(ErrorHandlingTaskExecutor.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by artembilan** [comment]
SO question on the matter: https://stackoverflow.com/questions/45495329/using-redismetadatastore-redisproperties-with-a-redis-cluster

**Comment by tkvangorder** [comment]
Should move the details in my SO question over to this issue? or is it enough just to have the link?

**Comment by artembilan** [comment]
True. That really just enough to have a link.
When we figure out what to do on the matter from the SO, we can just move the target proposition here and resolve that or other way.

**Comment by artembilan** [comment]
According to some simple investigation that looks like only the fix for this issue is like documenting the limitation of the `RedisMetadataStore` only for non-clustered connection to Redis.
