### ISSUE TITLE
Jetty websockets

### ISSUE THREAD

**Issue by bukajsytlos** [spring-projects/spring-integration#2238]
Spring boot: 1.5.6.RELEASE

Hello.
I am trying to get working websocket on Jetty runtime and I am getting

```
Caused by: org.springframework.web.socket.server.HandshakeFailureException: Uncaught failure for request http://localhost:8080/ws-endpoint; nested exception is org.eclipse.jetty.websocket.api.WebSocketException: No WebSockets have been registered with the factory.  Cannot use default implementation of WebSocketCreator.
	at org.springframework.web.socket.server.support.WebSocketHttpRequestHandler.handleRequest(WebSocketHttpRequestHandler.java:174)
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	... 89 common frames omitted
Caused by: org.eclipse.jetty.websocket.api.WebSocketException: No WebSockets have been registered with the factory.  Cannot use default implementation of WebSocketCreator.
	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.createWebSocket(WebSocketServerFactory.java:286)
	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:209)
	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:194)
	at org.springframework.web.socket.server.jetty.JettyRequestUpgradeStrategy.upgrade(JettyRequestUpgradeStrategy.java:194)
	at org.springframework.web.socket.server.support.AbstractHandshakeHandler.doHandshake(AbstractHandshakeHandler.java:279)
	at org.springframework.web.socket.server.support.WebSocketHttpRequestHandler.handleRequest(WebSocketHttpRequestHandler.java:166)
	... 93 common frames omitted
```
From what I've debugged, it looks like WebSocketCreator is created in start() method of JettyRequestUpgradeStrategy, but it is never called. On tomcat everything works fine.

Thanks for help.

PS: this is my config part

```

  @Bean
  public IntegrationWebSocketContainer serverWebSocketContainer(ServletContext servletContext) {
    return new ServerWebSocketContainer("/ws-endpoint")
      .setAllowedOrigins("*")
      .setHandshakeHandler(handshakeHandler(servletContext));
//      .withSockJs();
  }

  @Bean
  public DefaultHandshakeHandler handshakeHandler(ServletContext servletContext) {

    WebSocketPolicy policy = new WebSocketPolicy(WebSocketBehavior.SERVER);
    policy.setInputBufferSize(8192);
    policy.setIdleTimeout(600000);

    final DefaultHandshakeHandler defaultHandshakeHandler = new DefaultHandshakeHandler(
      new JettyRequestUpgradeStrategy(new WebSocketServerFactory(servletContext, policy)));
    return defaultHandshakeHandler;
  }
```

**Comment by artembilan** [comment]
I think this is a bug. The `JettyRequestUpgradeStrategy` implements `Lifecycle`, as well as `DefaultHandshakeHandler`, which really delegates the `start()` invocation to the target `JettyRequestUpgradeStrategy`.

When we deal with the Spring WebSocket support (`@EnableWebSocketMessageBroker`), we configure something like:
```
@Override
public void registerStompEndpoints(StompEndpointRegistry registry) {
	registry.addEndpoint("/ws").setHandshakeHandler(handshakeHandler()).withSockJS();
}
```
what in the end comes to the `WebSocketHandlerMapping` bean. And this one already implements `SmartLifecycle`. This type of components are started in the beginning of application via `DefaultLifecycleProcessor` where we can find the logic:
```
String[] dependenciesForBean = getBeanFactory().getDependenciesForBean(beanName);
for (String dependency : dependenciesForBean) {
	doStart(lifecycleBeans, dependency, autoStartupOnly);
}
if (!bean.isRunning() &&
	(!autoStartupOnly || !(bean instanceof SmartLifecycle) || ((SmartLifecycle) bean).isAutoStartup())) {
	if (logger.isDebugEnabled()) {
		logger.debug("Starting bean '" + beanName + "' of type [" + bean.getClass() + "]");
	}
	try {
		bean.start();
	}
...
```
Pay attention how we retrieve dependencies and start them.

Yes, `HandshakeHandler` is indeed a dependency for the `ServerWebSocketContainer`, but since the last one isn't `SmartLifecycle` the `start()` of the `DefaultHandshakeHandler` isn't called.

Good catch and we'd appreciate to have a fix via [Contribution](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc).

Thank you, @bukajsytlos !

**Comment by bukajsytlos** [comment]
Thanks @artembilan
