### ISSUE TITLE
SFTP module - error chmod'ing a file after upload through handler

### ISSUE THREAD

**Issue by jeblackburn** [spring-projects/spring-integration#2452]
We are using spring-integration-sftp to upload files to another machine, using v5.0.5.RELEASE. We have configured our SftpMessageHandler to do a chmod after upload, using handler.setChmodOctal(...). When we try to upload we see an exception: "Functional interface org.springframework.integration.file.remote.ClientCallbackWithoutResult is not an interface".

## Bug report

Versions:
spring-integration-sftp: 5.0.5.RELEASE
spring-integration-file: 4.3.12.RELEASE

Configuration:

    @Bean
    @ServiceActivator(inputChannel = "toSftpChannel")
    public MessageHandler contentHandler(
            @Qualifier("CachingSessionFactory") SessionFactory<ChannelSftp.LsEntry> sessionFactory
    ) {
        SftpMessageHandler handler = new SftpMessageHandler(sessionFactory);
        handler.setRemoteDirectoryExpression(new ValueExpression<>("upload"));
        handler.setFileNameGenerator((message) -> message.getHeaders().get("filename").toString());
        handler.setUseTemporaryFileName(false);
        handler.setChmodOctal("600");
        return handler;
    }

Stacktrace while uploading a file:
>

    com.discover.sbcidv.integration.SbcIdvFtpIntegrationTests shouldSendGeneratedCsvToFakeFtpServer FAILED
    java.lang.BootstrapMethodError: call site initialization exception
        at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
        at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
        at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
        at org.springframework.integration.sftp.outbound.SftpMessageHandler.doChmod(SftpMessageHandler.java:76)
        at org.springframework.integration.file.remote.handler.FileTransferringMessageHandler.handleMessageInternal(FileTransferringMessageHandler.java:172)
    ...
    Caused by:
        java.lang.invoke.LambdaConversionException: Functional interface org.springframework.integration.file.remote.ClientCallbackWithoutResult is not an interface
            at java.lang.invoke.AbstractValidatingLambdaMetafactory.<init>(AbstractValidatingLambdaMetafactory.java:145)
            at java.lang.invoke.InnerClassLambdaMetafactory.<init>(InnerClassLambdaMetafactory.java:155)
            at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:299)
            at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
            ... 28 more

**Comment by artembilan** [comment]
How does it work if you use `spring-integration-file:5.0.5.RELEASE`?
On the other hand you don't need such a dependency - it is transient from the `spring-integration-sftp`.

**Comment by artembilan** [comment]
Closed with lack of reporter response and with the mentioned fix for the incompatible versions.
