### ISSUE TITLE
Poller throws java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by despondency** [spring-projects/spring-integration#2473]
The poller seems to be throwing this exception on consuming RSS feed.

`org.springframework.messaging.MessagingException: nested exception is java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller.lambda$run$0(AbstractPollingEndpoint.java:395) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:53) [spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) ~[spring-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:51) [spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller.run(AbstractPollingEndpoint.java:372) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899) ~[na:1.8.0_162]
	at java.util.TimSort.mergeAt(TimSort.java:516) ~[na:1.8.0_162]
	at java.util.TimSort.mergeForceCollapse(TimSort.java:457) ~[na:1.8.0_162]
	at java.util.TimSort.sort(TimSort.java:254) ~[na:1.8.0_162]
	at java.util.Arrays.sort(Arrays.java:1512) ~[na:1.8.0_162]
	at java.util.ArrayList.sort(ArrayList.java:1462) ~[na:1.8.0_162]
	at java.util.Collections.sort(Collections.java:175) ~[na:1.8.0_162]
	at org.springframework.integration.feed.inbound.FeedEntryMessageSource.populateEntryList(FeedEntryMessageSource.java:215) ~[spring-integration-feed-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.feed.inbound.FeedEntryMessageSource.doReceive(FeedEntryMessageSource.java:185) ~[spring-integration-feed-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.feed.inbound.FeedEntryMessageSource.receive(FeedEntryMessageSource.java:151) ~[spring-integration-feed-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.receiveMessage(SourcePollingChannelAdapter.java:236) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:249) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller.lambda$run$0(AbstractPollingEndpoint.java:378) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	... 13 common frames omitted
`

Integration flow is as following: 

`final DirectChannel directChannel = new DirectChannel();
            try {
                StandardIntegrationFlow standardIntegrationFlow = IntegrationFlows
                        .from(Feed
                                .inboundAdapter(new URL(rssFeed.getUrl()), rssFeed.getUrl()), c ->
                                c.poller(Pollers.fixedRate(5000, TimeUnit.SECONDS).maxMessagesPerPoll(1).errorHandler(e -> {
                                    logger.error("Exception occured trying to handle RssFeed {}", rssFeed, e);
                                })))
                        .channel(directChannel)
                        .get();`

**Comment by garyrussell** [comment]
According to [this](https://stackoverflow.com/questions/11441666/java-error-comparison-method-violates-its-general-contract) it looks like there is a bug in the comparator.

```java
@Override
public int compare(SyndEntry entry1, SyndEntry entry2) {
	Date date1 = getLastModifiedDate(entry1);
	Date date2 = getLastModifiedDate(entry2);
	if (date1 != null && date2 != null) {
		return date1.compareTo(date2);
	}
	if (date1 == null && date2 == null) {
		return 0;
	}
	return (date2 == null) ? 1 : 0;
}
```
It looks like it should be `return (date2 == null) ? 1 : (date1 == null) ? -1 : 0;`

**Comment by despondency** [comment]
Also this happens from time to time when the INT_METADATA_STORE is empty and i restart the application 

``org.springframework.messaging.MessagingException: nested exception is org.springframework.dao.DeadlockLoserDataAccessException: PreparedStatementCallback; SQL [INSERT INTO INT_METADATA_STORE(METADATA_KEY, METADATA_VALUE, REGION) SELECT ?, ?, ? FROM INT_METADATA_STORE WHERE METADATA_KEY=? AND REGION=? HAVING COUNT(*)=0(conn=13859) Deadlock found when trying to get lock; try restarting transaction; nested exception is java.sql.SQLTransactionRollbackException: (conn=13859) Deadlock found when trying to get lock; try restarting transaction
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller.lambda$run$0(AbstractPollingEndpoint.java:395) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:53) [spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) ~[spring-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:51) [spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller.run(AbstractPollingEndpoint.java:372) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
Caused by: org.springframework.dao.DeadlockLoserDataAccessException: PreparedStatementCallback; SQL [INSERT INTO INT_METADATA_STORE(METADATA_KEY, METADATA_VALUE, REGION) SELECT ?, ?, ? FROM INT_METADATA_STORE WHERE METADATA_KEY=? AND REGION=? HAVING COUNT(*)=0(conn=13859) Deadlock found when trying to get lock; try restarting transaction; nested exception is java.sql.SQLTransactionRollbackException: (conn=13859) Deadlock found when trying to get lock; try restarting transaction
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:266) ~[spring-jdbc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1402) ~[spring-jdbc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:620) ~[spring-jdbc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850) ~[spring-jdbc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:905) ~[spring-jdbc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.integration.jdbc.metadata.JdbcMetadataStore.tryToPutIfAbsent(JdbcMetadataStore.java:144) ~[spring-integration-jdbc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.jdbc.metadata.JdbcMetadataStore.put(JdbcMetadataStore.java:177) ~[spring-integration-jdbc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.jdbc.metadata.JdbcMetadataStore$$FastClassBySpringCGLIB$$1bf04d6a.invoke(<generated>) ~[spring-integration-jdbc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.integration.jdbc.metadata.JdbcMetadataStore$$EnhancerBySpringCGLIB$$3f748f2c.put(<generated>) ~[spring-integration-jdbc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.feed.inbound.FeedEntryMessageSource.getNextEntry(FeedEntryMessageSource.java:205) ~[spring-integration-feed-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.feed.inbound.FeedEntryMessageSource.doReceive(FeedEntryMessageSource.java:186) ~[spring-integration-feed-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.feed.inbound.FeedEntryMessageSource.receive(FeedEntryMessageSource.java:151) ~[spring-integration-feed-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.receiveMessage(SourcePollingChannelAdapter.java:236) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:249) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at com.sun.proxy.$Proxy92.call(Unknown Source) ~[na:na]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller.lambda$run$0(AbstractPollingEndpoint.java:378) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	... 13 common frames omitted
Caused by: java.sql.SQLTransactionRollbackException: (conn=13859) Deadlock found when trying to get lock; try restarting transaction
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:179) ~[mariadb-java-client-2.2.5.jar:na]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110) ~[mariadb-java-client-2.2.5.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:228) ~[mariadb-java-client-2.2.5.jar:na]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:216) ~[mariadb-java-client-2.2.5.jar:na]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:150) ~[mariadb-java-client-2.2.5.jar:na]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:183) ~[mariadb-java-client-2.2.5.jar:na]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-3.2.0.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-3.2.0.jar:na]
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$0(JdbcTemplate.java:855) ~[spring-jdbc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:605) ~[spring-jdbc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	... 44 common frames omitted
Caused by: java.sql.SQLException: Deadlock found when trying to get lock; try restarting transaction
Query is: INSERT INTO INT_METADATA_STORE(METADATA_KEY, METADATA_VALUE, REGION) SELECT ?, ?, ? FROM INT_METADATA_STORE WHERE METADATA_KEY=? AND REGION=? HAVING COUNT(*)=0, parameters ['http://feeds.feedburner.com/Javarevisited.http://feeds.feedburner.com/Javarevisited','1526258769340','DEFAULT','http://feeds.feedburner.com/Javarevisited.http://feeds.feedburner.com/Javarevisited','DEFAULT']
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153) ~[mariadb-java-client-2.2.5.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:255) ~[mariadb-java-client-2.2.5.jar:na]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209) ~[mariadb-java-client-2.2.5.jar:na]
	... 50 common frames omitted

No one else is writing to the table other than the application so it does not make sense for it to deadlock

**Comment by artembilan** [comment]
The `DeadlockLoserDataAccessException` has been fixed recently: #2470

**Comment by garyrussell** [comment]
@artembilan That was only for the lock registry; this is `JdbcMetadataStore`.

**Comment by artembilan** [comment]
Sorry, I was wrong with the fix.

@despondency ,

May you consider to make a `poller` of your `Feed.inboundAdapter()` as transactional?

The `JdbcMetadataStore` has `@Transactional` on its operations, but those are local for each of them.
We need have here a global transaction for the whole poll operation, so any reads and writes to the store will be done in the same TX. Even if you say "No one else is writing to the table", there is this one:
```
SELECT METADATA_VALUE FROM %SMETADATA_STORE WHERE METADATA_KEY=? AND REGION=? FOR UPDATE
```
The `FOR UPDATE` is a culprit here and with the different transactions we end up with such a dead lock. I believe...

**Comment by despondency** [comment]
Hello,

I think i've tried using .transactional() and it still deadlocked, I am going to try again on Monday, what about the first error that I've posted.


Also it appears that if i have two jvms consuming the same rss feed and sharing a metastore, they still get duplicated entries despite the metastore, is there any workaround for this?

**Comment by artembilan** [comment]
For the firs problem @garyrussell raised JIRA: https://jira.spring.io/browse/INT-4484.

We will fix it soon.

Re. your deadlock situation it might be great to have some full test-case to let us to play and reproduce. However I don't believe that we can do anything on the matter rather than the mentioned `.transactional()` to wrap all the metadata store operation to a single operation.

The duplicated entries sounds like a third problem.

Would you mind to raise a JIRA for dead lock with the code to reproduce?
Then raise a separate JIRA for duplcate entries with code to reproduce.

In most cases we are requesting a simple Spring Boot project somewhere on GitHub to let us to play with the code closer to  what in your target project. This way we minimize a difference in understanding the situation and the way we may test it.

Thanks for understanding.

**Comment by despondency** [comment]
Hello, 

I've made a minimal example. The problems I could reproduce are the IllegalStateException on the .sort() violating the general conduct, and the no synchronization between multiple applications on the same metadata store. The deadlock, sadly, I could not reproduce on the example. But you may have more luck.


I am attaching the source. The violation of the sort happens abruptly and depends on the data that is been read from the feeds. The CNN feed appears to be very prone to this. 

[example.zip](https://github.com/spring-projects/spring-integration/files/2089018/example.zip)

**Comment by artembilan** [comment]
See the fix for comparator: https://github.com/spring-projects/spring-integration/pull/2477
