### ISSUE TITLE
DelayHandler starts to process stored messages before all subsequent integration flows are properly initialized

### ISSUE THREAD

**Issue by mr-springtime** [spring-projects/spring-integration#2543]
Hi all!

In our application we are defining integration flows with the Spring integration Java DSL. To implement delayed mail sending we are using a Delayer with an underlying JDBC message store. 
When restarting our application we encounter several exceptions and have messages lost due to those exceptions.

Reproduction:

Precondition:
* Spring Integration flow defined with Java DSL containing a JDBC message store based Delayer
* Before starting the server, there need to be several messages in the DB due for immediate processing by the delayer

Issues during Server Startup:
1. When the server starts up, at some point the delayer task is scheduled and begins to produce messages for the flow immediately, while the subsequent channel is not properly initialized. The following exception is shown:

```
2018-08-22 09:08:00.154 ERROR [TheAppName,4c80a4a907a23580,0f1e892a2b06d82b,true] 20472 --- [ask-scheduler-3] o.s.integration.handler.LoggingHandler   : 
org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'application-1.theFlowContainingADelayer.channel#2'.; 
nested exception is org.springframework.integration.MessageDispatchingException: 
Dispatcher has no subscribers, failedMessage=GenericMessage [payload= .......the message .......]
    at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
    at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:445)
    at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394)
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
    at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
    at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:426)
    at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:336)
    at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:227)
    at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:115)
    at org.springframework.integration.handler.DelayHandler.doReleaseMessage(DelayHandler.java:381)
    at org.springframework.integration.handler.DelayHandler.access$000(DelayHandler.java:84)
    at org.springframework.integration.handler.DelayHandler$ReleaseMessageHandler.handleMessage(DelayHandler.java:474)
    at org.springframework.integration.handler.DelayHandler.releaseMessage(DelayHandler.java:373)
    at org.springframework.integration.handler.DelayHandler.lambda$releaseMessageAfterDelay$1(DelayHandler.java:349)
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload= .......the message .......]
    at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:138)
    at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
    at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
    ... 23 more

```

Sometimes the MessageDeliveryException contains a line that even the general errorChannel is not initialized with the defined subscriber yet.

A few lines later in the log, the debug output states, that a subscriber has been added to theFlowContainingADelayer as well as to the errorChannel and the delayer works as expected.

We've read about timing problems, missing application events and tried to apply the fix suggested in this post ( https://stackoverflow.com/questions/35802308/onapplicationevent-is-never-invoked-on-delayhandler ), but it did not resolve the issue.

2. The processed messages are permanently lost, as they are deleted in the DelayHandler before processing ( see: doReleaseMessage() ). Setting the DelayHandler to transactional didn't solve this issue.

The bug is reproducible with the most recent Spring release versions our application is based on: Spring Boot 2.0.4 (Spring Core/Integration/etc 5.0.7)

Best Regards

**Comment by garyrussell** [comment]
Event-driven consumers (consuming endpoints) are started in the earliest phase (`SmartLifecycle` - `Integer.MIN_VALUE`); producers (inbound adapters) are started in a late phase (`Integer.MAX_VALUE / 2`).

This is done precisely to prevent this condition (dispatcher has no subscribers).

The `DelayHandler` is a special case since it's a hybrid (consumer and async producer). It needs to be started after all other consumers, but before any producers.

Try setting it's consumer spec's phase to 0 to achieve that.

Making the delayer transactional should prevent message loss (as long as all downstream components run on the delayer thread).

**Comment by mr-springtime** [comment]
Hi Gary, 

thanks for the quick reply. We tried to apply your hints and added some more debug messages. Our current DSL setup is:

```
@Configuration
@IntegrationComponentScan
public class EmailConfiguration {

    ....

    @Bean
    public IntegrationFlow delayedEmailFlow(
            final  OurGenericSelector1 genericSelector1,
			final  OurGenericSelector2 genericSelector2,
            final ObjectMapper objectMapper,
            final JdbcMessageStore jdbcMessageStore) {
        return IntegrationFlows.from(QuoteAlertEmailChannels.EMAIL_INBOUND_CHANNEL)
                .filter(genericSelector1)
                .transform(objectMapper, "writeValueAsString")
                .delay(MESSAGE_STORE_GROUP_ID, delayerEndpointSpec -> {
                    delayerEndpointSpec.messageStore(jdbcMessageStore);
                    delayerEndpointSpec.defaultDelay(60000);
                })
				// bean definition method in the same configuration class
                .transform(jsonToObjectTransformer(objectMapper, OurMessage.class))
                .filter(genericSelector2)
                .channel(EmailChannels.EMAIL_SENDING_OUTBOUND_CHANNEL)
                .get();
    }
	
	....
	
}

```

We added `delayerEndpointSpec.phase(Integer.MAX_VALUE)` , but no effect.

Also, setting the delayer to transactional  ( `delayerEndpointSpec.transactional(true); ` ) did not prevent message loss.

In the Transformer we added a debug statement and found, that even the transformer is not reached at first. Given that there can be arbitrarily complex flows after this one, is there a way to reliably ensure start order? If we would convert all elements combined by the DSL from Objects into specs, this would clutter the code and make the DSL as verbose as XML.

**Comment by garyrussell** [comment]
I am having trouble reproducing your problem. It turns out that this has nothing to do with the phase; `IntegrationFlow` beans are always started in phase 0 and their components are started from last to first. The internal phase on consumer specs is not used.

Furthermore, persisted messages, that are past due, are not emitted until the delayer receives a `ContextRefreshedEvent`, which means all components must have been `start()`ed (and hence subscribers all set up) before messages are emitted.

Can you provide a DEBUG log from a run that exhibits this behavior?

**Comment by garyrussell** [comment]
Regarding transactions, it turns out that `.transactional()` just makes the inserts transactional, to make the delayed sends transactional, we need to add a transaction interceptor to the `delayedAdviceChain`...

```java
@Bean
public IntegrationFlow flow(JdbcMessageStore store, PlatformTransactionManager tm) {
	return f -> f.delay("foo", d -> {
				d.messageStore(store)
					.transactional()
					.delayedAdvice(new TransactionInterceptorBuilder().transactionManager(tm).build())
					.defaultDelay(30_000);
			})
			.channel(new DirectChannel());
}
```

However, while it solves the issue of "lost" messages, it doesn't entirely help because the send is not rescheduled and the message will sit in the store until the next time the app is started. https://jira.spring.io/browse/INT-4527

**Comment by mr-springtime** [comment]
We retried to day and can confirm, that the `onApplicationEvent(ContextRefreshedEvent event)` is called on the DelayHandler, however the timing is still not right, the MessageDeliveryException exception still occurs.

As I'm working on a client's codebase at the moment, it's tough to share logs (especially on Github), as they might exhibit sensitive information. Is there a chance to discuss this topic directly? I've sent you an invite via LinkedIn to exchange contact information and eventually later summarize the root cause and add it to this thread in an anonymized fashion.

**Comment by garyrussell** [comment]
Sorry, I am not able to provide one:one support.

Given this application...

```java
@SpringBootApplication
public class Igh25431Application {

	public static void main(String[] args) {
		SpringApplication.run(Igh25431Application.class, args);
	}

	@Bean
	public JdbcMessageStore store(DataSource dataSource) {
		return new JdbcMessageStore(dataSource);
	}

	@Bean
	public ApplicationRunner runner(ApplicationContext context) {
		return args -> {
			MessageChannel flowInput = context.getBean("flow.input", MessageChannel.class);
			for (int i = 0; i < 1; i++) {
				flowInput.send(new GenericMessage<>("foo"));
			}
		};
	}

	@Bean
	public IntegrationFlow flow(JdbcMessageStore store, PlatformTransactionManager tm) {
		return f -> f.delay("foo", d -> {
					d.messageStore(store)
						.transactional()
						.delayedAdvice(new TransactionInterceptorBuilder().transactionManager(tm).build())
						.defaultDelay(30_000);
				})
				.channel("otherFlow.input");
	}

	@Bean
	public IntegrationFlow otherFlow() {
		return f -> f.log();
	}

	@EventListener
	public void refresh(ContextRefreshedEvent event) {
		System.out.println(event);
	}

}
```

The log looks like this...

```
2018-08-23 10:54:11.321 DEBUG 90948 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting bean 'otherFlow.org.springframework.integration.config.ConsumerEndpointFactoryBean#0' of type [class org.springframework.integration.config.ConsumerEndpointFactoryBean]
2018-08-23 10:54:11.321  INFO 90948 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {bridge} as a subscriber to the 'otherFlow.input' channel
2018-08-23 10:54:11.321  INFO 90948 --- [           main] o.s.integration.channel.DirectChannel    : Channel 'application.otherFlow.input' has 1 subscriber(s).
2018-08-23 10:54:11.321  INFO 90948 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started otherFlow.org.springframework.integration.config.ConsumerEndpointFactoryBean#0
2018-08-23 10:54:11.321 DEBUG 90948 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Successfully started bean 'otherFlow.org.springframework.integration.config.ConsumerEndpointFactoryBean#0'
2018-08-23 10:54:11.321 DEBUG 90948 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting bean 'otherFlow.org.springframework.integration.config.ConsumerEndpointFactoryBean#1' of type [class org.springframework.integration.config.ConsumerEndpointFactoryBean]
2018-08-23 10:54:11.321  INFO 90948 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {bridge} as a subscriber to the 'otherFlow.channel#1' channel
2018-08-23 10:54:11.321  INFO 90948 --- [           main] o.s.integration.channel.DirectChannel    : Channel 'application.otherFlow.channel#1' has 1 subscriber(s).
2018-08-23 10:54:11.321  INFO 90948 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started otherFlow.org.springframework.integration.config.ConsumerEndpointFactoryBean#1
2018-08-23 10:54:11.321 DEBUG 90948 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Successfully started bean 'otherFlow.org.springframework.integration.config.ConsumerEndpointFactoryBean#1'
2018-08-23 10:54:11.322 DEBUG 90948 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory'
2018-08-23 10:54:11.322 DEBUG 90948 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'org.springframework.integration.config.IdGeneratorConfigurer#0'
2018-08-23 10:54:11.322 DEBUG 90948 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'igh25431Application'

org.springframework.context.event.ContextRefreshedEvent[source=org.springframework.context.annotation.AnnotationConfigApplicationContext@7f1302d6: startup date [Thu Aug 23 10:54:09 EDT 2018]; root of context hierarchy]
```

i.e. all `Channel 'x' has 1 subscriber(s).` should all appear before the context refreshed event. If they don't then something is wrong with the configuration; perhaps some component does not have `autoStartup`?

**Comment by mr-springtime** [comment]
Adding the listener we found two events:

```
// initialization of the Actuator management port right before, otherwise this application does not have web controllers
Line 273: org.springframework.context.event.ContextRefreshedEvent[source=org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@7fce4c0b: startup date [Thu Aug 23 15:55:57 UTC 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@48e8c32a]

Line 275: 2018-08-23 15:55:58.337  INFO [FreightNetAirProcess,,,] 13452 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0

// .... MessageDeliveryExceptions inbetween ....


// ongoing setup of the channels, AMQP/RabbitMQ...

Line 902: 2018-08-23 15:55:58.379  INFO [FreightNetAirProcess,,,] 13452 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 1073741823

Line 934: 2018-08-23 15:55:58.721  INFO [FreightNetAirProcess,,,] 13452 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147483647
Line 935: org.springframework.context.event.ContextRefreshedEvent[source=org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@48e8c32a: startup date [Thu Aug 23 15:55:27 UTC 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@4aedaf61]
```

Seems like the first ContextRefreshedEvent already triggers the start of the Delayer.

**Comment by garyrussell** [comment]
`AnnotationConfigServletWebServerApplicationContext@7fce4c0b`
`AnnotationConfigServletWebServerApplicationContext@48e8c32a`

For some reason, you have 2 application contexts; if you have SI components in the first that are communicating with components in the second then all bets are off, or you need to start the second context before you start the context in which the delayer is declared.

**Comment by mr-springtime** [comment]
Hi Gary, 

we did some further research with respect to the MessageDeliveryException. Our Kibana log DB shows, that the problem started, when we migrated from Spring Boot 1.5.3 to Boot 2.0.2. I pulled out the Boot 1.5.3 version (Spring Integration 4.3.1) from our repo and compared the startup to Boot 2.0.2. 

Both versions have two contexts: one for the management part and one for the application. During startup they both fire one event each in the order: 

1. management
2. application.

In both versions, the DelayHandler is registered with the BeanFactory of the application context.

When setting a debug breakpoint in the DelayerHandler event handling method, the following happens:

- Boot 1.5.3 -> only the one correct event (application) is received
- Boot 2.0.2 -> two events are received (management, then application). So the handler starts to work as soon as the management context is up

When launching the project we had a common spring starters setup for all servers. Thus the boot applications might include more than they actually need for their purpuse. We're in the process of cleaning that up, but at first sight, this issue seemed to be introduced by the Boot 2.0.2 update.

We weren't able to identify yet, what caused the DelayHandler to be instantiated so early. There were some statements in the log related to JMX, and disabling JMX on the whole application made those statements go away, but it did not solve the problem of the MessageDeliveryExceptions due to early startup.

If you need more information or a dump of the contexts of the events for each version, please let us know.

Thanks!

**Comment by garyrussell** [comment]
Thanks for the analysis - it's a bug in the `DelayHandler` - it needs to check that the refreshed event is from the context in which it is declared. I am not sure why it works with Boot 1.5; perhaps some timing changed. I'll add the fix to the PR for https://jira.spring.io/browse/INT-4527. 

BTW, the current boot version is 2.0.4.

**Comment by mr-springtime** [comment]
Thanks for providing a fix!

**Comment by garyrussell** [comment]
@mr-springtime If you need a work-around in the meantime, something like this should work...

```java
@Bean
public static BeanPostProcessor eventSuppressor(final ApplicationContext context) {
	return new BeanPostProcessor() {

		@Override
		public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
			if (bean instanceof DelayHandler) {
				MethodInterceptor fixer = new MethodInterceptor() {

					@Override
					public Object invoke(MethodInvocation invocation) throws Throwable {
						if (invocation.getMethod().getName().equals("onApplicationEvent")) {
							ContextRefreshedEvent event = (ContextRefreshedEvent) invocation.getArguments()[0];
							if (!event.getApplicationContext().equals(context)) {
								System.out.println("Skipping event");
								return null;
							}
						}
						return invocation.proceed();
					}

				};
				if (bean instanceof Advised) {
					((Advised) bean).addAdvice(fixer);
				}
				else {
					ProxyFactory pf = new ProxyFactory(bean);
					pf.addAdvice(fixer);
					return pf.getProxy();
				}
			}
			return bean;
		}

	};
}
```
