### ISSUE TITLE
Enhancement - ChainFileListFilter constructors

### ISSUE THREAD

**Issue by lrk** [spring-projects/spring-integration#2569]
Hi,

While configuring a `ChainFileListFilter` with XML document, Spring Integration complain about `ChainFileListFilter`'s constructors to not match the given `<constructor-arg>`.

example: 
```
...
<bean id="myInputFileFilter"
          class="org.springframework.integration.file.filters.ChainFileListFilter">
        <constructor-arg>
            <list>
                <bean class="org.springframework.integration.file.filters.IgnoreHiddenFileListFilter"/>
                <bean class="org.springframework.integration.file.filters.RegexPatternFileListFilter">
                    <constructor-arg
                        value="myregex..."/>
                </bean>
                ...
           </list>
        </constructor-arg>    
</bean>
...
```
give me this error:
```
18:13:37.695| ERROR | Application run failed                                                                                                                                 | org.springframework.boot.SpringApplication.reportFailure(SpringApplication.java:833)
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ref01CompositeInputFileFilter' defined in class path resource [myflow-config.xml]: Could not resolve matching constructor (hint: specify index/type/name arguments for simple parameters to avoid type ambiguities)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:243)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1270)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137)
	at fr.enedis.distribution.estock.imports.application.ApplicationEmbedded.main(ApplicationEmbedded.java:46)

Process finished with exit code 1

```

As described in documentation, `ChainFileListFilter` should be a simple extension of `CompositeFileListFilter`. I think it should be usable in the same way.

My Spring Integration version: 5.0.3

I suggest for `ChainFileListFilter` to implement constructors matching it super class:

```
...
public class ChainFileListFilter<F> extends CompositeFileListFilter<F> {

    public ChainFileListFilter() {
        super();
    }

    public ChainFileListFilter(Collection<? extends FileListFilter<F>> fileFilters) {
        super(fileFilters);
    }
...
```

**Comment by lrk** [comment]
@artembilan done
