### ISSUE TITLE
Problems after upgrading to spring 5.0

### ISSUE THREAD

**Issue by bojanv55** [spring-projects/spring-integration#2658]
We are using "<spring.integration.version>5.0.8.RELEASE</spring.integration.version>" in combination with "<spring.version>5.0.9.RELEASE</spring.version>".

The problem we are facing is that there are a lot of messages in Unacked state on channels that are without consumers. Java shows that this socket connection is still open, but I guess somehow ListenerContainer is not running.

When we restart the component, all messages are sent to dead-letter queue. 

I know that this is not that much info, but wanted to ask if you already experienced this issues before?

![image](https://user-images.githubusercontent.com/1422698/49744438-09d7c200-fc9d-11e8-9da0-178187df0211.png)

**Comment by garyrussell** [comment]
On advice from the RabbitMQ team, the `prefetchCount` was increased to 250 by default, to get better out-of-the-box performance.

[2.0 what's new](https://docs.spring.io/spring-amqp/reference/html/_change_history.html#_prefetch_default_value).

To revert to the previous behavior, set it back to 1.

**Comment by garyrussell** [comment]
Oh; you have no consumers (and I see your prefetch is 5); that is weird, even with manual acks, they should go back to ready when there's no consumer.

I suggest you ask the RabbitMQ folks on the rabbitmq-users google group to see if they can explain what might cause this.

**Comment by garyrussell** [comment]
Oh; you have no consumers (and I see your prefetch is 5); that is weird, even with manual acks, they should go back to ready when there's no consumer.

But the channel is still open; 5.0.8 uses Spring AMQP 2.0.4; my guess is you have auto-recovery enabled in the RabbitMQ client, which is discouraged, since Spring AMQP has its own recovery mechanisms (and has had since day 1).

We fixed some auto-recovery co-existence issues in 2.0.7 (which is pulled in by Spring Integration 5.0.9.

**Comment by bojanv55** [comment]
Will try to check auto-recovery (to disable it), and then test again to see if that was the problem.

**Comment by garyrussell** [comment]
In that case, I don't see how it's possible to have an active channel with no consumers; is there anything interesting in the log?

**Comment by bojanv55** [comment]
Seems OK now when we updated spring integration version...

**Comment by bojanv55** [comment]
Hi Garry. Seems I was wrong. Same thing happening again. But this time I managed to do heap dump.

For this channel that I can see in rabbitmq admin pages, (showing unacked messages, and no consumers) I have following data in heap dump:

ChannelN.shutdownCause.detailMessage
`clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer ConsumerDecorator{queue='somequeue', consumerTag='sometag-3707bd7f-1533-49e8-94e7-fb75fdcebe70'} (something.866-3707bd7f-1533-49e8-94e7-fb75fdcebe70) method handleDelivery for channel AMQChannel(amqp://address@10.200.32.230:5672/somevhost,35), class-id=0, method-id=0)`

backtrace:
```
class com.rabbitmq.client.impl.ChannelN @ 0x689acc390
class com.rabbitmq.client.impl.ChannelN @ 0x689acc390
class com.rabbitmq.client.impl.StrictExceptionHandler @ 0x6885e3858
class com.rabbitmq.client.impl.StrictExceptionHandler @ 0x6885e3858
class com.rabbitmq.client.impl.ConsumerDispatcher$5 @ 0x689ab95b8
class com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable @ 0x689ab9688
class java.util.concurrent.ThreadPoolExecutor @ 0x68787f358
class java.util.concurrent.ThreadPoolExecutor$Worker @ 0x687a3db70
class java.lang.Thread @ 0x68789ef30
```

suppressedExceptions
`java.util.Collections$UnmodifiableRandomAccessList @ 0x687805398`

**Comment by garyrussell** [comment]
And this channel (`#35`) is the one on the admin UI that has unack'd messages?

Very strange; you might want to reach out to the RabbitMQ guys on the rabbitmq-users google group.

I am not sure what you mean by "suppressedExceptions".

Did you get a thread dump too?

**Comment by bojanv55** [comment]
Yes. Exactly same as in the image I posted in 1st post (just this time I have channel 10.200.32.223:5672 (35)) -> notice that it is .223 and in code it is .230 ->since 230 is loadbalancer and .223 is rabbit node.

suppressedExceptions is field that I have in heap dump. Yes I have also thread dump but there is nothing that shows dead-locks or smth. like that.

This is screenshot of channel dump:

![image](https://user-images.githubusercontent.com/1422698/54367701-22c48a80-4673-11e9-9e73-a79c45dfd1e7.png)

also this is scr. shot of ChannelManager holding reference to this channel (shouldn't it be garbage collected since there was an Exception?)

![image](https://user-images.githubusercontent.com/1422698/54367808-4982c100-4673-11e9-9ede-2c91b49537c0.png)

**Comment by bojanv55** [comment]
And this is thread dump of this thread 40110 referenced in ChannelManager (that I extracted from heap dump)

```
pool-3-thread-40110
  at java.net.SocketOutputStream.socketWrite0(Ljava/io/FileDescriptor;[BII)V (Native Method)
  at java.net.SocketOutputStream.socketWrite([BII)V (SocketOutputStream.java:109)
  at java.net.SocketOutputStream.write([BII)V (SocketOutputStream.java:153)
  at java.io.BufferedOutputStream.write([BII)V (BufferedOutputStream.java:122)
  at java.io.DataOutputStream.write([BII)V (DataOutputStream.java:107)
  at java.io.ByteArrayOutputStream.writeTo(Ljava/io/OutputStream;)V (ByteArrayOutputStream.java:167)
  at com.rabbitmq.client.impl.Frame.writeTo(Ljava/io/DataOutputStream;)V (Frame.java:192)
  at com.rabbitmq.client.impl.SocketFrameHandler.writeFrame(Lcom/rabbitmq/client/impl/Frame;)V (SocketFrameHandler.java:144)
  at com.rabbitmq.client.impl.AMQConnection.writeFrame(Lcom/rabbitmq/client/impl/Frame;)V (AMQConnection.java:513)
  at com.rabbitmq.client.impl.AMQCommand.transmit(Lcom/rabbitmq/client/impl/AMQChannel;)V (AMQCommand.java:119)
  at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(Lcom/rabbitmq/client/impl/AMQCommand;)V (AMQChannel.java:333)
  at com.rabbitmq.client.impl.AMQChannel.transmit(Lcom/rabbitmq/client/impl/AMQCommand;)V (AMQChannel.java:309)
  at com.rabbitmq.client.impl.ChannelN.basicPublish(Ljava/lang/String;Ljava/lang/String;ZZLcom/rabbitmq/client/AMQP$BasicProperties;[B)V (ChannelN.java:656)
  at com.rabbitmq.client.impl.ChannelN.basicPublish(Ljava/lang/String;Ljava/lang/String;ZLcom/rabbitmq/client/AMQP$BasicProperties;[B)V (ChannelN.java:639)
  at sun.reflect.GeneratedMethodAccessor125.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (Method.java:498)
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object; (CachingConnectionFactory.java:1032)
  at com.sun.proxy.$Proxy144.basicPublish(Ljava/lang/String;Ljava/lang/String;ZLcom/rabbitmq/client/AMQP$BasicProperties;[B)V (Unknown Source)
  at org.springframework.amqp.rabbit.core.RabbitTemplate.sendToRabbit(Lcom/rabbitmq/client/Channel;Ljava/lang/String;Ljava/lang/String;ZLorg/springframework/amqp/core/Message;)V (RabbitTemplate.java:2020)
  at org.springframework.amqp.rabbit.core.RabbitTemplate.doSend(Lcom/rabbitmq/client/Channel;Ljava/lang/String;Ljava/lang/String;Lorg/springframework/amqp/core/Message;ZLorg/springframework/amqp/rabbit/support/CorrelationData;)V (RabbitTemplate.java:2008)
  at org.springframework.amqp.rabbit.core.RabbitTemplate.lambda$send$3(Ljava/lang/String;Ljava/lang/String;Lorg/springframework/amqp/core/Message;Lorg/springframework/amqp/rabbit/support/CorrelationData;Lcom/rabbitmq/client/Channel;)Ljava/lang/Object; (RabbitTemplate.java:862)
  at org.springframework.amqp.rabbit.core.RabbitTemplate$$Lambda$656.doInRabbit(Lcom/rabbitmq/client/Channel;)Ljava/lang/Object; (Unknown Source)
  at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(Lorg/springframework/amqp/rabbit/core/ChannelCallback;Lorg/springframework/amqp/rabbit/connection/ConnectionFactory;)Ljava/lang/Object; (RabbitTemplate.java:1850)
  at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(Lorg/springframework/amqp/rabbit/core/ChannelCallback;Lorg/springframework/amqp/rabbit/connection/ConnectionFactory;)Ljava/lang/Object; (RabbitTemplate.java:1793)
  at org.springframework.amqp.rabbit.core.RabbitTemplate.send(Ljava/lang/String;Ljava/lang/String;Lorg/springframework/amqp/core/Message;Lorg/springframework/amqp/rabbit/support/CorrelationData;)V (RabbitTemplate.java:861)
  at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Lorg/springframework/amqp/core/MessagePostProcessor;Lorg/springframework/amqp/rabbit/support/CorrelationData;)V (RabbitTemplate.java:963)
  at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Lorg/springframework/amqp/core/MessagePostProcessor;)V (RabbitTemplate.java:955)
  at com.smth.utils.RabbitUtils.lambda$sendWithRetryWithPersistence$6(Ljava/lang/String;Ljava/lang/String;Lorg/springframework/amqp/core/Message;Lorg/springframework/amqp/rabbit/core/RabbitTemplate;)V (RabbitUtils.java:148)
  at com.smth.utils.RabbitUtils$$Lambda$1005.accept(Ljava/lang/Object;)V (Unknown Source)
  at com.smth.utils.RabbitUtils.retry(Lorg/springframework/amqp/rabbit/core/RabbitTemplate;Ljava/util/function/Consumer;)V (RabbitUtils.java:58)
  at com.smth.utils.RabbitUtils.sendWithRetryWithPersistence(Lorg/springframework/amqp/rabbit/core/RabbitTemplate;Ljava/lang/String;Ljava/lang/String;Lorg/springframework/amqp/core/Message;)V (RabbitUtils.java:147)
  at com.smth.domain.service.OwnDataServiceImpl.sendDataChangesToRabbit(Ljava/util/List;ILjava/lang/String;Z)Z (OwnDataServiceImpl.java:265)
  at com.smth.export.component.clientData.ClientDataHandler.sendMatchMarkets(Lcom/Dataarbitrage/project/lcoo/export/component/rediscache/json/ExportDataParams;Ljava/util/Map;)V (ClientDataHandler.java:283)
  at com.smth.export.component.clientData.ClientDataHandler.sendClientData(Lcom/Dataarbitrage/project/lcoo/domain/service/filter/ExportImplementationCommon;Ljava/util/Map;)V (ClientDataHandler.java:248)
  at com.smth.export.component.clientData.ClientDataHandler.performClientDataForBookmaker(Lcom/Dataarbitrage/project/lcoo/domain/model/event/Event;Lcom/Dataarbitrage/project/lcoo/export/component/rediscache/json/ExportDataParams;Ljava/util/Map;)Lcom/Dataarbitrage/project/lcoo/domain/model/event/Event; (ClientDataHandler.java:235)
  at com.smth.export.component.clientData.ClientDataHandler.onEvent(Lcom/Dataarbitrage/project/lcoo/domain/model/event/Event;Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;)V (ClientDataHandler.java:198)
  at com.smth.export.component.clientData.ClientDataHandler.onEvent(Lcom/Dataarbitrage/project/lcoo/domain/model/event/Event;Ljava/lang/String;Lorg/springframework/amqp/core/Message;)V (ClientDataHandler.java:179)
  at com.smth.export.component.clientData.ClientDataHandler.onMessage(Lorg/springframework/amqp/core/Message;)V (ClientDataHandler.java:170)
  at com.smth.export.component.clientData.ClientDataHandler.handleMessage(Lorg/springframework/amqp/core/Message;)V (ClientDataHandler.java:138)
  at sun.reflect.GeneratedMethodAccessor234.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (Method.java:498)
  at sun.reflect.misc.Trampoline.invoke(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (MethodUtil.java:71)
  at sun.reflect.GeneratedMethodAccessor75.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (Method.java:498)
  at sun.reflect.misc.MethodUtil.invoke(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (MethodUtil.java:275)
  at java.beans.Statement.invokeInternal()Ljava/lang/Object; (Statement.java:292)
  at java.beans.Statement.access$000(Ljava/beans/Statement;)Ljava/lang/Object; (Statement.java:58)
  at java.beans.Statement$2.run()Ljava/lang/Object; (Statement.java:185)
  at java.security.AccessController.doPrivileged(Ljava/security/PrivilegedExceptionAction;Ljava/security/AccessControlContext;)Ljava/lang/Object; (Native Method)
  at java.beans.Statement.invoke()Ljava/lang/Object; (Statement.java:182)
  at java.beans.Statement.execute()V (Statement.java:173)
  at com.smth.utils.ManualAckMessageHandler$1.doWithRetry(Lorg/springframework/retry/RetryContext;)Ljava/lang/Void; (ManualAckMessageHandler.java:125)
  at com.smth.utils.ManualAckMessageHandler$1.doWithRetry(Lorg/springframework/retry/RetryContext;)Ljava/lang/Object; (ManualAckMessageHandler.java:121)
  at org.springframework.retry.support.RetryTemplate.doExecute(Lorg/springframework/retry/RetryCallback;Lorg/springframework/retry/RecoveryCallback;Lorg/springframework/retry/RetryState;)Ljava/lang/Object; (RetryTemplate.java:287)
  at org.springframework.retry.support.RetryTemplate.execute(Lorg/springframework/retry/RetryCallback;Lorg/springframework/retry/RecoveryCallback;)Ljava/lang/Object; (RetryTemplate.java:180)
  at com.smth.utils.ManualAckMessageHandler.executeWithRetry(Ljava/beans/Statement;Lorg/springframework/amqp/core/Message;)V (ManualAckMessageHandler.java:120)
  at com.smth.utils.ManualAckMessageHandler.lambda$onMessage$0(Ljava/beans/Statement;Lorg/springframework/amqp/core/Message;)V (ManualAckMessageHandler.java:106)
  at com.smth.utils.ManualAckMessageHandler$$Lambda$670.run()V (Unknown Source)
  at java.util.concurrent.Executors$RunnableAdapter.call()Ljava/lang/Object; (Executors.java:511)
  at java.util.concurrent.FutureTask.run()V (FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run()V (ThreadPoolExecutor.java:617)
  at java.lang.Thread.run()V (Thread.java:745)
```

and this is thread dump done 10 seconds before I did heap dump with Thread.dump command only:

```
"pool-3-thread-40110" #189191 prio=5 os_prio=0 tid=0x00007f52bc00c000 nid=0x47d1 waiting on condition [0x00007f53a8ad5000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006890327a8> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bojanv55** [comment]
OK, Now I have same thing on other channel/queue. Did dump and again - same channel with same exception. But this time I could do more thread dumps if needed (If you think this can be due to spring)?

**Comment by garyrussell** [comment]
I think you should reach out to the RabbitMQ for their take on it; I don't have much knowledge about ChannelN internals.

However, it looks to me like it's blocked on a socket write, which doesn't make sense if the channel was closed.

>pool-3-thread-40110
>  at java.net.SocketOutputStream.socketWrite0(Ljava/io/FileDescriptor;[BII)V (Native Method)

**Comment by bojanv55** [comment]
I guess those thread dumps I posted are just dumps from ChannelManager which maintains a lot of threads internally. Biggest question here is why this channel that has shutdownCause variable != null still shown in channels list and not GC-ed. I guess this UnmodifiableRandomAccessList Exception is cause of it not being removed normally.

**Comment by garyrussell** [comment]
Makes sense; I just don't see how you can have a channel open on the broker, but that shutdown exception indicates that the channel is closed. Hence my suggestion to talk to the Rabbit folks.

If you can reproduce it reliably in a small app, I'd be happy to help debug it.

**Comment by garyrussell** [comment]
I just tested it with this...

```java
channel.basicConsume(this.queue, new DefaultConsumer(channel) {

	@Override
	public void handleDelivery(String consumerTag, Envelope envelope, BasicProperties properties,
			byte[] body) throws IOException {

		throw new RuntimeException("x");
	}
});
```

And I see the channel closed ok on the console, the message delivered to another consumer, along with...

>2019-03-14 13:21:04.622 ERROR 1752 --- [pool-1-thread-4] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer (amq.ctag-4AqDVpaxxC5LJMryfHQS7Q) method handleDelivery for channel AMQChannel(amqp://guest@127.0.0.1:5672/,1), class-id=0, method-id=0)

**Comment by garyrussell** [comment]
Ah - suppressed exceptions is indeed a list - can you drill into the list in the heap dump to find the root cause of the exception?

I see the folllowing from my test above...

- class java.lang.Throwable
- com.rabbitmq.client.ShutdownSignalException: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer (amq.ctag-oh9DklJW2C7Hg7QseE574Q) method handleDelivery for channel AMQChannel(amqp://guest@127.0.0.1:5672/,1), class-id=0, method-id=0)
- java.lang.Exception
- java.lang.RuntimeException: x

The last one being my root cause.

**Comment by bojanv55** [comment]
I guess it must be removed from heap dump?

![image](https://user-images.githubusercontent.com/1422698/54379751-4810c300-468a-11e9-838c-39f3926f7435.png)

**Comment by bojanv55** [comment]
Just also to mention that this is happening on 2 different rabbitmq instances (one newer and one older). Also, the code that produces this problem has a lot of queue creation at runtime and queue deletion at runtime.

**Comment by garyrussell** [comment]
I just noticed you have nested `ShutdownSignalExceptions` in the channel, can you try drilling into the `cause` to see if it has `suppressedExceptions` ?

**Comment by bojanv55** [comment]
If you are talking about shutdownCause and cause field inside - it is Reference cycle (as shown in jprofiler). Only data that I can find that could be potentially useful are this arrays in backtraces which contain a lot of integer. I guess one of those are line numbers or smthn.

![image](https://user-images.githubusercontent.com/1422698/54385619-5ca78800-4697-11e9-92bc-40913f3a85d4.png)

![image](https://user-images.githubusercontent.com/1422698/54385645-7052ee80-4697-11e9-94b8-3d5e12c26763.png)

![image](https://user-images.githubusercontent.com/1422698/54385669-82349180-4697-11e9-878f-040916772736.png)

**Comment by garyrussell** [comment]
Shucks; I am out of ideas.

**Comment by michaelklishin** [comment]
One thing I spotted in the trace and shutdown message. The code uses [StrictExceptionHandler](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/StrictExceptionHandler.java) which will close the channel when a consumer operation throws an exception your own code does not handle. In some scenarios, e.g. in the presence of alarms,
the channel.close frame won't get to RabbitMQ, so RabbitMQ will consider the channel open at least for a while but the client will consider it to be closed.

You can switch to a [more forgiving](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/ForgivingExceptionHandler.java) handler. It makes more sense in most cases. The shutdown detail is clear evidence of unhandled exceptions in your Consumer interface implementation.

Beyond that, [Wireshark](https://www.rabbitmq.com/amqp-wireshark.html) will provide most relevant information as to what the client sends and receives. You can close the channel's connection to [automatically requeue](http://www.rabbitmq.com/confirms.html) unacknowledged deliveries.

Also I'd like to point out that there are prefetch values beyond 250 and 1 that might be worth using ;) But the smoking gun right now is the strict exception handler that attempts to close the channel.
Please beef up exception handling in the consumer before you do anything else.

**Comment by bojanv55** [comment]
Thanks. Will try it tomorrow. We are using internaly Spring's SimpleListenerContainer, so I thought it is handling all exception processing inside its message handler methods (and not bubbling exceptions all way up to channel code).

**Comment by garyrussell** [comment]
Thanks @michaelklishin 

The container **does** catch all listener exceptions and `basicReject`s the message.

However, with the simple container, the listener is not invoked on the consumer thread. The `handleDelivery` code is very simple; in the normal case, it justputs the message in a queue; the only exception I can see it could throw (unless there is a bug I am not seeing - and this code has been around for years) is an `InterruptedException` which is caught anyway.

Shouldn't we see this log from the strict handler

https://github.com/rabbitmq/rabbitmq-java-client/blob/1bd2ea4508e6206fc84faa81c8158a276446b8f5/src/main/java/com/rabbitmq/client/impl/StrictExceptionHandler.java#L69-L70

though? It would help to see exactly what the exception was.

The newer `DirectMessageListenerContainer` runs the listener on the consumer thread; see [Choosing a Container](https://docs.spring.io/spring-amqp/reference/#choose-container) for an explanation of why there are two containers, and their differences regarding functionality.

**Comment by bojanv55** [comment]
OK, I managed to capture this time wireshark data, and some of chronon recording (not sure if this all is going to help but...). Ill try to check tomorrow a bit more. Here is so fat what I can see in logs:

`com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer ConsumerDecorator{queue='phoenix.lcoo.q.clientodds.oddschange.lo.26495', consumerTag='phoenix.lcoo.ClientOddsComponent.866-dc55d4cd-7f9d-4427-b822-aafa46c628ef'} (phoenix.lcoo.ClientOddsComponent.866-dc55d4cd-7f9d-4427-b822-aafa46c628ef) method handleDelivery for channel AMQChannel(amqp://betradar@100.68.66.127:5672/betradarMQ,13), class-id=0, method-id=0)`

![image](https://user-images.githubusercontent.com/1422698/54549948-6be64880-49ab-11e9-9745-8c87686a32aa.png)
(this is last packet I can find with this consumer ID)

Here i got `java.io.IOException: Unknown consumerTag` for this same consumer ID ("phoenix.lcoo.ClientOddsComponent.866-dc55d4cd-7f9d-4427-b822-aafa46c628ef"):

![image](https://user-images.githubusercontent.com/1422698/54550196-da2b0b00-49ab-11e9-922b-38aacb3079ba.png)

![image](https://user-images.githubusercontent.com/1422698/54550408-3f7efc00-49ac-11e9-8569-baba5f355a30.png)

**Comment by bojanv55** [comment]
OK. I think I finally found a reason with chronon tracing. Can you @michaelklishin please have a look:

```
//ChannelN.java
 public void basicCancel(final String consumerTag)
        throws IOException
    {
        final Consumer originalConsumer = _consumers.get(consumerTag);
        if (originalConsumer == null)
            throw new IOException("Unknown consumerTag"); <--------- THIS ONE IS THROWN HERE
        BlockingRpcContinuation<Consumer> k = new BlockingRpcContinuation<Consumer>() {
            public Consumer transformReply(AMQCommand replyCommand) {
                replyCommand.getMethod();
                _consumers.remove(consumerTag); 
                dispatcher.handleCancelOk(originalConsumer, consumerTag);
                return originalConsumer;
            }
        };

        rpc(new Basic.Cancel(consumerTag, false), k);

        try {
            k.getReply(); 
        } catch(ShutdownSignalException ex) {
            throw wrap(ex);
        }
    }


//CachingConnectionFactory.java
	}
			catch (InvocationTargetException ex) {
				if (this.target == null || !this.target.isOpen()) { <---- isOpen returns TRUE
					// Basic re-connection logic...
					if (logger.isDebugEnabled()) {
						logger.debug("Detected closed channel on exception.  Re-initializing: " + this.target);
					}
					this.target = null;
					synchronized (this.targetMonitor) {
						if (this.target == null) {
							this.target = createBareChannel(this.theConnection, this.transactional);
						}
					}
				}
				throw ex.getTargetException(); <---- rethrown here
			}

//ConsumerDispatcher.java
public void handleDelivery(final Consumer delegate,
                               final String consumerTag,
                               final Envelope envelope,
                               final AMQP.BasicProperties properties,
                               final byte[] body) throws IOException {
        executeUnlessShuttingDown(
        new Runnable() {
            public void run() {
                try {
                    delegate.handleDelivery(consumerTag,
                            envelope,
                            properties,
                            body);
                } catch (Throwable ex) {
                    connection.getExceptionHandler().handleConsumerException(	<----- this one calls code below
                            channel,
                            ex,
                            delegate,
                            consumerTag,
                            "handleDelivery");
                }
            }
        });
    }



//StrictExceptionHandler.java
public void handleConsumerException(Channel channel, Throwable exception,
                                        Consumer consumer, String consumerTag,
                                        String methodName)
    {
        handleChannelKiller(channel, exception, "Consumer " + consumer	<--------------- this one calls code below
                                                        + " (" + consumerTag + ")"
                                                        + " method " + methodName
                                                        + " for channel " + channel);
    }

protected void handleChannelKiller(Channel channel, Throwable exception, String what) {
        System.err.println(this.getClass().getName() + ": " + what + " threw an exception for channel "
                + channel + ":");
        exception.printStackTrace();
        try {
            channel.close(AMQP.REPLY_SUCCESS, "Closed due to exception from " + what);	<---- this one calls code below
        } catch (AlreadyClosedException ace) {
        } catch (TimeoutException ace) {
        } catch (IOException ioe) {
            System.err.println("Failure during close of channel " + channel + " after " + exception
                    + ":");
            ioe.printStackTrace();
            channel.getConnection().abort(AMQP.INTERNAL_ERROR, "Internal error closing channel for " + what);
        }
    }



//ChannelN.java
public void close(int closeCode, String closeMessage)
        throws IOException, TimeoutException {
        close(closeCode, closeMessage, true, null, false); <---this one calls code below
    }



//ChannelN.java
protected void close(int closeCode,
                      String closeMessage,
                      boolean initiatedByApplication,
                      Throwable cause,
                      boolean abort)	<--- abort is passed 0
        throws IOException, TimeoutException {
        Channel.Close reason = new Channel.Close(closeCode, closeMessage, 0, 0);
        ShutdownSignalException signal = new ShutdownSignalException(false,
                                                                     initiatedByApplication,
                                                                     reason,
                                                                     this);
        if (cause != null) {
            signal.initCause(cause);
        }

        BlockingRpcContinuation<AMQCommand> k = new BlockingRpcContinuation<AMQCommand>(){
@Override
public AMQCommand transformReply(AMQCommand command) {
                ChannelN.this.finishProcessShutdownSignal();
                return command;
            }};
        boolean notify = false;
        try {
            synchronized (_channelMutex) {
                startProcessShutdownSignal(signal, !initiatedByApplication, true); <--- this one throws exception (in AMQChannel.java) : new AlreadyClosedException("channel is already closed due to clean channel shutdown...")
                quiescingRpc(reason, k);
            }
            notify = true;
            k.getReply(10000);
        } catch (TimeoutException ise) {
            if (!abort)
                throw ise;
        } catch (ShutdownSignalException sse) {
            if (!abort)
                throw sse; <--- this one is called since abort = 0 and sse is catched
        } catch (IOException ioe) {
            if (!abort)
                throw ioe;
        } finally {
            if (abort || notify) { <---- abort = 0 AND notify = false (never released channel)
                releaseChannel();	//I GUESS THIS IS NEVER CALLED AND CHANNEL IS NOT RELEASED?
                notifyListeners();
            }
        }
```

I have full trace if you need more details.

**Comment by michaelklishin** [comment]
When a `basic.cancel` arrives for a consumer the client does not know, it should be logged as a warning and ignored. Throwing an exception is pretty extreme and indeed as we can see here, confusing. If @acogoluegnes agrees we will file a Java client issue. It should be a pretty easy fix ;)

**Comment by michaelklishin** [comment]
By the way, an "unknown consumer" condition isn't necessarily an indication of an issue anywhere. Sometimes there's a natural race condition between consumer management on the server and client ends.

**Comment by acogoluegnes** [comment]
@michaelklishin Yes, logging a warning should be enough in case of unknown consumer on a `basic.cancel`.

**Comment by garyrussell** [comment]
We should also catch exceptions other than `TimeoutException` there.
