### ISSUE TITLE
ConcurrentModificationException when two threads execute a method annotated with @Publisher

### ISSUE THREAD

**Issue by Cameronjmayfield** [spring-projects/spring-integration#2699]
## Bug report

Started when we upgraded to Spring Integration 5.x. Specifically 5.1.1. Example stacktrace:

```
 java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134) ~[na:na]
	at org.springframework.integration.aop.MethodAnnotationPublisherMetadataSource.getExpressionsForHeaders(MethodAnnotationPublisherMetadataSource.java:142) ~[spring-integration-core-5.1.1.RELEASE.jar!/:5.1.1.RELEASE]
	at org.springframework.integration.aop.MessagePublishingInterceptor.evaluateHeaders(MessagePublishingInterceptor.java:195) ~[spring-integration-core-5.1.1.RELEASE.jar!/:5.1.1.RELEASE]
	at org.springframework.integration.aop.MessagePublishingInterceptor.publishMessage(MessagePublishingInterceptor.java:162) ~[spring-integration-core-5.1.1.RELEASE.jar!/:5.1.1.RELEASE]
	at org.springframework.integration.aop.MessagePublishingInterceptor.invoke(MessagePublishingInterceptor.java:144) ~[spring-integration-core-5.1.1.RELEASE.jar!/:5.1.1.RELEASE]
```

Looks like it was introduced with this optimization: https://github.com/spring-projects/spring-integration/commit/b1a3ca764c73e5da4bf10eb4b6be1116375ac227

This causes issues for our application on startup. Thoughts on using a `ConcurrentHashMap` instead of a `HashMap`?

**Comment by artembilan** [comment]
@Cameronjmayfield ,

As you see we confirm that this is a problem.
Dare to contribute the fix: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc?

Thank you anyway!

**Comment by Cameronjmayfield** [comment]
@artembilan Here is a pull request: https://github.com/spring-projects/spring-integration/pull/2700
