### ISSUE TITLE
ClassCastException from PollSkipAdvice

### ISSUE THREAD

**Issue by cdombroski** [spring-projects/spring-integration#2714]
**Affects Version(s):** 5.1.2

---

When using a PollSkipAdvice that is set to skipPolls, it causes a ClassCastException in AbstractPollingEndpoint. This is caused by the `return Boolean.FALSE;` on line 56 when the AbstractPollingEndpoint expects a Message or null. 

> 2019-01-24 09:08:09.814 ERROR 8732 --- [ask-scheduler-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessagingException: nested exception is java.lang.ClassCastException: java.lang.Boolean cannot be cast to org.springframework.messaging.Message
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:343)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$null$1(AbstractPollingEndpoint.java:277)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$2(AbstractPollingEndpoint.java:274)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to org.springframework.messaging.Message
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:329)
	... 15 more

**Comment by garyrussell** [comment]
Thanks - strange that nobody reported this in 5 years - I guess people aren't using it (or are using a smart poller, which really superseded this functionality).

**Comment by cdombroski** [comment]
It looks like a change in [AbstractPollingEndpoint](https://github.com/spring-projects/spring-integration/commit/27353ed3933925e69dc7b9394392e22f07b3f18e#diff-0a70ed47bf7fc1556df5d76b2bd0ce5c) occurred about 4 months ago might have introduced this. 

If you don't mind, could you point me to the documentation for the smart polling you mentioned? I'm using this to only poll a database when the process has leadership.

**Comment by garyrussell** [comment]
Ah - ok; thanks; yes, it's a regression.

[See "Smart" Polling](https://docs.spring.io/spring-integration/reference/html/messaging-channels-section.html#_literal_smart_literal_polling).

>Version 4.2 introduced the AbstractMessageSourceAdvice. Any Advice objects in the advice-chain that subclass this class are applied only to the receive operation. Such classes implement the following methods:

> - `beforeReceive(MessageSource<?> source)` This method is called before the `MessageSource.receive()` method. It lets you examine and reconfigure the source. Returning false cancels this poll (similar to the `PollSkipAdvice` mentioned earlier).

**Comment by cdombroski** [comment]
So, it looks like there's nothing out of the box to provide the functionality of PollSkipAdvice as a AbstractMessageSourceAdvice. It wouldn't take much to refactor the current class to do so, is this something that should/will be done in the future?

**Comment by garyrussell** [comment]
Good point; yes, we should do that.
