### ISSUE TITLE
NullPointer on error message being sent to errorChannel

### ISSUE THREAD

**Issue by ADeane6** [spring-projects/spring-integration#2897]
**Affects Version(s):** Spring-integration-file 5.1.3

## Bug Report
---

When the inbound file synchroniser throws an error during the transfer to local it creates a messaging exception without a failed message, this then causes NullPointerException when that message is attempted to be sent to the error channel via the error handler.

Stacktrace
```
org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'errorChannel'; nested exception is java.lang.NullPointerException
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInDeliveryExceptionIfNecessary(IntegrationUtils.java:166)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:483)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.channel.MessagePublishingErrorHandler.handleError(MessagePublishingErrorHandler.java:95)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:60)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$2(AbstractPollingEndpoint.java:274)
	at net.javacrumbs.shedlock.core.DefaultLockManager.executeWithLock(DefaultLockManager.java:49)
	at net.javacrumbs.shedlock.core.LockableRunnable.run(LockableRunnable.java:35)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.springframework.messaging.support.MessageHeaderAccessor.getMutableAccessor(MessageHeaderAccessor.java:619)
	at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.mutableHeaderAccessor(TracingChannelInterceptor.java:389)
	at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.preSend(TracingChannelInterceptor.java:170)
	at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:608)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:443)
	... 21 common frames omitted
11:40:44.380 ERROR [---,,,] [scheduling-1] ERROR o.s.i.c.MessagePublishingErrorHandler – failure occurred in messaging task
org.springframework.messaging.MessagingException: Problem occurred while synchronizing 'XXXXXXXXX' to local directory; nested exception is org.springframework.messaging.MessagingException: Failed to execute on session; nested exception is org.springframework.integration.util.PoolItemNotAvailableException: Failed to obtain pooled item
	at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizer.synchronizeToLocalDirectory(AbstractInboundFileSynchronizer.java:315)
	at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizingMessageSource.doReceive(AbstractInboundFileSynchronizingMessageSource.java:258)
	at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizingMessageSource.doReceive(AbstractInboundFileSynchronizingMessageSource.java:64)
	at org.springframework.integration.endpoint.AbstractFetchLimitingMessageSource.doReceive(AbstractFetchLimitingMessageSource.java:45)
	at org.springframework.integration.endpoint.AbstractMessageSource.receive(AbstractMessageSource.java:160)
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.receiveMessage(SourcePollingChannelAdapter.java:250)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:360)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:329)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$null$1(AbstractPollingEndpoint.java:277)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$2(AbstractPollingEndpoint.java:274)
	at net.javacrumbs.shedlock.core.DefaultLockManager.executeWithLock(DefaultLockManager.java:49)
	at net.javacrumbs.shedlock.core.LockableRunnable.run(LockableRunnable.java:35)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This is the configuration of the channel and ftp factory

```
@Bean
    public SessionFactory<FTPFile> ftpSessionFactory() {
        DefaultFtpSessionFactory sf = new DefaultFtpSessionFactory();
        sf.setHost(server);
        sf.setPort(port);
        sf.setUsername(user);
        sf.setPassword(password);
        return new CachingSessionFactory<>(sf);
    }

    @Bean
    public FtpInboundFileSynchronizer ftpInboundFileSynchronizer(DataSource dataSource) {
        FtpInboundFileSynchronizer fileSynchronizer = new FtpInboundFileSynchronizer(ftpSessionFactory());
        fileSynchronizer.setDeleteRemoteFiles(ftpDeleteRemoteFile);
        fileSynchronizer.setRemoteDirectory(ftpFileLocation);
        JdbcMetadataStore metadataStore = new JdbcMetadataStore(dataSource);
        metadataStore.setTablePrefix(ftpMetadataPrefix);
        metadataStore.afterPropertiesSet();
        fileSynchronizer.setFilter(new FtpPersistentAcceptOnceFileListFilter(metadataStore, ""));
        return fileSynchronizer;
    }

    @Bean("InboundFtpChannel")
    @InboundChannelAdapter(channel = "ftpChannel", poller = @Poller(fixedDelay = "10000"))
    public MessageSource<File> ftpMessageSource(FtpInboundFileSynchronizer ftpInboundFileSynchronizer) {
        FtpInboundFileSynchronizingMessageSource source =
                new FtpInboundFileSynchronizingMessageSource(ftpInboundFileSynchronizer);
        source.setLocalDirectory(new File(ftpFileDestination));
        source.setAutoCreateLocalDirectory(true);
        source.setLocalFilter(new AcceptOnceFileListFilter<>());
        source.setMaxFetchSize(-1);
        return source;
    }
```

**Comment by garyrussell** [comment]
Looks like a bug in Sleuth to me, not checking for a `null` `failedMessage`.

>`	at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.mutableHeaderAccessor(TracingChannelInterceptor.java:389)`

`MessagingException` clearly supports `null`...

```java
public class MessagingException extends NestedRuntimeException {

	@Nullable
	private final Message<?> failedMessage;


	public MessagingException(Message<?> message) {
		super(null, null);
		this.failedMessage = message;
	}

	public MessagingException(String description) {
		super(description);
		this.failedMessage = null;
	}
...
```

**Comment by artembilan** [comment]
I think it's time to move this issue exactly into the https://github.com/spring-cloud/spring-cloud-sleuth.

Unfortunately it looks like I don't have permissions to do that operation...

**Comment by garyrussell** [comment]
Me neither.

/cc: @marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
I don't know how to do it so I just referenced it here https://github.com/spring-cloud/spring-cloud-sleuth/issues/1335

**Comment by artembilan** [comment]
Closed as moved to the appropriate project into the issue: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1335

**Comment by spencergibb** [comment]
I think you can only move issues in the same org
