### ISSUE TITLE
Inconsistency in schema locations in spring integration 4.3.20

### ISSUE THREAD

**Issue by dmitrysm2000** [spring-projects/spring-integration#2987]
All the Spring integration xsds (-jms, -jmx, -file) import the core xsd by using https in schemaLocation while in the spring-integration-core\spring.schemas it is defined with http.
In runtime this causes the system to look for the https://www.springframework.org/schema/integration/spring-integration-4.3.xsd on the web.

Looks the same as https://github.com/spring-projects/spring-framework/issues/22739

**Comment by artembilan** [comment]
I'm afraid that we are here fully based on what Spring Core provides for us and since my colleagues in the mentioned Spring issue suggest to fix an IDE, we don't have any freedom to change anything here in this project.

I'm just not sure why you say *in rutime*, just because Spring really resolves all the HTTPS schemas to HTTP at runtime. You might have a problem in the IDE during development, but that's fully not related to runtime.
Also be sure that you use all the compatible Spring versions. Would be better to start from Spring Boot on top of that which is going to manage dependencies properly for you.

I will wait for your feedback, but keep in mind that we are going to close this as `Won't Fix`. At least until some general solution will be dictated for us from the core framework.

**Comment by dmitrysm2000** [comment]
In my case it is not an IDE problem.
I say runtime because it happens in the deployed application running under Tomcat.
When I define an external trustStore (for the application purposes) using the -Djavax.net.ssl.trustStrore, the system logs the following errors/warnings:
1. 

> 2019.07.15 09:31:47.516 WARN  [localhost-startStop-1] XmlBeanDefinitionReader - Ignored XML validation warning
org.xml.sax.SAXParseException; systemId: http://www.springframework.org/schema/integration/jmx/spring-integration-jmx.xsd; lineNumber: 11; columnNumber: 102; schema_reference.4: Failed to read schema document 'https://www.springframework.org/schema/integration/spring-integration-4.3.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
...
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

which means it tries to download the xsd by https, but cannot validate the certificate.

And after that, spring loading fails
2.  

> org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location 
[classpath:...]
Offending resource: URL [jar:file:....xml]; nested exception is org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 307 in XML document from class path resource 
[...] is invalid; nested exception is org.xml.sax.SAXParseException; systemId: http://www.springframework.org/schema/integration/jmx/spring-integration-jmx.xsd; lineNumber: 307; columnNumber: 73; src-resolve: 
Cannot resolve the name 'integration:smartLifeCycleAttributeGroup' to a(n) 'attribute group' component.
	at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:70)
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:118)
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:103)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.importBeanDefinitionResource(DefaultBeanDefinitionDocumentReader.java:233)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseDefaultElement(DefaultBeanDefinitionDocumentReader.java:184)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:169)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:142)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:94)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:508)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:392)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	...
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:122)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	...
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:744)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:624)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1833)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 307 in XML document from class path resource [...] is invalid; nested exception is org.xml.sax.SAXParseException; systemId: http://www.springframework.org/schema/integration/jmx/spring-integration-jmx.xsd; lineNumber: 307; columnNumber: 73; src-resolve: Cannot resolve the name 'integration:smartLifeCycleAttributeGroup' to a(n) 'attribute group' component.
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:399)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.importBeanDefinitionResource(DefaultBeanDefinitionDocumentReader.java:227)
	... 32 more
Caused by: org.xml.sax.SAXParseException; systemId: http://www.springframework.org/schema/integration/jmx/spring-integration-jmx.xsd; lineNumber: 307; columnNumber: 73; src-resolve: Cannot resolve the name 'integration:smartLifeCycleAttributeGroup' to a(n) 'attribute group' component.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4154)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4137)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1684)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAttributeGroupTraverser.traverseLocal(XSDAttributeGroupTraverser.java:80)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAbstractTraverser.traverseAttrsAndAttrGrps(XSDAbstractTraverser.java:643)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.processComplexContent(XSDComplexTypeTraverser.java:1123)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexContent(XSDComplexTypeTraverser.java:836)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexTypeDecl(XSDComplexTypeTraverser.java:315)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseGlobal(XSDComplexTypeTraverser.java:191)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseGlobalDecl(XSDHandler.java:1894)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1782)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexContent(XSDComplexTypeTraverser.java:768)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexTypeDecl(XSDComplexTypeTraverser.java:315)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseLocal(XSDComplexTypeTraverser.java:164)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseNamedElement(XSDElementTraverser.java:392)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseGlobal(XSDElementTraverser.java:242)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseSchemas(XSDHandler.java:1439)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:635)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:610)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2447)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1768)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:761)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:76)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:429)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391)
	... 37 more



When the system is started without the javax.net.ssl.trustStrore definition it works.
When we added the following definitions in our own spring.schemas file - it fixed the issue:

> https\://www.springframework.org/schema/integration/spring-integration-4.3.xsd=org/springframework/integration/config/spring-integration-4.3.xsd
https\://www.springframework.org/schema/integration/spring-integration.xsd=org/springframework/integration/config/spring-integration-4.3.xsd


So it looks like Spring fails to resolve the HTTPS prefixed locations using the xsd files from the jars

**Comment by dmitrysm2000** [comment]
we use spring-integration 4.3.20 (all the jars are of the same version) and spring 4.3.22 (the same)

**Comment by artembilan** [comment]
Can you try it with the Spring Core `4.3.24.RELEASE` ?
The issue you are mentioning in Spring Framework talks about `4.3.23` instead of your mentioned `4.3.22` though...

**Comment by dmitrysm2000** [comment]
I don't have an issue with Spring Core, I just mentioned it because it is similar to the one I have with Spring Integration.

**Comment by artembilan** [comment]
OK. I got you.
Looks like Spring Core provides HTTPS XSD locations in their `spring.schemas`, but we don't here in Spring Integration.
For example:
```
http\://www.springframework.org/schema/beans/spring-beans-4.3.xsd=org/springframework/beans/factory/xml/spring-beans.xsd
https\://www.springframework.org/schema/beans/spring-beans-4.3.xsd=org/springframework/beans/factory/xml/spring-beans.xsd
```
in `spring-beans`
VS just
```
http\://www.springframework.org/schema/integration/spring-integration-4.3.xsd=org/springframework/integration/config/spring-integration.xsd
```
in `spring-integrastion-core`.

Correct me if I'm wrong, that just need to add those HTTPS entries into our `spring.schemas` files every module in our project?

Thanks

**Comment by dmitrysm2000** [comment]
I think so

**Comment by artembilan** [comment]
Thanks for confirmation, @dmitrysm2000 !

Any chance that you can provide a contribution on  the matter?
We are out for Spring One Tour today, so can't fix it quickly.

Thanks for understanding!

@garyrussell ,

I've noticed that Spring Framework since version 5.0 doesn't manage several versions for XSD. They have only one "versionless" file in the `/config` directory and their  all `spring.schemas` entries point to the same file, even if they come with version. I know we have a check in the framework for schema reference version fully compatible with the one in the jar. And looks like they even stopped to publish version-based schemas, e.g.: http://www.springframework.org/schema/aop/

So, any thoughts about ours?

**Comment by garyrussell** [comment]
>I've noticed that Spring Framework since version 5.0 doesn't manage several versions for XSD. 

>So, any thoughts about ours?

Interesting.

However, I rather like the version checking; without it, people can have mismatched integration modules (core, http, file) etc. This check detects the condition and fails fast.

Without that check we can end up with weird errors.

In fact, I think we should strengthen the check, in the case that they use the version-less schema (compare it to the versioned one and, if different, fail fast).

Of course, most new devs use Boot so the versions are managed, but we should still consider it.

I do agree that it looks like we need to add the `https:` scheme to the `spring-schemas` files.

**Comment by artembilan** [comment]
Well, I'm going to fix an HTTPS issue, leaving all other concerns for the future consideration. But my opinion that in the modern world where people less and less use XML configuration, we should just don't worry about strict version matching and just do whatever is done in Spring Framework: provide only versionless XSD and map all the version-based into this last one. The mismatched integration modules bring much more byte code incompatibility issues, than just wrong XSD references...

**Comment by artembilan** [comment]
OK. I have modified as much as I could recall throughout all of our projects.
