### ISSUE TITLE
IntegrationManagementConfigurer registorComponentGuage issue using graphite metric registry

### ISSUE THREAD

**Issue by ekdxhrl0096** [spring-projects/spring-integration#3015]
*spring integration version*
- spring-integration-core-5.1.6.RELEASE

I experienced stacktrace every time I quit the spring application. 
It seems that when trying to close a non-Singleton value, an error occurs. 
How can I fix it?

*application.yml*
```
management:
  metrics:
    export:
      graphite:
        host: 127.0.0.1
        enabled: true
        port: 2003
        step: 20s
        protocol: plaintext
        prefix: "prefix"
```

*Stacktrace*
```
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'nullChannel': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:606)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:594)
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1226)
	at org.springframework.integration.config.IntegrationManagementConfigurer.lambda$registerComponentGauges$1(IntegrationManagementConfigurer.java:407)
	at io.micrometer.core.instrument.dropwizard.DropwizardMeterRegistry.lambda$newGauge$0(DropwizardMeterRegistry.java:79)
	at com.codahale.metrics.graphite.GraphiteReporter.reportGauge(GraphiteReporter.java:368)
	at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:268)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:237)
	at io.micrometer.graphite.GraphiteMeterRegistry.close(GraphiteMeterRegistry.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:339)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:273)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1036)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1029)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1057)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1026)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:945)
```

Has anyone experienced this experience?

**Comment by garyrussell** [comment]
>	at io.micrometer.core.instrument.dropwizard.DropwizardMeterRegistry.lambda$newGauge$0(DropwizardMeterRegistry.java:79)
	at com.codahale.metrics.graphite.GraphiteReporter.reportGauge(GraphiteReporter.java:368)
	at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:268)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:237)
	at io.micrometer.graphite.GraphiteMeterRegistry.close(GraphiteMeterRegistry.java:92)

It's either a problem in micrometer or in graphite - it's trying to create a new gauge during shutdown. 

This has nothing to do with Spring Integration; I suggest you open an issue against micrometer and they can determine if it's a micrometer or graphite issue.

**Comment by csabakos** [comment]
@garyrussell https://github.com/micrometer-metrics/micrometer/issues/1936 is the relevant micrometer issue and the comments indicate that meter creation isn't allowed in a destroy method.

Should we consider reopening this ticket and avoiding meter creation during destruction?

**Comment by artembilan** [comment]
Probably it's better to report the issue against Graphite.
See that stack trace:
```
at io.micrometer.core.instrument.dropwizard.DropwizardMeterRegistry.lambda$newGauge$0(DropwizardMeterRegistry.java:79)
at com.codahale.metrics.graphite.GraphiteReporter.reportGauge(GraphiteReporter.java:368)
at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:268)
at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:237)
at io.micrometer.graphite.GraphiteMeterRegistry.close(GraphiteMeterRegistry.java:92)
```

The Micormeter calls `close()` and that one delegates to the `report()` of Grahite which in turns tries to report a gauge with our callback:
```
this.metricsCaptor.gaugeBuilder("spring.integration.channels", this,
				(c) -> this.applicationContext.getBeansOfType(MessageChannel.class).size())
				.description("The number of message channels")
				.build();
```
