### ISSUE TITLE
Hung Build

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#3061]
```
Found one Java-level deadlock:
=============================
"SpringContextShutdownHook":
  waiting to lock monitor 0x00007fc021fbba98 (object 0x00000007b5dcfe58, a org.h2.engine.Session),
  which is held by "SpringContextShutdownHook"
"SpringContextShutdownHook":
  waiting to lock monitor 0x00007fc021fbd4b8 (object 0x00000007b5f19690, a org.h2.engine.Session),
  which is held by "SpringContextShutdownHook"

Java stack information for the threads listed above:
===================================================
"SpringContextShutdownHook":
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:97)
	- waiting to lock <0x00000007b5dcfe58> (a org.h2.engine.Session)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	- locked <0x00000007b5f19690> (a org.h2.engine.Session)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	- locked <0x00000007b5f19690> (a org.h2.engine.Session)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.springframework.jdbc.datasource.embedded.AbstractEmbeddedDatabaseConfigurer.shutdown(AbstractEmbeddedDatabaseConfigurer.java:48)
	at org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory.shutdownDatabase(EmbeddedDatabaseFactory.java:229)
	at org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactoryBean.destroy(EmbeddedDatabaseFactoryBean.java:90)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:258)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1071)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1064)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1060)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1029)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948)
	- locked <0x00000007a0d7b6e8> (a java.lang.Object)
"SpringContextShutdownHook":
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:97)
	- waiting to lock <0x00000007b5f19690> (a org.h2.engine.Session)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	- locked <0x00000007b5dcfe58> (a org.h2.engine.Session)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	- locked <0x00000007b5dcfe58> (a org.h2.engine.Session)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.springframework.jdbc.datasource.embedded.AbstractEmbeddedDatabaseConfigurer.shutdown(AbstractEmbeddedDatabaseConfigurer.java:48)
	at org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory.shutdownDatabase(EmbeddedDatabaseFactory.java:229)
	at org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactoryBean.destroy(EmbeddedDatabaseFactoryBean.java:90)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:258)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1071)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1064)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1060)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1029)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948)
	- locked <0x00000007a053a060> (a java.lang.Object)

Found 1 deadlock.
```

**Comment by artembilan** [comment]
According that stack trace it looks like the story is only about the cases where we have a `<jdbc:embedded-database id="dataSource" type="H2">` definition.

**Comment by garyrussell** [comment]
I still have the full thread dump; I'll find out which threads own the locks.

**Comment by garyrussell** [comment]
Oh - it's a mutual deadlock between those two threads.

**Comment by artembilan** [comment]
A couple tests with an embedded DB don't have a `@DirtiesContext` on them to close a DB in the end of test suite.
This way when context cache cleanup comes to the scene, it is a fact that several cleaners try to destroy the same in-memory DB instance cause the mentioned dead lock.
