### ISSUE TITLE
GatewayProxyFactoryBean should not proxy default methods in the interface

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration#3118]
```
@Autowired
	private Function<Object, Message<?>> functionGateay;

	@Test
	void testHeadersFromFunctionGateway() {
		Object payload = this.functionGateay
				.andThen(message -> {
					assertThat(message.getHeaders()).containsKeys("gatewayMethod", "gatewayArgs");
					return message.getPayload();
				})
				.apply("testPayload");

		assertThat(payload).isEqualTo("testPayload");
	}
```
So, we definitely would like to use `default` methods in the interface as well, but it turns out they are proxied as well leading to unexpected behavior when we don't call a real `default` method, but send a message downstream instead.

On the other hand it is not so easy to exclude those methods from proxing and their normal logic:
```
			NameMatchMethodPointcutAdvisor gatewayAdvisor = new NameMatchMethodPointcutAdvisor(this);

			Method[] methods =
					ReflectionUtils.getUniqueDeclaredMethods(this.serviceInterface,
							method -> Modifier.isAbstract(method.getModifiers()));
			for (Method method : methods) {
				MethodInvocationGateway gateway = createGatewayForMethod(method);
				this.gatewayMap.put(method, gateway);
				gatewayAdvisor.addMethodName(method.getName());
			}

			ProxyFactory gatewayProxyFactory =
					new ProxyFactory(this.serviceInterface, AdvisedSupport.EMPTY_TARGET_SOURCE);
			gatewayProxyFactory.addAdvisor(gatewayAdvisor);
			this.serviceProxy = gatewayProxyFactory.getProxy(this.beanClassLoader);
```
When a `default` method in called we have a `target` for reflection as `null` leading to NPE.

Spring Data has something like this `DefaultMethodInvokingMethodInterceptor` - need to investigate what is the beast.

**Comment by artembilan** [comment]
The `DefaultMethodInvokingMethodInterceptor` doesn't work for `Function.class` proxing use-cases:
```
Caused by: java.lang.IllegalArgumentException: illegal lookupClass: interface java.util.function.Function
	at java.lang.invoke.MethodHandleStatics.newIllegalArgumentException(MethodHandleStatics.java:139)
	at java.lang.invoke.MethodHandles$Lookup.checkUnprivilegedlookupClass(MethodHandles.java:686)
	at java.lang.invoke.MethodHandles$Lookup.<init>(MethodHandles.java:604)
```

The code in Java 8 is like this:
```
   // For caller-sensitive MethodHandles.lookup()
            // disallow lookup more restricted packages
            if (allowedModes == ALL_MODES && lookupClass.getClassLoader() == null) {
                if (name.startsWith("java.") ||
                        (name.startsWith("sun.")
                                && !name.startsWith("sun.invoke.")
                                && !name.equals("sun.reflect.ReflectionFactory"))) {
                    throw newIllegalArgumentException("illegal lookupClass: " + lookupClass);
                }
            }
```

**Comment by artembilan** [comment]
Well, we definitely have to fix at least proxiing extra non-abstract methods. Otherwise Integration Graph becomes a bit awkward:
```
{
    "nodeId" : 28,
    "stats" : null,
    "componentType" : "gateway",
    "integrationPatternType" : "gateway",
    "integrationPatternCategory" : "messaging_endpoint",
    "properties" : { },
    "output" : "controlBusFlow.channel#0",
    "errors" : null,
    "name" : "controlBusFlow.gateway.andThen(java.util.function.Function)"
  }, {
    "nodeId" : 29,
    "stats" : null,
    "componentType" : "gateway",
    "integrationPatternType" : "gateway",
    "integrationPatternCategory" : "messaging_endpoint",
    "properties" : { },
    "output" : "controlBusFlow.channel#0",
    "errors" : null,
    "name" : "controlBusFlow.gateway.apply(java.lang.Object)"
  }, {
    "nodeId" : 30,
    "stats" : null,
    "componentType" : "gateway",
    "integrationPatternType" : "gateway",
    "integrationPatternCategory" : "messaging_endpoint",
    "properties" : { },
    "output" : "controlBusFlow.channel#0",
    "errors" : null,
    "name" : "controlBusFlow.gateway.compose(java.util.function.Function)"
  }, {
    "nodeId" : 31,
    "stats" : null,
    "componentType" : "gateway",
    "integrationPatternType" : "gateway",
    "integrationPatternCategory" : "messaging_endpoint",
    "properties" : { },
    "output" : "controlBusFlow.channel#0",
    "errors" : null,
    "name" : "controlBusFlow.gateway.lambda$compose$0(java.util.function.Function,java.lang.Object)"
  }, {
    "nodeId" : 32,
    "stats" : null,
    "componentType" : "gateway",
    "integrationPatternType" : "gateway",
    "integrationPatternCategory" : "messaging_endpoint",
    "properties" : { },
    "output" : "controlBusFlow.channel#0",
    "errors" : null,
    "name" : "controlBusFlow.gateway.lambda$andThen$1(java.util.function.Function,java.lang.Object)"
  }, {
    "nodeId" : 33,
    "stats" : null,
    "componentType" : "gateway",
    "integrationPatternType" : "gateway",
    "integrationPatternCategory" : "messaging_endpoint",
    "properties" : { },
    "output" : "controlBusFlow.channel#0",
    "errors" : null,
    "name" : "controlBusFlow.gateway.identity()"
  }, {
    "nodeId" : 34,
    "stats" : null,
    "componentType" : "gateway",
    "integrationPatternType" : "gateway",
    "integrationPatternCategory" : "messaging_endpoint",
    "properties" : { },
    "output" : "controlBusFlow.channel#0",
    "errors" : null,
    "name" : "controlBusFlow.gateway.lambda$identity$2(java.lang.Object)"
  }
```

**Comment by artembilan** [comment]
Hm. GitHub somehow didn't close the issue automatically with the commit.
So, fixed via: https://github.com/spring-projects/spring-integration/commit/4134fc76e5b23a5372c1e0e8692939a899d8acf0
