### ISSUE TITLE
MQ Exception when running stop() on StandardIntegrationFlow

### ISSUE THREAD

**Issue by lafual** [spring-projects/spring-integration#3301]
When running `.stop()` for the following code;

```
public StandardIntegrationFlow queueReader(ConnectionFactory connectionFactory, String queueName) {
	return IntegrationFlows.from(
		Jms
			.inboundAdapter(connectionFactory)
			.destination(queueName)
		, e -> e.poller(
			Pollers
				.fixedDelay(1000)
				.errorChannel(CHANNEL_ERROR)
				.maxMessagesPerPoll(1)
		)
	)
	.channel(CHANNEL_BACKUP)
	.get();
}
```
I get an error and the flow is redirected to CHANNEL_ERROR as expected. In the error handler `payload.getFailedMessage()` is `null` which is (kind-of) expected as the queue was empty. Restarting with `.start()` is working OK and messages are processed.

This is possibly a JMS or IBM MQ issue, but is Spring Integration properly interacting with JMS or MQ? (I understand that this may not be an S.I. issue, but it would help to know how S.I. is stopping in order to pass on the issue to JMS or IBM).

Possibly, the `stop()` is interrupting the lower level `JMSTemplate.doReceive()` thus causing the exception. Maybe, the `stop()` should just cause the next poll to ignore doReceive(). I know that from working with MQ classes that a `get` can (depending on the API call and/or MQ GET options) wait for a period before returning (similar to a Java `BlockingQueue`) and maybe it is this that is blocking. When I interrupt (the MQ class) I _can_ get 2195.

The trace is as follows;
```
Caused by: org.springframework.jms.UncategorizedJmsException: Uncategorized exception occurred during JMS processing; nested exception is com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2002: Failed to get a message from destination 'QA.UAT.GLOBIT.TO.DRS.OPTIONS'.
IBM MQ classes for JMS attempted to perform an MQGET; however IBM MQ reported an error.
Use the linked exception to determine the cause of this error.; nested exception is com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2195' ('MQRC_UNEXPECTED_ERROR').
	at org.springframework.jms.support.JmsUtils.convertJmsAccessException(JmsUtils.java:311)
	at org.springframework.jms.support.JmsAccessor.convertJmsAccessException(JmsAccessor.java:185)
	at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:507)
	at org.springframework.jms.core.JmsTemplate.receiveSelected(JmsTemplate.java:747)
	at org.springframework.integration.jms.JmsDestinationPollingSource.doReceiveJmsMessage(JmsDestinationPollingSource.java:157)
	at org.springframework.integration.jms.JmsDestinationPollingSource.doReceive(JmsDestinationPollingSource.java:126)
	at org.springframework.integration.endpoint.AbstractMessageSource.receive(AbstractMessageSource.java:167)
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.receiveMessage(SourcePollingChannelAdapter.java:250)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:359)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:328)
	... 14 more
Caused by: com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2002: Failed to get a message from destination 'QA.UAT.GLOBIT.TO.DRS.OPTIONS'.
IBM MQ classes for JMS attempted to perform an MQGET; however IBM MQ reported an error.
Use the linked exception to determine the cause of this error.
	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
	at com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:222)
	at com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:156)
	at com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1858)
	at com.ibm.msg.client.wmq.internal.WMQSyncConsumerShadow.receiveInternal(WMQSyncConsumerShadow.java:228)
	at com.ibm.msg.client.wmq.internal.WMQConsumerShadow.receive(WMQConsumerShadow.java:1461)
	at com.ibm.msg.client.wmq.internal.WMQMessageConsumer.receive(WMQMessageConsumer.java:674)
	at com.ibm.msg.client.jms.internal.JmsMessageConsumerImpl.receiveInboundMessage(JmsMessageConsumerImpl.java:1051)
	at com.ibm.msg.client.jms.internal.JmsMessageConsumerImpl.receive(JmsMessageConsumerImpl.java:667)
	at com.ibm.mq.jms.MQMessageConsumer.receive(MQMessageConsumer.java:209)
	at org.springframework.jms.support.destination.JmsDestinationAccessor.receiveFromConsumer(JmsDestinationAccessor.java:132)
	at org.springframework.jms.core.JmsTemplate.doReceive(JmsTemplate.java:788)
	at org.springframework.jms.core.JmsTemplate.doReceive(JmsTemplate.java:765)
	at org.springframework.jms.core.JmsTemplate.lambda$receiveSelected$9(JmsTemplate.java:749)
	at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:504)
	... 21 more
Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2195' ('MQRC_UNEXPECTED_ERROR').
	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
	... 35 more
```

**Comment by artembilan** [comment]
Yes, we definitely interrupt a polling task on `stop()`:
```
	protected void doStop() {
		if (this.runningTask != null) {
			this.runningTask.cancel(true);
		}
		this.runningTask = null;

		if (this.subscription != null) {
			this.subscription.cancel();
		}
	}
```

This is to avoid losing messages which could be pulled from the queue and lost because we would ignore `doReceive()` result.

I would say that ignore such an exception on stop is the best way to go for time being.
It is probably an IBM MQ matter to treat such a thread interrupt properly: we do our best to exist as fast as possible and do not interact with the broker for nothing.

**Comment by lafual** [comment]
Thanks for responding.  I just wanted to clarify that it was by design. For sure you cannot be expected to know how MQ will react. Apart from the noise in the logs SI is working fine :-)

**Comment by artembilan** [comment]
Thanks for confirmation!

Well, technically in the `CHANNEL_ERROR` flow you could just ignore this kind of exceptions. Not sure though if we can have some control over `JMSTemplate.doReceive()` to make a proper assumption about a downstream client exception...

**Comment by lafual** [comment]
@artembilan I did some more investigation. I suspected that there may be an issue with the poller, in that cancelling the poller shouldn't really affect the MQ GET. I assume that the GET should only happen after the poll duration. There I increased the duration from 1000ms to 1 hour and the stop did not yield the Exception. So this does lend support to this theory. However, I always get the error when the poll is 1000ms

**Comment by artembilan** [comment]
Well, you probably need to do like this:
```
Jms
			.inboundAdapter(connectionFactory)
			.destination(queueName)
                        .configureJmsTemplate(template -> template.receiveTimeout(-1))
```

So, no blocking on that GET any more:
```
protected Message receiveFromConsumer(MessageConsumer consumer, long timeout) throws JMSException {
		if (timeout > 0) {
			return consumer.receive(timeout);
		}
		else if (timeout < 0) {
			return consumer.receiveNoWait();
		}
		else {
			return consumer.receive();
		}
	}
```

By default it is `private long receiveTimeout = RECEIVE_TIMEOUT_INDEFINITE_WAIT;`.

**Comment by lafual** [comment]
@artembilan Thanks for giving me a workaround. It does solve the issue. 

However, the behavior is kind-of counter-intuitive to what (in my opinion) polling is. With my non-reactive JDBC/JPA hat on, a poll will not block. The data is there or not. The SQL will not block for `1000L` milliseconds until something arrives. So shouldn't your suggestion be the default activity?

**Comment by artembilan** [comment]
We can't make a mutation in an externally provided reference:
```
public JmsDestinationPollingSource(JmsTemplate jmsTemplate) {
```
But we definitely can provide an IMPORTANT not into a docs: https://docs.spring.io/spring-integration/docs/current/reference/html/jms.html#jms-inbound-channel-adapter

**Comment by artembilan** [comment]
Feel free to contribute such a fix into the `jms.adoc`: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc !

**Comment by shristi-shah** [comment]
@Configuration
@EnableJms
public class Configure  {
    @Bean
    public DefaultJmsListenerContainerFactory jmsListenerContainerFactory(ConnectionFactory connectionFactory) {
        DefaultJmsListenerContainerFactory jmsListenerContainerFactory = new DefaultJmsListenerContainerFactory();

        jmsListenerContainerFactory.setConnectionFactory(connectionFactory);
        jmsListenerContainerFactory.setConcurrency("5-10");

        return jmsListenerContainerFactory;
    }


}

while executing this i am getting error 

uncategorized exception occurred during JMS processing
