### ISSUE TITLE
autoStartup(false) is ignored on Mail.imapInboundAdapter

### ISSUE THREAD

**Issue by jzelenka** [spring-projects/spring-integration#3341]
Hello everyone,
it seems that autoStartup(false) is ignored on Mail.imapInboundAdapter :

```java
    @Bean
    public IntegrationFlow imapMailFlow() {
        return IntegrationFlows
                .from(Mail.imapInboundAdapter("imap://user:pw@host:port/INBOX")
                    e -> e.autoStartup(false)
                            .poller(p -> p.fixedDelay(1000)))
                .channel(MessageChannels.queue("imapChannel"))
                .get();
    }
```

it is still connecting to the IMAP server (and throwing exceptions when not available) :

```
failure occurred while polling for mail; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: host, 143; timeout -1;
  nested exception is:
	java.net.UnknownHostException: host
org.springframework.messaging.MessagingException: failure occurred while polling for mail; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: host, 143; timeout -1;
  nested exception is:
	java.net.UnknownHostException: host
	at org.springframework.integration.mail.MailReceivingMessageSource.doReceive(MailReceivingMessageSource.java:74)
	at org.springframework.integration.endpoint.AbstractMessageSource.receive(AbstractMessageSource.java:184)
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.receiveMessage(SourcePollingChannelAdapter.java:212)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:407)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:376)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$null$3(AbstractPollingEndpoint.java:323)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$4(AbstractPollingEndpoint.java:320)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: host, 143; timeout -1;
  nested exception is:
	java.net.UnknownHostException: host
	at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:740)
	at javax.mail.Service.connect(Service.java:366)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at org.springframework.integration.mail.AbstractMailReceiver.connectStoreIfNecessary(AbstractMailReceiver.java:332)
	at org.springframework.integration.mail.AbstractMailReceiver.openFolder(AbstractMailReceiver.java:339)
	at org.springframework.integration.mail.AbstractMailReceiver.receive(AbstractMailReceiver.java:371)
	at org.springframework.integration.mail.MailReceivingMessageSource.doReceive(MailReceivingMessageSource.java:60)
	... 19 more
Caused by: java.net.UnknownHostException: host
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:359)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
	at com.sun.mail.iap.Protocol.<init>(Protocol.java:134)
	at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:131)
	at com.sun.mail.imap.IMAPStore.newIMAPProtocol(IMAPStore.java:763)
	at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:698)
	... 26 more
```

it works correctly when specified via XML  with `<int-mail:inbound-channel-adapter auto-startup="false"`

**Comment by artembilan** [comment]
I have transferred the issue into https://github.com/spring-projects/spring-integration since the version is an actual.

Would be great if you can provide a simple reproducable sample.

Thanks

**Comment by jzelenka** [comment]
@artembilan I found an issue - on my side. Sorry for false alarm. I am closing it.
