### ISSUE TITLE
Update Paho MQTT client library dependency version to 1.2.3+ because of the keep-alive bug

### ISSUE THREAD

**Issue by Happy-Neko** [spring-projects/spring-integration#3348]
**Current Behavior**
`org.eclipse.paho:org.eclipse.paho.client.mqttv3` dependency versions is 1.2.2.

**Context**
Paho MQTT client version 1.2.2 has nasty bug that can result in ping packet being sent to server every millisecond regardless of the configuration. https://github.com/eclipse/paho.mqtt.java/issues/738

Version 1.2.4 seems to work fine.

**Comment by artembilan** [comment]
Sure! Feel free to raise a Pull Request on the matter: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc.

Be sure that you have an MQTT broker locally on `1883` port to run all our test with your fix.

Thank you!

**Comment by Happy-Neko** [comment]
I can't make unit tests pass on master branch.  `BackToBackAdapterTests.testAddRemoveTopic()` fails with mosquitto 1.6.9 as local broker.

```
ERROR [main] [org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter] - Error connecting or subscribing to []
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:272) ~[?:?]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:?]
	... 1 more
```
All other test passes. A am not sure where to look for the problem.

**Comment by artembilan** [comment]
Let me check it locally with MQTT plugin in RabbitMQ!

**Comment by artembilan** [comment]
Works well. So, probably some Mosquitto incompatibility issue.

Pushing the upgrade...

Thanks for your contribution!
