### ISSUE TITLE
IPV6 Exception

### ISSUE THREAD

**Issue by mgalindor** [spring-projects/spring-integration#3373]
I'm using the Sftp.inboundAdapter and I'm getting the next exception when I configure the SFTPSessionFactory with a host in IPv6

```
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizer.copyFileToLocalDirectory(AbstractInboundFileSynchronizer.java:499)
	at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizer.copyIfNotNull(AbstractInboundFileSynchronizer.java:400)
	at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizer.transferFilesFromRemoteToLocal(AbstractInboundFileSynchronizer.java:386)
	at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizer.lambda$synchronizeToLocalDirectory$0(AbstractInboundFileSynchronizer.java:349)
	at org.springframework.integration.file.remote.RemoteFileTemplate.execute(RemoteFileTemplate.java:439)
```

Reviewing the code I found in AbstractInboundFileSynchronizer
```
String[] hostPort = session.getHostPort().split(":");

.....

String remoteFileMetadata = (new URI(this.protocol(), (String)null, hostPort[0], Integer.parseInt(hostPort[1]), '/' + remoteDirectoryPath, (String)null, remoteFileName)).toString();
```

Probably `String[] hostPort = session.getHostPort().split(":");` can be replaced by 

```
int lio=  hostPort.lastIndexOf(":");
String host = hostPort.substring(0,lio);
String port = hostPort.substring(lio+1);
```

This is my configuration 
```
@Bean
    public IntegrationFlow readFileFlow(
        SessionFactory<LsEntry> sftpSessionFactory, IntegrationFlow moveInputFileFlow,
        IntegrationFlow processFileFlow) {
        return IntegrationFlows.from(Sftp.inboundAdapter(sftpSessionFactory)
                .preserveTimestamp(true)
                .autoCreateLocalDirectory(true)
                .deleteRemoteFiles(true)
                .maxFetchSize(1)
                .remoteDirectory("/input")
                .filter(new SftpPersistentAcceptOnceFileListFilter(new SimpleMetadataStore(), "rotate"))
                .localFilter(new AcceptOnceFileListFilter())
                .regexFilter("^([0-9\\-]+).in$")
                .localDirectory(new File("tmp")),
            e -> e.autoStartup(true)
                .poller(Pollers.fixedDelay(5000)))
            .transform(Files.toStringTransformer())
            .publishSubscribeChannel(pubSub -> pubSub
                .subscribe(moveInputFileFlow)
                .subscribe(processFileFlow))
            .get();
    }


@Bean
    public CachingSessionFactory<LsEntry> sftpSessionFactory() {
        DefaultSftpSessionFactory factory = new DefaultSftpSessionFactory(true);
        factory.setHost("::1");
        factory.setPort(2222);
        factory.setUser("foo");
        factory.setPassword("pass");
        factory.setAllowUnknownKeys(true);
        CachingSessionFactory cachingSessionFactory = new CachingSessionFactory<>(factory);
        cachingSessionFactory.setTestSession(true);
        return cachingSessionFactory;
    }
```

**Comment by artembilan** [comment]
I think so.

Please, consider to contribute the fix and we will back-port it into respective versions!
