### ISSUE TITLE
SFTP-Put command is missing a beanfactory for expression evaluation

### ISSUE THREAD

**Issue by sonOfRa** [spring-projects/spring-integration#3393]
**In what version(s) of Spring Integration are you seeing this issue?**

5.3.2.RELEASE

**Describe the bug**

When parsing the file expression using ```Sftp.outboundGateway(sftpSessionFactory(), AbstractRemoteFileOutboundGateway.Command.PUT, "someExpressionHere")```, the expression evaluator is created with a null BeanFactory, resulting in a RuntimeException and a log message with WARN-level:

```
2020-09-28 13:19:01.199  WARN 48221 --- [ask-scheduler-1] o.s.i.expression.ExpressionUtils         : Creating EvaluationContext with no beanFactory

java.lang.RuntimeException: No beanFactory
	at org.springframework.integration.expression.ExpressionUtils.createStandardEvaluationContext(ExpressionUtils.java:90) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.util.AbstractExpressionEvaluator.getEvaluationContext(AbstractExpressionEvaluator.java:113) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.util.AbstractExpressionEvaluator.getEvaluationContext(AbstractExpressionEvaluator.java:99) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:171) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:129) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.handler.ExpressionEvaluatingMessageProcessor.processMessage(ExpressionEvaluatingMessageProcessor.java:107) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.file.remote.RemoteFileTemplate.doSend(RemoteFileTemplate.java:325) ~[spring-integration-file-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.file.remote.RemoteFileTemplate.lambda$send$0(RemoteFileTemplate.java:301) ~[spring-integration-file-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.file.remote.RemoteFileTemplate.execute(RemoteFileTemplate.java:439) ~[spring-integration-file-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:301) ~[spring-integration-file-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:289) ~[spring-integration-file-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.file.remote.gateway.AbstractRemoteFileOutboundGateway.put(AbstractRemoteFileOutboundGateway.java:789) ~[spring-integration-file-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.file.remote.gateway.AbstractRemoteFileOutboundGateway.lambda$doPut$11(AbstractRemoteFileOutboundGateway.java:775) ~[spring-integration-file-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.file.remote.RemoteFileTemplate.invoke(RemoteFileTemplate.java:471) ~[spring-integration-file-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.file.remote.gateway.AbstractRemoteFileOutboundGateway.doPut(AbstractRemoteFileOutboundGateway.java:774) ~[spring-integration-file-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.file.remote.gateway.AbstractRemoteFileOutboundGateway.doPut(AbstractRemoteFileOutboundGateway.java:770) ~[spring-integration-file-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.file.remote.gateway.AbstractRemoteFileOutboundGateway.handleRequestMessage(AbstractRemoteFileOutboundGateway.java:574) ~[spring-integration-file-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:134) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:62) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:570) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:520) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.handleMessage(SourcePollingChannelAdapter.java:196) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.messageReceived(AbstractPollingEndpoint.java:444) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:428) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:376) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$null$3(AbstractPollingEndpoint.java:323) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$4(AbstractPollingEndpoint.java:320) ~[spring-integration-core-5.3.2.RELEASE.jar:5.3.2.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
```
**To Reproduce**

Create a small IntegrationFlow that uses an SFTP Put command and a payload expression.

**Expected behavior**

There should not be a WARN message when using only internal API as it is documented

**Sample**

https://github.com/sonOfRa/spring-sftp-beanfactory

The sample is a Spring-Boot Application that runs out of the box.

Some minimal configuration is required locally in order to wire the application up to some valid SFTP server:

https://github.com/sonOfRa/spring-sftp-beanfactory/blob/7ac5b9088fd169aeffb9b7aff14febbc9f7da99e/src/main/java/com/eventim/sftpdemo/SftpDemoApplication.java#L24-L31

**Comment by artembilan** [comment]
This bug has been fixed in the https://github.com/spring-projects/spring-integration/issues/3370.

The relevant code is in the `AbstractRemoteFileOutboundGateway`:
```
if (!this.remoteFileTemplateExplicitlySet) {
	this.remoteFileTemplate.afterPropertiesSet();
}
```
The fix is going to be available in the next `5.3.3` version which is planned at the moment for October 28.

Meanwhile as a workaround consider to have an `SftpRemoteFileTemplate` as a bean and inject this one instead of that `sftpSessionFactory()` into your `Sftp.outboundGateway()` definition.

Closed as duplicated.
