### ISSUE TITLE
Spring Integration Metrics launch WARN message when the metrics are being collected in Graceful shutdown process.

### ISSUE THREAD

**Issue by admoca60** [spring-projects/spring-integration#3425]
**In what version(s) of Spring Integration are you seeing this issue?**
I can reproduce the "issue" for Spring Integration version 5.2.8.RELEASE but I can see in version 5.4.0.RELEASE (https://github.com/spring-projects/spring-integration/blob/v5.4.0/spring-integration-core/src/main/java/org/springframework/integration/config/IntegrationManagementConfigurer.java) that the gauge definitions are equals. The conflictive code is at "registerComponentGauges" method.

	private void registerComponentGauges() {
		this.gauges.add(
				this.metricsCaptor.gaugeBuilder("spring.integration.channels", this,
						(c) -> this.applicationContext.getBeansOfType(MessageChannel.class).size())
						.description("The number of message channels")
						.build());

		this.gauges.add(
				this.metricsCaptor.gaugeBuilder("spring.integration.handlers", this,
						(c) -> this.applicationContext.getBeansOfType(MessageHandler.class).size())
						.description("The number of message handlers")
						.build());

		this.gauges.add(
				this.metricsCaptor.gaugeBuilder("spring.integration.sources", this,
						(c) -> this.applicationContext.getBeansOfType(MessageSource.class).size())
						.description("The number of message sources")
						.build());
	}

**Describe the bug**

The bug will be reproducible when any application based on SpringBoot with Micrometer starts to close Spring Application context when the app receive the graceful shutdown signal. In that moment, the micrometer registry try to send the gauge metrics related to "spring.integration.channels", "spring.integration.handlers" and "spring.integration.sources".

The lambda that is executed to collect the values for that metrics invoke to Spring context (`this.applicationContext.getBeansOfType(MessageHandler.class).size()`) producing that the context try to create the beans of the types `MessageHandler`, `MessageChannel `or `MessageSource`. This try to create the beans fails and throw a message 

> Singleton bean creation not allowed while singletons of this factory are in destruction

 because, obviously, the context is in destruction phase.

**To Reproduce**

To reproduce this bug is enough to create an application with micrometer (and a meter registry as a @Bean) and wait that the context start to destruction phase.

**Expected behavior**

In my opinion, the lambda functions to retrieve the metrics should be designed in other way, avoiding to check the spring context each time that we want to retrieve the metric value.

Another suggestion that maybe should be in another different issue is the way to disable the metrics. As I know, we don't have any way/property to disable the registration (and future shipping) of the metrics related to spring integration.
I found a workaround that is using an SpringBoot Actuator property, but that property is not efficient because affect as a meter filter, but In my opinion, we should act at the origin, without interacting with micrometer.

**Sample**

I don't have any standard project now to publish. I have my own code that belongs to my company and I can't publish right now. I think that is easily reproducible.

**Comment by artembilan** [comment]
This is probably related to: https://github.com/spring-projects/spring-integration/issues/3420.

Let's see if `META-INF/spring-autoconfigure-metadata.properties` with the content like:
```
org.springframework.boot.actuate.autoconfigure.metrics.CompositeMeterRegistryAutoConfiguration.AutoConfigureBefore=org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration
```
will help us to have a proper order between the mentioned `IntegrationManagementConfigurer` and `MeterRegistry` bean, so when destruction of the application context happens, the `IntegrationManagementConfigurer` is destroyed together with its `gauges` *before* `MeterRegistry` and its metrics gathering on shutdown.

**Comment by admoca60** [comment]
I'm not really sure that it's related to this issue. In fact, before to create my issue, I was looking for if it was reported previously and I could see that one, but I thought that the issues are not strictly related because your solution seems to affect to startup process, not destroy process.

Can you reproduce the fail that I commented before currently? Is the failure fixed after the change of autoconfiguration orders?

**Comment by artembilan** [comment]
Sorry, I can't. 
It would be great if you can share a simple project to play with.

I probably miss something in my configuration or environment.
Also I'm not sure why do you have your own `MeterRegistry` bean if you use Spring  Boot...

I believe that order is cause a proper destroy as well.

**Comment by admoca60** [comment]
I will try to write an code to reproduce it ASAP. 

Regarding my "own" meterregistry. I didn't say explicilty that I would have my custom meter registry, but it's true. 

We have different meter registries because in our FWK we don't use directly all the autoconfiguration classes provides from SpringBoot. We are using Influx but we are not using InfluxMeterRegistry but a custom variation (business requirements) of that.

**Comment by admoca60** [comment]
This is the repo where we can reproduce the error 

https://github.com/admoca60/bugSpringIntegrationDemo

**Comment by artembilan** [comment]
OK. I see the warning you describe. Will investigate what to do...

But at the same time I see this error which is fully not related to Spring Integration:
```
2020-11-10 10:51:29.434 ERROR 12192 --- [extShutdownHook] i.micrometer.influx.InfluxMeterRegistry  : unable to create database 'mydb'

java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_251]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[na:1.8.0_251]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_251]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_251]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_251]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_251]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_251]
	at java.net.Socket.connect(Socket.java:606) ~[na:1.8.0_251]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_251]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_251]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_251]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_251]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_251]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226) ~[na:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[na:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[na:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990) ~[na:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340) ~[na:1.8.0_251]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315) ~[na:1.8.0_251]
	at io.micrometer.core.ipc.http.HttpUrlConnectionSender.send(HttpUrlConnectionSender.java:96) ~[micrometer-core-1.6.0.jar:1.6.0]
	at io.micrometer.core.ipc.http.HttpSender$Request$Builder.send(HttpSender.java:284) ~[micrometer-core-1.6.0.jar:1.6.0]
	at io.micrometer.influx.InfluxMeterRegistry.createDatabaseIfNecessary(InfluxMeterRegistry.java:91) [micrometer-registry-influx-1.6.0.jar:1.6.0]
	at io.micrometer.influx.InfluxMeterRegistry.publish(InfluxMeterRegistry.java:104) [micrometer-registry-influx-1.6.0.jar:1.6.0]
	at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:52) [micrometer-core-1.6.0.jar:1.6.0]
	at io.micrometer.core.instrument.push.PushMeterRegistry.close(PushMeterRegistry.java:89) [micrometer-core-1.6.0.jar:1.6.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_251]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:339) [spring-beans-5.3.0.jar:5.3.0]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:273) [spring-beans-5.3.0.jar:5.3.0]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) [spring-beans-5.3.0.jar:5.3.0]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) [spring-beans-5.3.0.jar:5.3.0]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1152) [spring-beans-5.3.0.jar:5.3.0]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) [spring-beans-5.3.0.jar:5.3.0]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1145) [spring-beans-5.3.0.jar:5.3.0]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1113) [spring-context-5.3.0.jar:5.3.0]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1082) [spring-context-5.3.0.jar:5.3.0]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:998) [spring-context-5.3.0.jar:5.3.0]
```

Probably better to raise with Spring Boot project to be sure what is going on.
In fact we have the same problem: the shutdown hook tries to call some metrics emission and does that against the mentioned Influx, but its bean is being destroyed therefore we can't get access to the `mydb`.

**Comment by artembilan** [comment]
OK. I think `destroy()` is not good place for such a central component to try to clean its infrastructure properly.
We really can't have dependency for all those bean to have a proper destruction order.
Anyway it doesn't look like it is a good idea to try to gather such an info when we are already in the destruction phase.

To mitigate the problem I think I'll fix Spring Integration `IntegrationManagementConfigurer` to react for the`ContextClosedEvent` instead of `destroy()`, so we will remove gauges before that `PushMeterRegistry.publishSafely()` is called.

**Comment by admoca60** [comment]
The error "java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_251]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[na:1.8.0_251]" is due to you need a InfluxDB docker container in local. Try to use the default image.

The error I refer is "Singleton bean creation not allowed while singletons of this factory are in destruction"

**Comment by admoca60** [comment]
Regarding the behaviour of Micrometer in destruction phase, we cannot change this behaviour.

Are you considered the option to change how the metrics are collected from instead of remove the metrics before the context close?

Maybe, if you have a listener feeding a @Bean with the values, you wouldn't to do the command "this.applicationContext.getBeansOfType(MessageHandler.class).size()"

**Comment by artembilan** [comment]
I will go the logical way: since we are in destruction phase, there is nothing to gather as a metrics. Therefore it is just safe to delete those metrics from the meter registry at that point.
