### ISSUE TITLE
IntegrationFlowRegistration NPE when RuntimeException thrown from delay handler

### ISSUE THREAD

**Issue by RonNitschke** [spring-projects/spring-integration#3433]
I'm using Spring Boot 2.2.7.RELEASE 

I am getting a NPE when using IntegrationFlowRegistration for a File based Flow, with org.springframework.integration.dsl.IntegrationFlowDefinition.delay and when a file exists at startup in the Polling Directory. If the GenericHandler in https://docs.spring.io/spring-integration/api/org/springframework/integration/dsl/IntegrationFlowDefinition.html#handle-org.springframework.integration.handler.GenericHandler- throws a RuntimeException, then I get a NPE .

Source code that reproduces the error:

```
/**
 * Test the {@link org.springframework.integration.dsl#delay} with a file IntegrationFlowRegistration.
 */
@SpringBootTest
@ExtendWith(SpringExtension.class)
public class TestDelayFileIntegrationFlowRegistration {

  private static final Logger LOG = LoggerFactory.getLogger("TestDelayFileIntegrationFlowRegistration");

  static File pollDirectory2 = new File("/tmp/polltest2");


  /**
   * Configure the {@link IntegrationFlowRegistration}.
   */
  @Configuration
  @EnableIntegration
  public static class ContextConfiguration {


    private static File newFile2 = new File(pollDirectory2, "newFile2.txt");

    static {
      try {
        if (!newFile2.exists()) {
          newFile2.mkdirs();
        }
        newFile2.createNewFile();
      } catch (IOException e) {
        e.printStackTrace();
      }
    }

    @Autowired
    private IntegrationFlowContext flowContext;

    /**
     * Setup the {@link IntegrationFlowRegistration}.
     *
     * @return the {@link IntegrationFlowRegistration}.
     */
    @Bean
    public IntegrationFlowRegistration fileFlow2() {
      IntegrationFlow flow = IntegrationFlows
          .from(Files.inboundAdapter(pollDirectory2), e -> e.poller(Pollers.fixedDelay(100)))
          .delay("delayer",
              (DelayerEndpointSpec e) -> e.defaultDelay(1000))
          .handle(File.class, (file, headers) -> {
            LOG.info("**** Retry handling for " + file);
            if (file.exists()) {
              LOG.info("**** file exists");
              throw new RuntimeException();
            } else {
              LOG.info("*** No File");
            }
            return null;
          })
          .get();
      return this.flowContext.registration(flow).register();
    }

  }

  /**
   * Test the file flow.
   *
   * @throws Exception
   */
  @Test
  public void testFileFlow() throws Exception {

    (new File(pollDirectory2, "yetAnotherNewFile.txt")).createNewFile();

    Thread.sleep(5000);
  }

}
```

For the above code I'm seeing the following NPE:

```
20:43:34.468 [task-scheduler-4] ERROR o.s.i.handler.LoggingHandler - java.lang.NullPointerException at org.springframework.integration.handler.DelayHandler.releaseMessage(DelayHandler.java:454) at org.springframework.integration.handler.DelayHandler.lambda$releaseMessageAfterDelay$0(DelayHandler.java:412) at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834)
```

The following test that doesn't use an IntegrationFlowRegistration runs without throwing a NPE.

```
@SpringBootTest
@ExtendWith(SpringExtension.class)
public class TestDelayFileIntegrationFlowRegistration {

  private static final Logger LOG = LoggerFactory.getLogger("TestDelayFileIntegrationFlowRegistration");

  static File pollDirectory2 = new File("/tmp/polltest2");


  /**
   * Configure the {@link IntegrationFlowRegistration}.
   */
  @Configuration
  @EnableIntegration
  public static class ContextConfiguration {


    private static File newFile2 = new File(pollDirectory2, "newFile2.txt");

    static {
      try {
        if (!newFile2.exists()) {
          newFile2.mkdirs();
        }
        newFile2.createNewFile();
      } catch (IOException e) {
        e.printStackTrace();
      }
    }

    @Autowired
    private IntegrationFlowContext flowContext;

    /**
     * Setup the {@link IntegrationFlowRegistration}.
     *
     * @return the {@link IntegrationFlowRegistration}.
     */
    @Bean
    public IntegrationFlowRegistration fileFlow2() {
      IntegrationFlow flow = IntegrationFlows
          .from(Files.inboundAdapter(pollDirectory2), e -> e.poller(Pollers.fixedDelay(100)))
          .delay("delayer",
              (DelayerEndpointSpec e) -> e.defaultDelay(1000))
          .handle(File.class, (file, headers) -> {
            LOG.info("**** Retry handling for " + file);
            if (file.exists()) {
              LOG.info("**** file exists");
              throw new RuntimeException();

            } else {
              LOG.info("*** No `File");
            }
            return null;
          })
          .get();
      return this.flowContext.registration(flow).register();
    }

  }


  /**
   * Test the file flow.
   *
   * @throws Exception
   */
  @Test
  public void testFileFlow() throws Exception {

    (new File(pollDirectory2, "yetAnotherNewFile.txt")).createNewFile();

    Thread.sleep(5000);
  }

}
```

You can download the reproducer from https://github.com/RonNitschke/SpringIntegration.git

**Comment by artembilan** [comment]
Sorry, I don't see a difference between your provided tests.
And it is not clear what is the point to use an `IntegrationFlowContext` if you are going to do everything during regular bean initialization phase. I mean your `@Bean` on the `IntegrationFlowRegistration` is really strange.
Plus the `flowContext.registration(flow).register()` does some hard work with application context.
We really may end up with the strange behavior trying to add more beans during bean initialization phase.
The point of the `IntegrationFlowContext` is to be used already at runtime when regular static bean initialization phase is not enough.

I would see your final solution as a `@Bean` for the regular `IntegrationFlow` without any `IntegrationFlowContext` involvement.

Sure, we will look into NPE and possible fix, but it is very suspicious to fix it for the code which doesn't look like the right way to go. This is something similar what reminds me a plain Spring question when people ask: "why my object is not autowired when I call a `new` for its constructor?" We indeed end up with NPE over there as well. I know, our situation is more complicated, but it still fits to category "wrong way to use Spring".

Thanks for understanding

**Comment by RonNitschke** [comment]
Thanks for your reply.  

In our project we have a configurable integration flow, so using IntegrationFlowRegistration is required. 

As you suggested, when I perform the registration of the IntegrationFlow after the Bean initialisation phase, the application then runs without this error.

Thanks again for you time.
