### ISSUE TITLE
Building With JDK11 Breaks TCP (NIO)

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#3470]
See https://github.com/spring-projects/spring-integration-samples/issues/291

`ByteBuffer.flip()` now returns `ByteBuffer`, previously it returned `Buffer`.

Cannot run with JDK8.

```
Exception in thread "pool-2-thread-2" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at org.springframework.integration.ip.tcp.connection.TcpNioConnection.doRead(TcpNioConnection.java:437)
	at org.springframework.integration.ip.tcp.connection.TcpNioConnection.readPacket(TcpNioConnection.java:499)
	at org.springframework.integration.ip.tcp.connection.AbstractConnectionFactory.lambda$processNioSelections$7(AbstractConnectionFactory.java:708)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

WorkAround:

https://github.com/plasma-umass/doppio/issues/497#issuecomment-334740243

**Comment by garyrussell** [comment]
Reopening. Other methods suffer from the same problem.
