### ISSUE TITLE
Revise configuration code for better Spring Native support

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration#3502]
See more info in [Spring Native](https://docs.spring.io/spring-native/docs/0.9.0-SNAPSHOT/reference/#_designing_native_friendly_spring_libraries).

At the moment it is important to revise `ImportSelector` impls and class presence checks.

Related to: https://github.com/spring-projects/spring-framework/issues/18353

**Comment by artembilan** [comment]
```
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:83) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1308) ~[na:na]
        ... 17 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.springframework.integration.config.IntegrationConfigurationBeanFactoryPostProcessor.<init>()

```

Looks like Spring requires explicit public default ctor for that type of bean in Native mode:
```
		if (NativeDetector.inNativeImage()) {
			this.instantiationStrategy = new SimpleInstantiationStrategy();
		}
		else {
			this.instantiationStrategy = new CglibSubclassingInstantiationStrategy();
		}
```

**Comment by artembilan** [comment]
Yeah... Better to say this: https://docs.spring.io/spring-native/docs/current-SNAPSHOT/reference/htmlsingle/#how-to-contribute to align with whatever is the latest.

**Comment by artembilan** [comment]
`GroovyScriptExecutingMessageProcessor`:
```
		GroovyObject goo = (GroovyObject) BeanUtils.instantiateClass(this.scriptClass);
```
`MapToObjectTransformer`:
```
Object target = (this.targetClass != null)
				? BeanUtils.instantiateClass(this.targetClass)
				: this.getBeanFactory().getBean(this.targetBeanName);
```
Or even `JmsChannelFactoryBean`:
```
AbstractMessageListenerContainer container = BeanUtils.instantiateClass(this.containerType);
```
and respective Java DSL:
```
protected JmsListenerContainerSpec(Class<C> aClass) {
		super(BeanUtils.instantiateClass(aClass));
```

Well, technically every single place where we indeed rely on the reflection at runtime.
This probably can be handled only via `@NativeHint` in Spring Native project.

**Comment by artembilan** [comment]
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'errorChannel': Unexpected exception during bean creation; nested exception is org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.expression.spel.Spel
EvaluationException: EL1005E: Type cannot be found 'org.springframework.integration.context.IntegrationContextUtils'
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:537) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:774) ~[org.springframework.integration.demonative.DemoNativeApplication:2.5.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:443) ~[org.springframework.integration.demonative.DemoNativeApplication:2.5.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:341) ~[org.springframework.integration.demonative.DemoNativeApplication:2.5.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[org.springframework.integration.demonative.DemoNativeApplication:2.5.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1341) ~[org.springframework.integration.demonative.DemoNativeApplication:2.5.0-SNAPSHOT]
        at org.springframework.integration.demonative.DemoNativeApplication.main(DemoNativeApplication.java:15) ~[org.springframework.integration.demonative.DemoNativeApplication:na]
Caused by: org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.expression.spel.SpelEvaluationException: EL1005E: Type cannot be found 'org.springframework.integration.context.IntegrationContextUtils'
        at org.springframework.context.expression.StandardBeanExpressionResolver.evaluate(StandardBeanExpressionResolver.java:169) ~[na:na]
        at org.springframework.integration.config.DefaultConfiguringBeanFactoryPostProcessor.resolveExpression(DefaultConfiguringBeanFactoryPostProcessor.java:595) ~[na:na]
        at org.springframework.integration.config.DefaultConfiguringBeanFactoryPostProcessor.createErrorChannel(DefaultConfiguringBeanFactoryPostProcessor.java:283) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1231) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1173) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[na:na]
        ... 13 common frames omitted
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1005E: Type cannot be found 'org.springframework.integration.context.IntegrationContextUtils'
        at org.springframework.expression.spel.support.StandardTypeLocator.findType(StandardTypeLocator.java:117) ~[na:na]
        at org.springframework.expression.spel.ExpressionState.findType(ExpressionState.java:155) ~[na:na]
        at org.springframework.expression.spel.ast.TypeReference.getValueInternal(TypeReference.java:69) ~[na:na]
        at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:55) ~[na:na]
        at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:91) ~[na:na]
        at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:112) ~[na:na]
        at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:272) ~[na:na]
        at org.springframework.context.expression.StandardBeanExpressionResolver.evaluate(StandardBeanExpressionResolver.java:166) ~[na:na]
        ... 19 common frames omitted
```

We probably can figure out something on the framework level how to be with this and similar SpEL expressions we use for out-of-the-box and support components, but it is definitely has to be somehow addressed in the target  projects for end-user expressions and their types. Probably the same `@NativeHint` can help but already in the end-user code...

**Comment by artembilan** [comment]
I'm moving this issue back to `5.5` with more priority at the moment since there is a demand from the community.

With the latest PR the basic app works well.
We probably need to go over a basic Spring Cloud Stream app with this solution to be sure where we are with the rest of reflection in the framework
