### ISSUE TITLE
Need of errorChannel on spring integration aggregation

### ISSUE THREAD

**Issue by abdulmohsin** [spring-projects/spring-integration#3504]
**Expected Behavior**

Refer : https://stackoverflow.com/questions/66486861/spring-integration-messagegroupstorereaper-global-errorchannel

In the aggregation scenarios ( partial / complete /expire etc)  flow which is triggered through a MessageGroupStoreReaper.run & scheduled task  ,  if there is any exception post aggregation then exception should be routed to global error channel ("errorChannel") like in a normal spring integration flow

**Current Behavior**

As the MessageGroupStoreReaper is getting triggered through a separate task scheduler , the exceptions post aggregation flows are not reaching to global errorChannel.

Tried two more things but it didn't work : 

1. Instead of a task scheduler , used the inbound adapter and poller with errorChannel
<int:inbound-channel-adapter channel="reaperChannel" ref="MyMsgsAggregator" method="triggerReaper"> 
<int:poller error-channel="**errorChannel**" fixed-rate="5000">         
</int:poller>

2. Post aggregation , populated the "errorChannel" through header enhancer but still didn't work.

Refer : https://stackoverflow.com/questions/66486861/spring-integration-messagegroupstorereaper-global-errorchannel

**Context**

**Comment by artembilan** [comment]
After thinking about this a bit more, I come to the conclusion that it is not an aggregator responsibility to do such a manipulation.
The aggregator is just in the middle of the flow: it is already an original caller to be sure how to deal with errors in the stream it is initiating. And this one is exactly general solution for all the flows we can build with Spring Integration - with an aggregator in the middle or not. 

As you noticed there are 3 possible scenarios for an aggregator to do its job:

1. Regular message arrival release - the upstream called is responsible for error handling thrown after an aggregator reply.
2. `MessageGroupStoreReaper.run()` - the scheduled task which can catch and handle errors thrown from the expire or partial result processing. In this case, if you rely on Spring Integration, the `taskScheduler` bean is registered with the `integrationMessagePublishingErrorHandler` reference, where an `errorChannel` header is resolved or a global `errorChannel` is used to publish an `ErrorMessage`.
3. And one more scenario when an aggregator schedules an expiring task internally according its `groupTimeout`. In this case it is still using the same `taskScheduler` bean with the mentioned `integrationMessagePublishingErrorHandler` logic.

So, since you claim that you have problems with error handling via an `errorChannel`, then it looks more like you use wrong `TaskScheduler` for your reaper task.

We probably just need to improve an `Error Handling` chapter in the docs: https://docs.spring.io/spring-integration/docs/current/reference/html/error-handling.html#error-handling and mention how to handle them in the aggregator chapter. Because of those async tasks as origin for the process it really might be confusing a little bit...

**Comment by abdulmohsin** [comment]
Thanks Artembilan,

Currently point#2 is not working as I mentioned on the stackoverflow even if we trigger a reaper through a poller configured with errorChannel errors are not reaching global error channel :

<int:inbound-channel-adapter channel="reaperChannel" ref="MyMsgsAggregator" method="triggerReaper"> 
<int:poller error-channel="**errorChannel**" fixed-rate="5000">         
</int:poller>

if we can make it working then I agree there is no need to have aggregator with "errorChannel" attribute.

Many thanks
Abdul Mohsin

**Comment by artembilan** [comment]
Good. Let me test that use-case then! We definitely can come up with something what is related to `<int:inbound-channel-adapter>` 😄

**Comment by artembilan** [comment]
Works well:

````xml
	<bean id="messageStore4" class="org.springframework.integration.store.SimpleMessageStore">
		<property name="expiryCallbacks">
			<bean class="org.springframework.integration.store.MessageStoreReaperTests$ErrorExpiryCallback"/>
		</property>
	</bean>

	<bean id="reaper4" class="org.springframework.integration.store.MessageGroupStoreReaper">
		<property name="messageGroupStore" ref="messageStore4"/>
		<property name="timeout" value="0" />
	</bean>

	<int:inbound-channel-adapter id="reaperTrigger" channel="nullChannel" expression="@reaper4.run()"
								 auto-startup="false">
		<int:poller error-channel="reaperErrors" fixed-delay="500"/>
	</int:inbound-channel-adapter>

	<int:channel id="reaperErrors">
		<int:queue />
	</int:channel>
````
````java
@SpringJUnitConfig
@DirtiesContext
public class MessageStoreReaperTests {

	@Autowired
	private MessageGroupStore messageStore4;

	@Autowired
	private SourcePollingChannelAdapter reaperTrigger;

	@Autowired
	private PollableChannel reaperErrors;


	@Test
	public void testErrorFromReaperPropagatedToErrorChannel() {
		this.messageStore4.addMessageToGroup("testGroup", new GenericMessage<>("test"));

		this.reaperTrigger.start();

		Message<?> receive = this.reaperErrors.receive(10_000);
		assertThat(receive).isNotNull()
				.extracting(Message::getPayload)
				.asInstanceOf(InstanceOfAssertFactories.type(MessagingException.class))
				.extracting(MessagingException::getCause)
				.isInstanceOf(RuntimeException.class)
				.extracting("message")
				.isEqualTo("intentional");

		this.reaperTrigger.stop();
	}

	public static class ErrorExpiryCallback implements MessageGroupCallback {

		@Override
		public void execute(MessageGroupStore messageGroupStore, MessageGroup group) {
			throw new RuntimeException("intentional");
		}

	}

}
````

This test confirms that exception thrown from the `MessageGroupCallback.execute()` callback on the `MessageGroupStoreReaper.run()` is propagated to the `errorChannel` configured on the `<int:inbound-channel-adapter>`.
See logs:
```
2021-03-15 14:36:02,655 ERROR [task-scheduler-1] [org.springframework.integration.store.SimpleMessageStore] - Exception in expiry callback
java.lang.RuntimeException: intentional
	at org.springframework.integration.store.MessageStoreReaperTests$ErrorExpiryCallback.execute(MessageStoreReaperTests.java:182) ~[classes/:?]
	at org.springframework.integration.store.AbstractMessageGroupStore.expire(AbstractMessageGroupStore.java:199) ~[classes/:?]
	at org.springframework.integration.store.AbstractMessageGroupStore.expireMessageGroups(AbstractMessageGroupStore.java:137) ~[classes/:?]
	at org.springframework.integration.store.MessageGroupStoreReaper.run(MessageGroupStoreReaper.java:118) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:129) ~[spring-expression-5.3.5-SNAPSHOT.jar:5.3.5-SNAPSHOT]
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:139) ~[spring-expression-5.3.5-SNAPSHOT.jar:5.3.5-SNAPSHOT]
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:55) ~[spring-expression-5.3.5-SNAPSHOT.jar:5.3.5-SNAPSHOT]
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:387) ~[spring-expression-5.3.5-SNAPSHOT.jar:5.3.5-SNAPSHOT]
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:92) ~[spring-expression-5.3.5-SNAPSHOT.jar:5.3.5-SNAPSHOT]
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:117) ~[spring-expression-5.3.5-SNAPSHOT.jar:5.3.5-SNAPSHOT]
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:308) ~[spring-expression-5.3.5-SNAPSHOT.jar:5.3.5-SNAPSHOT]
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:159) ~[classes/:?]
	at org.springframework.integration.endpoint.ExpressionEvaluatingMessageSource.doReceive(ExpressionEvaluatingMessageSource.java:48) ~[classes/:?]
	at org.springframework.integration.endpoint.AbstractMessageSource.receive(AbstractMessageSource.java:142) ~[classes/:?]
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.receiveMessage(SourcePollingChannelAdapter.java:212) ~[classes/:?]
```

**Comment by artembilan** [comment]
Schedule the issue as `documentation` to explain that `TaskScheduler` for the `MessageGroupStoreReaper` must be supplied with the `MessagePublishingErrorHandler`, like it comes with the default one in the framework - see `DefaultConfiguringBeanFactoryPostProcessor`:
```
/**
 * Register a {@link ThreadPoolTaskScheduler}  bean in the application context.
 */
private void registerTaskScheduler() {
		if (!this.beanFactory.containsBean(IntegrationContextUtils.TASK_SCHEDULER_BEAN_NAME)) {
			if (LOGGER.isInfoEnabled()) {
				LOGGER.info("No bean named '" + IntegrationContextUtils.TASK_SCHEDULER_BEAN_NAME +
						"' has been explicitly defined. " +
						"Therefore, a default ThreadPoolTaskScheduler will be created.");
			}
			BeanDefinition scheduler = BeanDefinitionBuilder.genericBeanDefinition(ThreadPoolTaskScheduler.class)
					.addPropertyValue("poolSize", IntegrationProperties
							.getExpressionFor(IntegrationProperties.TASK_SCHEDULER_POOL_SIZE))
					.addPropertyValue("threadNamePrefix", "task-scheduler-")
					.addPropertyValue("rejectedExecutionHandler", new CallerRunsPolicy())
					.addPropertyReference("errorHandler",
							ChannelUtils.MESSAGE_PUBLISHING_ERROR_HANDLER_BEAN_NAME)
					.getBeanDefinition();

			this.registry.registerBeanDefinition(IntegrationContextUtils.TASK_SCHEDULER_BEAN_NAME, scheduler);
		}
}
```
