### ISSUE TITLE
Cannot register SimplePatternFileListFilter filter in IntegrationFlow

### ISSUE THREAD

**Issue by MateuszWicherski** [spring-projects/spring-integration#3537]
**In what version(s) of Spring Integration are you seeing this issue?**

For example:

5.4.4+ (spring-boot-integration 2.4.3+). Working correctly in 5.4.3 (spring-boot-integration 2.4.2).

**Describe the bug**

When I try to register `SimplePatternFileListFilter` in the integration flow (polling for files), an `IllegalArgumentException` is thrown.
```
Caused by: java.lang.IllegalArgumentException: Found ambiguous parameter type [class java.lang.Boolean] for method match: [public final boolean org.springframework.integration.file.filters.AbstractSimplePatternFileListFilter.accept(java.lang.Object), public boolean org.springframework.integration.file.filters.AbstractFileListFilter.supportsSingleFileFiltering(), public final java.util.List org.springframework.integration.file.filters.AbstractFileListFilter.filterFiles(java.lang.Object[]), public void org.springframework.integration.file.filters.AbstractDirectoryAwareFileListFilter.setForRecursion(boolean)]
	at org.springframework.util.Assert.isNull(Assert.java:179) ~[spring-core-5.3.5.jar:5.3.5]
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.validateFallbackMethods(MessagingMethodInvokerHelper.java:757) ~[spring-integration-core-5.4.5.jar:5.4.5]
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.findHandlerMethodsForTarget(MessagingMethodInvokerHelper.java:742) ~[spring-integration-core-5.4.5.jar:5.4.5]
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.<init>(MessagingMethodInvokerHelper.java:295) ~[spring-integration-core-5.4.5.jar:5.4.5]
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.<init>(MessagingMethodInvokerHelper.java:232) ~[spring-integration-core-5.4.5.jar:5.4.5]
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.<init>(MessagingMethodInvokerHelper.java:226) ~[spring-integration-core-5.4.5.jar:5.4.5]
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.<init>(MethodInvokingMessageProcessor.java:62) ~[spring-integration-core-5.4.5.jar:5.4.5]
	at org.springframework.integration.filter.MethodInvokingSelector.<init>(MethodInvokingSelector.java:50) ~[spring-integration-core-5.4.5.jar:5.4.5]
	at org.springframework.integration.dsl.BaseIntegrationFlowDefinition.filter(BaseIntegrationFlowDefinition.java:796) ~[spring-integration-core-5.4.5.jar:5.4.5]
	at org.springframework.integration.dsl.BaseIntegrationFlowDefinition.filter(BaseIntegrationFlowDefinition.java:782) ~[spring-integration-core-5.4.5.jar:5.4.5]
	at org.springframework.integration.dsl.BaseIntegrationFlowDefinition.filter(BaseIntegrationFlowDefinition.java:770) ~[spring-integration-core-5.4.5.jar:5.4.5]
	at pl.wicherski.spring.springintegrationbug.IntegrationConfig.fileReadingFlow(IntegrationConfig.java:27) ~[classes/:na]
	at pl.wicherski.spring.springintegrationbug.IntegrationConfig$$EnhancerBySpringCGLIB$$de0b3cf2.CGLIB$fileReadingFlow$1(<generated>) ~[classes/:na]
	at pl.wicherski.spring.springintegrationbug.IntegrationConfig$$EnhancerBySpringCGLIB$$de0b3cf2$$FastClassBySpringCGLIB$$94718d05.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.5.jar:5.3.5]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.5.jar:5.3.5]
	at pl.wicherski.spring.springintegrationbug.IntegrationConfig$$EnhancerBySpringCGLIB$$de0b3cf2.fileReadingFlow(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.5.jar:5.3.5]
	... 20 common frames omitted
```

**To Reproduce**

Run sample application (link to repository below).

**Expected behavior**

An exception shouldn't be thrown when registering `FileListFilter`.

**Sample**

https://github.com/MateuszWicherski/spring-integration-bug
To see expected behavior reduce `spring-boot-starter-parent` version to 2.4.2

**Comment by artembilan** [comment]
This is wrong:
```
.filter(new SimplePatternFileListFilter("*.txt"))
```

The `FileListFilter` is exactly for the `Files.inboundAdapter(new File("source")`.
See its respective option:
```
	/**
	 * Configure the filter.
	 * @param filter the filter.
	 * @return the spec.
	 * @see FileReadingMessageSource#setFilter(FileListFilter)
	 */
	public FileInboundChannelAdapterSpec filter(FileListFilter<File> filter) {
```

The `IntegrationFlowDefinition.filter()` API is for a EI `filter` pattern, which indeed may work with any POJO method invocation, but you have to be more specific with a particular method if there are more than one candidate.

It really was a coincidence that it worked before. Just because we have introduced several other APIs into a `FileListFilter` it is failing for you right now.

Please, see more docs about both of them:

https://docs.spring.io/spring-integration/reference/html/message-routing.html#filter

https://docs.spring.io/spring-integration/reference/html/file.html#file-reading

The point is that `FileListFilter` is in wrong place in your code.

You better to use this one instead:
```
/**
	 * Configure a
	 * {@link org.springframework.integration.file.filters.SimplePatternFileListFilter}.
	 * @param pattern The pattern.
	 * @return the spec.
	 * @see FileReadingMessageSource#setFilter(FileListFilter)
	 * @see #filter(FileListFilter)
	 */
	public FileInboundChannelAdapterSpec patternFilter(String pattern) {
```

So, closing this as target project bug and invalid in context of this one.

**Comment by MateuszWicherski** [comment]
Thank you very much for the quick response!
