### ISSUE TITLE
JacksonJsonUtils no longer supports java 8

### ISSUE THREAD

**Issue by lesp83** [spring-projects/spring-integration#3762]
Hello - we recently upgraded to spring 2.5.11 from 2.5.10 in our spring cloud stream kafka project and we started getting a NoSuchMethodException.  We noticed that line 58 of JacksonJsonUtils.java changed to a List.of which is available in java 9+.

Was this intentional?

https://github.com/spring-projects/spring-integration/blob/main/spring-integration-
core/src/main/java/org/springframework/integration/support/json/JacksonJsonUtils.java

Specifically:
`	public static final List<String> DEFAULT_TRUSTED_PACKAGES =
			List.of(
					"java.util",
					"java.lang",
					"org.springframework.messaging.support",
					"org.springframework.integration.support",
					"org.springframework.integration.message",
					"org.springframework.integration.store",
					"org.springframework.integration.history"
			);`

Last bit of the stack trace
`Caused by: java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;

	at org.springframework.integration.support.json.JacksonJsonUtils.<clinit>(JacksonJsonUtils.java:58)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.<init>(KafkaMessageDrivenChannelAdapter.java:139)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:726)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:158)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:408)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:91)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143)
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:177)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:134)
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:118)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	... 14 common frames omitted`

**Comment by artembilan** [comment]
It was not. See here for more info: https://github.com/spring-projects/spring-integration/issues/3761.
