### ISSUE TITLE
When use mail filtering function,the rootObject is null value

### ISSUE THREAD

**Issue by XhstormR** [spring-projects/spring-integration#3861]
**In what version(s) of Spring Integration are you seeing this issue?**

5.5.13.RELEASE
![image](https://user-images.githubusercontent.com/10527522/180677649-b7c95eae-2ca7-43f1-b761-6858fadf0c95.png)

**Describe the bug**

I looked in the documentation for the description of email filtering, but found that the root object is always null, causing an error in the SPEL expression.

https://docs.spring.io/spring-integration/reference/html/mail.html#mail-filtering

![image](https://user-images.githubusercontent.com/10527522/180677183-af645152-dd96-40c4-98e6-cb8adeb4eb85.png)

**To Reproduce**

Kotlin code:
```kotlin
    @Bean
    fun integrationFlow() = IntegrationFlows.from(mailInboundChannelAdapterSpec())
        .handle(MailMessageHandler())
        .get()

    private fun mailInboundChannelAdapterSpec() =
        Mail.imapIdleAdapter("imaps://user:pass@imap.qq.com:993/INBOX")
            .autoStartup(true)
            .shouldReconnectAutomatically(true)
            .simpleContent(false)
            .autoCloseFolder(false)
            .embeddedPartsAsBytes(false)
            .shouldDeleteMessages(false)
            .shouldMarkMessagesAsRead(true)
            .selectorExpression("subject matches '(?i).*Spring Integration.*'")
            .maxFetchSize(1)
            .headerMapper(DefaultMailHeaderMapper())
```

Log:
```
2022-07-25 09:34:18.398  INFO 45193 --- [  restartedMain] com.xhstormr.erp.ApplicationKt           : Starting ApplicationKt using Java 18.0.1 on c02ft5jdmd6m with PID 45193 (/Users/user/IdeaProjects/ERP/build/classes/kotlin/main started by user in /Users/user/IdeaProjects/ERP)
2022-07-25 09:34:18.399  INFO 45193 --- [  restartedMain] com.xhstormr.erp.ApplicationKt           : The following 3 profiles are active: "attachment", "cors", "dev"
2022-07-25 09:34:19.656  INFO 45193 --- [  restartedMain] com.xhstormr.erp.ApplicationKt           : Started ApplicationKt in 1.688 seconds (JVM running for 2.071)
2022-07-25 09:35:30.206  WARN 45193 --- [   scheduling-1] o.s.i.mail.ImapIdleChannelAdapter        : Failed to execute IDLE task. Will attempt to resubmit in 10000 milliseconds.

org.springframework.expression.spel.SpelEvaluationException: EL1037E: First operand to matches operator must be a string. 'null' is not
	at org.springframework.expression.spel.ast.OperatorMatches.getValueInternal(OperatorMatches.java:69)
	at org.springframework.expression.spel.ast.OperatorMatches.getValueInternal(OperatorMatches.java:41)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:117)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:376)
	at org.springframework.integration.mail.AbstractMailReceiver.filterMessagesThruSelector(AbstractMailReceiver.java:556)
	at org.springframework.integration.mail.AbstractMailReceiver.searchAndFilterMessages(AbstractMailReceiver.java:425)
	at org.springframework.integration.mail.AbstractMailReceiver.receive(AbstractMailReceiver.java:380)
	at org.springframework.integration.mail.ImapIdleChannelAdapter$IdleTask.run(ImapIdleChannelAdapter.java:274)
	at org.springframework.integration.mail.ImapIdleChannelAdapter$ReceivingTask.run(ImapIdleChannelAdapter.java:246)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Expected behavior**

Mail filtering function works normally.

**Comment by XhstormR** [comment]
N/A
