### ISSUE TITLE
error when using `spring-integration-ftp` inbound adapter with AOT in Spring Boot 3.0.M5

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-integration#3910]
hi, i get the following error using spring integration's ftp inbound adapter with spring boot 3.0.m5 AOT support.

NB: this does NOT cause the application to fail. it just spews a huge stack trace on the console.

```springframework.integration.config.IntegrationManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-10-11T04:22:45.211-07:00  WARN 22068 --- [           main] o.s.i.expression.ExpressionUtils         : Creating EvaluationContext with no beanFactory

java.lang.RuntimeException: No beanFactory
        at org.springframework.integration.expression.ExpressionUtils.createStandardEvaluationContext(ExpressionUtils.java:90) ~[na:na]
        at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizer.afterPropertiesSet(AbstractInboundFileSynchronizer.java:292) ~[ftp:6.0.0-M5]
        at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizingMessageSource.onInit(AbstractInboundFileSynchronizingMessageSource.java:201) ~[ftp:6.0.0-M5]
        at org.springframework.integration.util.AbstractExpressionEvaluator.afterPropertiesSet(AbstractExpressionEvaluator.java:93) ~[ftp:6.0.0-M5]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1800) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1750) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[ftp:6.0.0-M6]
        at org.springframework.integration.dsl.context.IntegrationFlowBeanPostProcessor.registerComponent(IntegrationFlowBeanPostProcessor.java:453) ~[ftp:na]
        at org.springframework.integration.dsl.context.IntegrationFlowBeanPostProcessor.processStandardIntegrationFlow(IntegrationFlowBeanPostProcessor.java:219) ~[ftp:na]
        at org.springframework.integration.dsl.context.IntegrationFlowBeanPostProcessor.postProcessBeforeInitialization(IntegrationFlowBeanPostProcessor.java:115) ~[ftp:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:420) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1746) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[ftp:6.0.0-M6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:931) ~[ftp:6.0.0-M6]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:926) ~[ftp:6.0.0-M6]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:592) ~[ftp:6.0.0-M6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:751) ~[ftp:3.0.0-M5]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:442) ~[ftp:3.0.0-M5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[ftp:3.0.0-M5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1323) ~[ftp:3.0.0-M5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[ftp:3.0.0-M5]
        at aot.ftp.FtpApplication.main(FtpApplication.java:18) ~[ftp:an] 
```

given the following code 

```
package aot.ftp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.integration.dsl.IntegrationFlow;
import org.springframework.integration.ftp.dsl.Ftp;
import org.springframework.integration.ftp.session.DefaultFtpSessionFactory;

import java.io.File;
import java.util.concurrent.TimeUnit;

@SpringBootApplication
public class FtpApplication {

    public static void main(String[] args) {
        SpringApplication.run(FtpApplication.class, args);
    }

}

@Configuration
class FtpConfiguration {


    @Bean
    DefaultFtpSessionFactory defaultFtpSessionFactory() {
        var ftp = new DefaultFtpSessionFactory();
        ftp.setUsername("guest");
        ftp.setPassword("guest");
        ftp.setPort(7777);
        return ftp;
    }

    @Bean
    IntegrationFlow inbound(DefaultFtpSessionFactory ftpSf) {
        var localDirectory = new File(new File(System.getProperty("user.home"), "Desktop"), "local");
        var spec = Ftp
                .inboundAdapter(defaultFtpSessionFactory())
                .remoteDirectory("/")
                .autoCreateLocalDirectory(true)
                .patternFilter("*.txt")
                .localDirectory(localDirectory)
                .get();
        return IntegrationFlow
                .from(spec, pc -> pc.poller(pm -> pm.fixedRate(1000, TimeUnit.MILLISECONDS)))
                .handle((file, messageHeaders) -> {
                    System.out.println("new file: " + file + ".");
                    messageHeaders.forEach((k, v) -> System.out.println(k + ':' + v));
                    return null;
                })
                .get();
    }
}
```

and the following `pom.xml` 

```<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.0-M5</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>aot</groupId>
	<artifactId>ftp</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>ftp</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-integration</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-ftp</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

</project>
```

**Comment by artembilan** [comment]
@joshlong ,

this has nothing to do with AOT: if the component you provide is not Spring bean, you got that warning either way. That's first.
Second: it is not OK to call `get()` on the `Spec` manually.
I'm sure if you do like this, then it is going to be OK:
```
      var spec = Ftp
                .inboundAdapter(defaultFtpSessionFactory())
                .remoteDirectory("/")
                .autoCreateLocalDirectory(true)
                .patternFilter("*.txt")
                .localDirectory(localDirectory);
```
You see, there is no `get()` in the end.

I would suggest to have your code more cleaner like this:
```
    @Bean
    FtpInboundChannelAdapterSpec ftpInboundSpec(DefaultFtpSessionFactory ftpSf) {
        var localDirectory = new File(new File(System.getProperty("user.home"), "Desktop"), "local");
        return Ftp
                .inboundAdapter(ftpSf)
                .remoteDirectory("/")
                .autoCreateLocalDirectory(true)
                .patternFilter("*.txt")
                .localDirectory(localDirectory);
    }

    @Bean
    IntegrationFlow inbound(FtpInboundChannelAdapterSpec ftpInboundSpec) {
        return IntegrationFlow
                .from(spec, pc -> pc.poller(pm -> pm.fixedRate(1000, TimeUnit.MILLISECONDS)))
                .handle((file, messageHeaders) -> {
                    System.out.println("new file: " + file + ".");
                    messageHeaders.forEach((k, v) -> System.out.println(k + ':' + v));
                    return null;
                })
                .get();
    }
```

**Comment by joshlong** [comment]
Ah! Even better :) I’m pleased to learn this! Thank you 🙏
