### ISSUE TITLE
No declared method 'evaluate' in class 'class org.springframework.integration.json.JsonPathUtils'

### ISSUE THREAD

**Issue by susimsek** [spring-projects/spring-integration#3990]
hi spring integration teams.i am using spring integration 6.0.1. When I compile the project as native, I am getting an error as follows. Can you provide aot support for JsonPathUtils?

The reproduce example codes are shared via my Github, check [here.](https://github.com/susimsek/spring-graphql-samples) 

Spring boot version: 3.0.1
Spring Integration version: 6.0.1
 Kotlin version: 1.7.22
 Java version: 17

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name '_org.springframework.integration.errorLogger.handler': Error creating bean with name 'integrationEvaluationContext': Error creating bean with name 'jsonPath': No declared method 'evaluate' in class 'class org.springframework.integration.json.JsonPathUtils'
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[spring-graphql-samples:6.0.3]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[spring-graphql-samples:6.0.3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-graphql-samples:6.0.3]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-graphql-samples:3.0.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-graphql-samples:3.0.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-graphql-samples:3.0.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-graphql-samples:3.0.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-graphql-samples:3.0.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-graphql-samples:3.0.1]
	at io.github.susimsek.springgraphqlsamples.SpringGraphqlSamplesApplicationKt.main(SpringGraphqlSamplesApplication.kt:13) ~[spring-graphql-samples:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'integrationEvaluationContext': Error creating bean with name 'jsonPath': No declared method 'evaluate' in class 'class org.springframework.integration.json.JsonPathUtils'
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205) ~[spring-graphql-samples:6.0.3]
	at org.springframework.integration.context.IntegrationContextUtils.getBeanOfType(IntegrationContextUtils.java:164) ~[spring-graphql-samples:6.0.1]
	at org.springframework.integration.context.IntegrationContextUtils.getEvaluationContext(IntegrationContextUtils.java:145) ~[spring-graphql-samples:6.0.1]
	at org.springframework.integration.expression.ExpressionUtils.doCreateContext(ExpressionUtils.java:116) ~[na:na]
	at org.springframework.integration.expression.ExpressionUtils.createStandardEvaluationContext(ExpressionUtils.java:92) ~[na:na]
	at org.springframework.integration.handler.LoggingHandler.onInit(LoggingHandler.java:174) ~[spring-graphql-samples:6.0.1]
	at org.springframework.integration.context.IntegrationObjectSupport.afterPropertiesSet(IntegrationObjectSupport.java:208) ~[spring-graphql-samples:6.0.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747) ~[spring-graphql-samples:6.0.3]
	... 16 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jsonPath': No declared method 'evaluate' in class 'class org.springframework.integration.json.JsonPathUtils'
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:662) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:650) ~[spring-graphql-samples:6.0.3]
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1276) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.BeanFactoryUtils.beansOfTypeIncludingAncestors(BeanFactoryUtils.java:321) ~[na:na]
	at org.springframework.integration.config.AbstractEvaluationContextFactoryBean.functions(AbstractEvaluationContextFactoryBean.java:112) ~[spring-graphql-samples:6.0.1]
	at org.springframework.integration.config.AbstractEvaluationContextFactoryBean.initialize(AbstractEvaluationContextFactoryBean.java:96) ~[spring-graphql-samples:6.0.1]
	at org.springframework.integration.config.IntegrationEvaluationContextFactoryBean.afterPropertiesSet(IntegrationEvaluationContextFactoryBean.java:86) ~[spring-graphql-samples:6.0.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747) ~[spring-graphql-samples:6.0.3]
	... 30 common frames omitted
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: No declared method 'evaluate' in class 'class org.springframework.integration.json.JsonPathUtils'
	at org.springframework.integration.config.SpelFunctionFactoryBean.afterPropertiesSet(SpelFunctionFactoryBean.java:68) ~[spring-graphql-samples:6.0.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797) ~[spring-graphql-samples:6.0.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747) ~[spring-graphql-samples:6.0.3]
	... 45 common frames omitted
```

**Comment by artembilan** [comment]
We have this hints registered for that class:
```
		reflectionHints.registerType(JsonPathUtils.class,
				builder ->
						builder.onReachableType(TypeReference.of("com.jayway.jsonpath.JsonPath"))
								.withMembers(MemberCategory.INVOKE_PUBLIC_METHODS));
```
But apparently `INVOKE_PUBLIC_METHODS` is not enough for that `this.method = BeanUtils.resolveSignature(this.functionMethodSignature, this.functionClass);` in the `SpelFunctionFactoryBean`...

Will come back to you after some testing in our respective `spring-aot-smoke-tests` project: https://github.com/spring-projects/spring-aot-smoke-tests
