### ISSUE TITLE
SpelEvaluationException: EL1012E: Cannot index into a null value in @Payload for @MessagingGateway

### ISSUE THREAD

**Issue by tompson** [spring-projects/spring-integration#3998]
**In what version(s) of Spring Integration are you seeing this issue?**

6.0.2

**Describe the bug**

I defined a Gateway

```
@MessagingGateway(defaultRequestChannel = "removeTokenPubSubChannel")
public interface RemoveTokenGateway {

	@Payload("#args[0]")
	void removeToken(@Header("token") String token);
}
```

which worked in 5.5.16 before upgrading to Spring Boot 3

No I get 

```
org.springframework.expression.spel.SpelEvaluationException: EL1012E: Cannot index into a null value
	at org.springframework.expression.spel.ast.Indexer.getValueRef(Indexer.java:145) ~[spring-expression-6.0.4.jar:6.0.4]
	at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:70) ~[spring-expression-6.0.4.jar:6.0.4]
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:91) ~[spring-expression-6.0.4.jar:6.0.4]
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:112) ~[spring-expression-6.0.4.jar:6.0.4]
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:338) ~[spring-expression-6.0.4.jar:6.0.4]
	at org.springframework.integration.gateway.GatewayMethodInboundMessageMapper$DefaultMethodArgsMessageMapper.toMessage(GatewayMethodInboundMessageMapper.java:288) ~[spring-integration-core-6.0.2.jar:6.0.2]
	at org.springframework.integration.gateway.GatewayMethodInboundMessageMapper$DefaultMethodArgsMessageMapper.toMessage(GatewayMethodInboundMessageMapper.java:275) ~[spring-integration-core-6.0.2.jar:6.0.2]
	at org.springframework.integration.gateway.GatewayMethodInboundMessageMapper.mapArgumentsToMessage(GatewayMethodInboundMessageMapper.java:193) ~[spring-integration-core-6.0.2.jar:6.0.2]
	at org.springframework.integration.gateway.GatewayMethodInboundMessageMapper.toMessage(GatewayMethodInboundMessageMapper.java:187) ~[spring-integration-core-6.0.2.jar:6.0.2]
	at org.springframework.integration.gateway.GatewayMethodInboundMessageMapper.toMessage(GatewayMethodInboundMessageMapper.java:86) ~[spring-integration-core-6.0.2.jar:6.0.2]
	at org.springframework.integration.support.converter.SimpleMessageConverter.toMessage(SimpleMessageConverter.java:111) ~[spring-integration-core-6.0.2.jar:6.0.2]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.doConvert(AbstractMessageSendingTemplate.java:182) ~[spring-messaging-6.0.4.jar:6.0.4]
	at org.springframework.integration.gateway.MessagingGatewaySupport$ConvertingMessagingTemplate.doConvert(MessagingGatewaySupport.java:1007) ~[spring-integration-core-6.0.2.jar:6.0.2]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:150) ~[spring-messaging-6.0.4.jar:6.0.4]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:143) ~[spring-messaging-6.0.4.jar:6.0.4]
	at org.springframework.integration.gateway.MessagingGatewaySupport.send(MessagingGatewaySupport.java:467) ~[spring-integration-core-6.0.2.jar:6.0.2]
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.sendOrSendAndReceive(GatewayProxyFactoryBean.java:669) ~[spring-integration-core-6.0.2.jar:6.0.2]
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.invokeGatewayMethod(GatewayProxyFactoryBean.java:584) ~[spring-integration-core-6.0.2.jar:6.0.2]
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.doInvoke(GatewayProxyFactoryBean.java:550) ~[spring-integration-core-6.0.2.jar:6.0.2]
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.invoke(GatewayProxyFactoryBean.java:540) ~[spring-integration-core-6.0.2.jar:6.0.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.4.jar:6.0.4]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:218) ~[spring-aop-6.0.4.jar:6.0.4]
	at jdk.proxy2/jdk.proxy2.$Proxy72.removeToken(Unknown Source) ~[na:na]
```

**Comment by artembilan** [comment]
Hi, @tompson !

Sad to hear that something is broken for you, but I'm sorry, what is your expectation with that `#args[0]` expression against your `String token`?
Even if that worked before, it doesn't mean that it was correct.
Either way it is more Spring Framework question since SpEL is hosted and supported over there: nothing what Spring Integration can do for you.

Thanks

**Comment by tompson** [comment]
thanks for the quick reply

since there are sample in the Spring Integration documentation it should work that way: https://docs.spring.io/spring-integration/docs/6.0.2/reference/html/messaging-endpoints.html#mapping-method-arguments

```
public interface MyGateway {

    void payloadAndHeaderMapWithoutAnnotations(String s, Map<String, Object> map);

    void payloadAndHeaderMapWithAnnotations(@Payload String s, @Headers Map<String, Object> map);

    void headerValuesAndPayloadWithAnnotations(@Header("k1") String x, @Payload String s, @Header("k2") String y);

    void mapOnly(Map<String, Object> map); // the payload is the map and no custom headers are added

    void twoMapsAndOneAnnotatedWithPayload(@Payload Map<String, Object> payload, Map<String, Object> headers);

    @Payload("#args[0] + #args[1] + '!'")
    void payloadAnnotationAtMethodLevel(String a, String b);

    @Payload("@someBean.exclaim(#args[0])")
    void payloadAnnotationAtMethodLevelUsingBeanResolver(String s);

    void payloadAnnotationWithExpression(@Payload("toUpperCase()") String s);

    void payloadAnnotationWithExpressionUsingBeanResolver(@Payload("@someBean.sum(#this)") String s); //  (1)

    // invalid
    void twoMapsWithoutAnnotations(Map<String, Object> m1, Map<String, Object> m2);

    // invalid
    void twoPayloads(@Payload String s1, @Payload String s2);

    // invalid
    void payloadAndHeaderAnnotationsOnSameParameter(@Payload @Header("x") String s);

    // invalid
    void payloadAndHeadersAnnotationsOnSameParameter(@Payload @Headers Map<String, Object> map);

}

```

**Comment by tompson** [comment]
@artembilan Thanks - `@Payload("args[0]")` works!
