### ISSUE TITLE
GraalVM native-image failure: "Code generation is not supported" for root bean MessagingAnnotationPostProcessor

### ISSUE THREAD

**Issue by mmoayyed** [spring-projects/spring-integration#8571]
**In what version(s) of Spring Integration are you seeing this issue?**

6.0.3

**Describe the bug**

Generating a GraalVM native image in a JDK 17 project with Spring Boot 3.0.4 leads to:

```
Exception in thread "main" java.lang.IllegalArgumentException: Code generation is not supported for bean definitions declaring an instance supplier callback : Root bean: class [org.springframework.integration.config.MessagingAnnotationPostProcessor]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGenerator.<init>(BeanDefinitionMethodGenerator.java:82)
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:100)
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:115)
        at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:48)
        at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:36)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.getContributions(BeanFactoryInitializationAotContributions.java:67)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:49)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:44)
        at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
        at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
        at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
        at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
```

**To Reproduce**

https://github.com/mmoayyed/demo-spring-boot-native#spring-boot-3-graalvm-gradle-demo

**Expected behavior**

GraalVM image builds correctly.

**Sample**

See README please:

https://github.com/mmoayyed/demo-spring-boot-native#spring-boot-3-graalvm-gradle-demo

**Comment by mmoayyed** [comment]
Looks like this might already be fixed via https://github.com/spring-projects/spring-integration/commit/5c96c0ded07e4630b7756e2643650bf3a01fbb5d

**Comment by artembilan** [comment]
Yes, fixed via: https://github.com/spring-projects/spring-integration/commit/5c96c0ded07e4630b7756e2643650bf3a01fbb5d.
Will be released next week.
