### ISSUE TITLE
SftpSession.write() method fails after 100 writes.

### ISSUE THREAD

**Issue by abraham-macias** [spring-projects/spring-integration#8744]
**In what version(s) of Spring Integration are you seeing this issue?**

6.1.2

**Describe the bug**

After some time online, when calling the SftpSession.write() method, the application returns a SFTP error (SSH_FX_FAILURE): Too many open files in this session, maximum 100.
I think that the cause is that SftpSession.write is opening a OutputStream that is not closing.

**To Reproduce**

It will probably be reproduce if you call the SftpSession.write() method more that 100 times.

**Expected behavior**

The SftpSession.write() method should write correctly the file into the SFTP.

**Comment by abraham-macias** [comment]
It looks that the 100 file handles limit depends on the SFTP server:
  https://repost.aws/questions/QUylHqUiMTS2-IRcl5tGbknw/aws-sftp-error-too-many-open-files-in-this-session-maximum-100

```
Caused by: SFTP error (SSH_FX_FAILURE): Too many open files in this session, maximum 100
  at org.apache.sshd.sftp.client.impl.AbstractSftpClient.throwStatusException(AbstractSftpClient.java:217)
  at org.apache.sshd.sftp.client.impl.AbstractSftpClient.checkHandleResponse(AbstractSftpClient.java:255)
  at org.apache.sshd.sftp.client.impl.AbstractSftpClient.checkHandle(AbstractSftpClient.java:232)
  at org.apache.sshd.sftp.client.impl.AbstractSftpClient.open(AbstractSftpClient.java:573)
  at org.apache.sshd.sftp.client.impl.SftpOutputStreamAsync.(SftpOutputStreamAsync.java:63)
  at org.apache.sshd.sftp.client.impl.AbstractSftpClient.write(AbstractSftpClient.java:1201)
  at org.apache.sshd.sftp.client.SftpClient.write(SftpClient.java:940)
  at org.apache.sshd.sftp.client.SftpClient.write(SftpClient.java:936)
  at org.springframework.integration.sftp.session.SftpSession.write(SftpSession.java:126)
```

**Comment by rishiraj88** [comment]
@abraham-macias , looks like the traditional piece of advice has been missed to adhere to. Interesting issue. 
Thanks.

**Comment by artembilan** [comment]
@abraham-macias ,

I don't think that the problem is with not closed stream.
The code there is like this:
```
	public void write(InputStream inputStream, String destination) throws IOException {
		OutputStream outputStream = this.sftpClient.write(destination);
		FileCopyUtils.copy(inputStream, outputStream);
	}
```
where the last line does this:
```
	/**
	 * Copy the contents of the given InputStream to the given OutputStream.
	 * Closes both streams when done.
	 * @param in the stream to copy from
	 * @param out the stream to copy to
	 * @return the number of bytes copied
	 * @throws IOException in case of I/O errors
	 */
	public static int copy(InputStream in, OutputStream out) throws IOException {
```

So, the problem might be indeed on the SFTP server when you try to send more than 100 files in parallel.

@rishiraj88 ,

I'm not sure in your comment. An advice for what are you looking for here?


Do you both see anything what has to be fixed from this project perspective?

Thanks

**Comment by abraham-macias** [comment]
Hi @artembilan ,
 I think you are right. I didn't see that inside FileCopyUtils.copy the stream is being closed.

But the thing is that with spring-integration-sftp v5.5.15 (based on com.jcraft.jsch) everything works fine and with spring-integration-sftp v6.1.2 (based on org.apache.sshd) this error appears.

As the comment in repost.aws says, maybe the "file handle" leak is not when writing the file, maybe the "file handler" leak is at listing the files or something.

All I know is that I had to revert the change after updating from 5.5.15 to 6.1.2.

Please help! 
Thanks

**Comment by artembilan** [comment]
@abraham-macias ,

thank you for providing more info!

Well, we need to know more about your solution.
Perhaps you just can share with us a simple project where we can reproduce the problem?
It is indeed might be the fact the file handlers are locked by some other operation or even other process.
It is just a side-effect that this `write` operation is suffering from the result of the original problem.

You can enable `TRACE` logging level for `org.apache.sshd.sftp.client` category to see how an `SftpClient` behaves.
For example, there supposed to be something like:
```
2023-10-03 10:26:51,654 DEBUG [main] [org.apache.sshd.sftp.client.impl.SftpOutputStreamAsync] - close(SftpOutputStreamAsync[ClientSessionImpl[user@localhost/127.0.0.1:55387]][bar]) processing ack #1 response for SftpAckData[id=106, offset=0, length=3]
2023-10-03 10:26:51,654 DEBUG [main] [org.apache.sshd.sftp.client.impl.SftpOutputStreamAsync] - close(SftpOutputStreamAsync[ClientSessionImpl[user@localhost/127.0.0.1:55387]][bar]) closing file handle
```
I also see in my logs this:
```
2023-10-03 10:26:51,678 TRACE [main] [org.apache.sshd.sftp.client.impl.SftpDirEntryIterator] - load(/)[/: 6534353235326162626263653934373037353338616164636663373232653937] exhausted all entries - EOL=true
2023-10-03 10:26:51,678 DEBUG [main] [org.apache.sshd.sftp.client.impl.SftpDirEntryIterator] - close(/) handle=/: 6534353235326162626263653934373037353338616164636663373232653937
```
and this:
```
2023-10-03 10:26:51,691 TRACE [main] [org.apache.sshd.sftp.client.impl.SftpInputStreamAsync] - pollBuffer(SftpInputStreamAsync[ClientSessionImpl[user@localhost/127.0.0.1:55387]][bar]) response=103 for ack=SftpAckData[id=114, offset=0, length=32755] - len=13
2023-10-03 10:26:51,691 DEBUG [main] [org.apache.sshd.sftp.client.impl.SftpInputStreamAsync] - transferTo(SftpInputStreamAsync[ClientSessionImpl[user@localhost/127.0.0.1:55387]][bar]) transferred 3 bytes
2023-10-03 10:26:51,691 DEBUG [main] [org.apache.sshd.sftp.client.impl.SftpInputStreamAsync] - close(SftpInputStreamAsync[ClientSessionImpl[user@localhost/127.0.0.1:55387]][bar]) closing file handle; 0 short reads
```

so, I still not sure where we might be wrong and have those handlers not closed. 

Any chances to try your solution with Spring Integration `6.2.0-M3`?
I'm asking because there we have moved to the `org.apache.sshd` of version `2.10.0`, which might have some fixes on the matter.
Note though: we cannot upgrade Spring Integration `6.1.x` to that SSHD version because of our policy on one hand and not compatible byte code on the other: https://github.com/spring-projects/spring-integration/pull/8743
