### ISSUE TITLE
Spring Boot app Initialization error: IllegalArgumentException: Invalid value type for attribute 'factoryBeanObjectType': java.lang.String

### ISSUE THREAD

**Issue by meletis** [spring-projects/spring-integration#8787]
**In what version(s) of Spring Integration are you seeing this issue?**

v6.2.0-RC1 

* It comes automatically by Gradle when using Spring Boot 3.2.0-RC2.
* The same bug kicks in with Spring Boot 3.2.0-RC1
* The bug **doesn't kick in** with Spring Boot 3.1.5

```
plugins {
    id("org.springframework.boot") version "3.2.0-RC2"
    id("io.spring.dependency-management") version "1.1.3"
    id("org.hibernate.orm") version "6.2.13.Final"
}

dependencies {
    // Pull in the needed Spring Boot dependencies
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-cache")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-graphql")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-oauth2-client")
    implementation("org.springframework.boot:spring-boot-starter-quartz")
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    implementation("org.springframework.boot:spring-boot-starter-integration")
    implementation("org.springframework.integration:spring-integration-redis")
    implementation("org.springframework.session:spring-session-data-redis")
}
```

**Describe the bug**

A bean of type `RedisLockRegistry` is declared in my `@Configuration` class like the following:

```
    @Bean
    @ConditionalOnBean(RedisConnectionFactory.class)
    public LockRegistry createRedisLockRegistry(RedisConnectionFactory redisConnectionFactory, @Value("${spring.application.name}") String appName) {
        return new RedisLockRegistry(redisConnectionFactory, appName, this.contextProperties.getLocksMaximumAgeMillis());
    }
```

I get the following exception when my Spring Boot app starts up:

```
Error: Exception in thread "main" java.lang.IllegalStateException: Error processing condition on com.surveycto.admin.app.config.BeansConfig.createRedisLockRegistry
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:183)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:144)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:428)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:289)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:775)
	at org.springframework.context.support.GenericApplicationContext.refreshForAotProcessing(GenericApplicationContext.java:415)
	at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:54)
	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
	at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
Caused by: java.lang.IllegalArgumentException: Invalid value type for attribute 'factoryBeanObjectType': java.lang.String
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getTypeForFactoryBeanFromAttributes(FactoryBeanRegistrySupport.java:86)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:838)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:620)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:573)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:532)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:246)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:239)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:229)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:182)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:119)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
	... 18 more
```

The only thing that I changed is the "org.springframework.boot" plugin version, but I suspect that the problem is in the code of this repo, so I opened this issue here instead of the Spring Boot repo.

If I'm wrong, then I'm happy to close this and re-open it in the Spring Boot repo.

**Comment by artembilan** [comment]
Any chances that you can share a simple project with us where we can reproduce the problem?
Looks like an AOT is involved somehow, so it might be also great to know steps how you reproduce.

That `factoryBeanObjectType` attribute is not set anywhere in Spring Integration though.
And I cannot find in Spring Integration dependencies that it used somehow.
I see that you have a `spring-session-data-redis` one. Not familiar with the project, but might be a clue.

So, would be great if you give me a project where I can debug the problem.

Thanks

**Comment by meletis** [comment]
You are right, @artembilan , AOT _is_ involved. I have added this plugin in my `build.gradle` file, so that I can also build a native image for the app:

```
    id("org.graalvm.buildtools.native") version "0.9.28"
```

But the bug kicks in during the normal build (`./gradlew build`), during the `processAot` phase.

I'm not allowed to share any code and it could take a while before I can extract the minimum bits into a new demo project, so I was hoping that this could ring a bell to you in the meantime. But it looks like this is not an issue with Spring Integration, so I should probably post this into the Spring Boot project?

**Comment by artembilan** [comment]
Even if we move it to Spring Boot, they still going to ask you for a simple project to reproduce.
In the end it doesn't matter what team takes care about the issue since we all in this together.

You see: there is that `DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:573)` in the stack trace, which really iterates all the beans in the application context to determine their matching type.
Therefore anything from your dependencies could do the harm.
So, to determine the place for the fix we need to catch that wrong usage of the mentioned `factoryBeanObjectType`.
And since I don't see how all those standard Spring Boot dependencies can do that, I make an assumption that only `spring-session-data-redis` (or its parent) does something what new AOT does not allow.
But this might be rude for that specific project without any evidence, therefore it is better to have something which we both can reproduce.

**Comment by meletis** [comment]
Oh, I just discovered the problem. I was using a Spring Cloud dependency and I had to change the BOM for Spring Cloud to 2023.0.0-RC1. Once I did that everything worked again.

Thank you for help @artembilan; your comments helped me dig into the right direction.
