### ISSUE TITLE
Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)

### ISSUE THREAD

**Issue by jianotl** [spring-projects/spring-integration#8864]
jdk 17 + springboot 3.2.0
use @MessagingGateway(defaultRequestChannel = "mqttOutboundChannel")
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @78b1cc93
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:505)
	... 26 common frames omitted

**Comment by artembilan** [comment]
We need much more info to understand what is the problem.

Will be closed in a couple days without an answer.

Thank you for understanding

**Comment by artembilan** [comment]
Closed as `Invalid`.
