### ISSUE TITLE
ClassCastException: class java.lang.String cannot be cast to class org.springframework.messaging.Message

### ISSUE THREAD

**Issue by ivangfr** [spring-projects/spring-integration#9002]
**In what version(s) of Spring Integration are you seeing this issue?** 6.2.2

**Describe the bug**

While using **Spring Boot 2.7.17** and **Spring Integration 5.5.19**, I don't face any issue with this code

```
@RequiredArgsConstructor
@Configuration
@EnableIntegration
public class FileIntegrationProcessorConfig {

    private final FileMessageProcessorChain fileMessageProcessorChain;

    @Value("${application.inbound.path}")
    private String inboundPath;

    @Bean
    public IntegrationFlow fileReadingFlow() {
        return IntegrationFlows
                .from(Files.inboundAdapter(new File(inboundPath))
                                .filter(new SimplePatternFileListFilter("*.csv"))
                                .useWatchService(true)
                                .watchEvents(WatchEventType.CREATE),
                        e -> e.poller(Pollers.fixedDelay(1000)))
                .transform(Files.toStringTransformer(StandardCharsets.ISO_8859_1.name()))
                .channel("processFileChannel")
                .get();
    }

    @Bean
    @ServiceActivator(inputChannel = "processFileChannel")
    public Consumer<Message<String>> processMessage() {
        return System.out::println;
    }
}
```

However, once upgraded to **Spring Boot 3.2.3** and **Spring Integration 6.2.2**, the exception (shown on the bottom) is thrown.

It seems that the **ServiceActivator** before was receiving a `Message<String>` but, after the update, it's receiving `String`.

**To Reproduce**

Steps to reproduce the behavior.

1. Download the sample attached;
2. Unzip it;
3. Navigate inside the sample folder;
4. Run: `./mvnw clean spring-boot:run --projects actor-filmography-service`
5. The exception should be displayed.

**Expected behavior**

The **ServiceActivator** should consume a `Message<String>` and not a `String`.

**Sample**

[spring-integration-file-support-example.zip](https://github.com/spring-projects/spring-integration/files/14623787/spring-integration-file-support-example.zip)

**Exception Log**
```
o.s.i.handler.LambdaMessageProcessor     : Could not invoke the method 'public void com.ivanfranchin.actorfilmographyservice.file.FileIntegrationProcessorConfig$$Lambda$1351/0x00000001238d2428.accept(java.lang.Object)' due to a class cast exception, if using a lambda in the DSL, consider using an overloaded EIP method that takes a Class<?> argument to explicitly  specify the type. An example of when this often occurs is if the lambda is configured to receive a Message<?> argument.

java.lang.ClassCastException: class java.lang.String cannot be cast to class org.springframework.messaging.Message (java.lang.String is in module java.base of loader 'bootstrap'; org.springframework.messaging.Message is in unnamed module of loader 'app')
	at org.springframework.integration.handler.LambdaMessageProcessor.invokeMethod(LambdaMessageProcessor.java:195) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.handler.LambdaMessageProcessor.processMessage(LambdaMessageProcessor.java:121) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:95) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:145) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:73) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:132) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:378) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:332) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-6.1.4.jar:6.1.4]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-6.1.4.jar:6.1.4]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-6.1.4.jar:6.1.4]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-6.1.4.jar:6.1.4]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:501) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.doProduceOutput(AbstractMessageProducingHandler.java:356) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:285) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:249) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:151) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:73) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:132) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:378) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:332) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:302) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-6.1.4.jar:6.1.4]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-6.1.4.jar:6.1.4]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-6.1.4.jar:6.1.4]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-6.1.4.jar:6.1.4]
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.handleMessage(SourcePollingChannelAdapter.java:206) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.messageReceived(AbstractPollingEndpoint.java:481) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:467) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:419) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$4(AbstractPollingEndpoint.java:355) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) ~[spring-core-6.1.4.jar:6.1.4]
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$5(AbstractPollingEndpoint.java:348) ~[spring-integration-core-6.2.2.jar:6.2.2]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:96) ~[spring-context-6.1.4.jar:6.1.4]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
```

**Comment by ivangfr** [comment]
I've found a different way to implement the `ServiceActivator` that works.
```
    @ServiceActivator(inputChannel = "processFileChannel")
    public void processMessage(Message<String> message) {
        System.out.println(message);
    }
```

**Comment by artembilan** [comment]
Just wrote this simple Spring Boot application to mimic your problem explanation:
```
@SpringBootApplication
public class SpringIntegrationGh9002Application {

	public static void main(String[] args) {
		SpringApplication.run(SpringIntegrationGh9002Application.class, args);
	}


	@Bean
	ApplicationRunner applicationRunner(MessageChannel processFileChannel) {
		return args -> {
			processFileChannel.send(new GenericMessage<>("test data"));
		};
	}

	@Bean
	MessageChannel processFileChannel() {
		return new DirectChannel();
	}

	@Bean
	@ServiceActivator(inputChannel = "processFileChannel")
	public Consumer<Message<String>> processMessage() {
		return System.out::println;
	}

}
```
Works well in both mentioned Spring Boot versions.

On the other hand, according to your stack trace, the `LambdaMessageProcessor` is used only with Java DSL. It is not involved with regular messaging annotations.
So, the problem you are facing is in a different place, e.g. `<Message<String>, String>transform(m -> ...)`.

I'm glad that you have figured out a solution for your project, but the report is not what we really see.
