### ISSUE TITLE
Mqtt5 removing topic with multiple topic subscriptions leads to java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by MarcelFadtke** [spring-projects/spring-integration#9276]
**In what version(s) of Spring Integration are you seeing this issue?**

For example:

6.3.1.RELEASE 
and probably before

**Describe the bug**
When adding multiple topics (org.springframework.integration.mqtt.inbound.Mqttv5PahoMessageDrivenChannelAdapter#addTopic) and removing a topic later on (org.springframework.integration.mqtt.inbound.Mqttv5PahoMessageDrivenChannelAdapter#removeTopic) a java.util.ConcurrentModificationException occurs. 

If I have subscribed to a single topic only, I don't receive the exception. 

**To Reproduce**

Setup an mqtt 5 client and connect to a broker and adding at least two topics programatically, then removing one of the topics.

**Expected behavior**

Unsubscribing (removeTopic) works without a ConcurrentModificationException in line 363.
https://github.com/spring-projects/spring-integration/blob/4108ea520ea0b152ea09d4472dbbee74ac11af29/spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/inbound/Mqttv5PahoMessageDrivenChannelAdapter.java#L358-L365

Also I'm wondering why the structure of the method structure calls the `super.removeTopic(topic);` after `this.mqttClient.unsubscribe(topic).waitForCompletion(getCompletionTimeout());` and not the other way around...

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by artembilan** [comment]
I still have to prove this, but if you have an idea how to fix, feel free to contribute it!
Will come back to you tomorrow .

**Comment by MarcelFadtke** [comment]
@artembilan Thank you again for checking on this. 
I just tried to reproduce it with the version before and it does not occur, so it's related only to the latest release.
I'm not sure if this is making any difference, but I'm using the spring-boot-dependencies 3.3.1 which includes the latest release of spring integration 6.3.1.

**Comment by artembilan** [comment]
Can you share, please, how that does `ConcurrentModificationException` stack trace look like?
My one comes like this:
```
2024-06-26 11:25:20,510 ERROR [main] [org.springframework.integration.mqtt.inbound.Mqttv5PahoMessageDrivenChannelAdapter] - Error during stopping: bean 'mqttInFlow.mqtt:inbound-channel-adapter#0'; defined in: 'org.springframework.integration.mqtt.Mqttv5BackToBackTests$Config'; from source: 'bean method mqttInFlow'
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
	at org.eclipse.paho.mqttv5.client.internal.CommsCallback.removeMessageListener(CommsCallback.java:568) ~[org.eclipse.paho.mqttv5.client-1.2.5.jar:?]
	at org.eclipse.paho.mqttv5.client.internal.ClientComms.removeMessageListener(ClientComms.java:676) ~[org.eclipse.paho.mqttv5.client-1.2.5.jar:?]
	at org.eclipse.paho.mqttv5.client.MqttAsyncClient.unsubscribe(MqttAsyncClient.java:1394) ~[org.eclipse.paho.mqttv5.client-1.2.5.jar:?]
	at org.eclipse.paho.mqttv5.client.MqttAsyncClient.unsubscribe(MqttAsyncClient.java:1354) ~[org.eclipse.paho.mqttv5.client-1.2.5.jar:?]
	at org.springframework.integration.mqtt.inbound.Mqttv5PahoMessageDrivenChannelAdapter.doStop(Mqttv5PahoMessageDrivenChannelAdapter.java:292) ~[classes/:?]
```

But this has nothing to do with the code you are pointing to.

Thanks

**Comment by MarcelFadtke** [comment]
Sure, 
```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1638)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1636)
	at org.eclipse.paho.mqttv5.client.internal.CommsCallback.removeMessageListener(CommsCallback.java:568)
	at org.eclipse.paho.mqttv5.client.internal.ClientComms.removeMessageListener(ClientComms.java:676)
	at org.eclipse.paho.mqttv5.client.MqttAsyncClient.unsubscribe(MqttAsyncClient.java:1394)
	at org.eclipse.paho.mqttv5.client.MqttAsyncClient.unsubscribe(MqttAsyncClient.java:1354)
	at org.springframework.integration.mqtt.inbound.Mqttv5PahoMessageDrivenChannelAdapter.removeTopic(Mqttv5PahoMessageDrivenChannelAdapter.java:363)
	at com.example.project.mqtt.service.MqttSubscriptionService.unsubscribe(MqttSubscriptionService.kt:77)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.mockk.proxy.jvm.advice.MethodCall.call(MethodCall.kt:14)
	at io.mockk.proxy.jvm.advice.SelfCallEliminatorCallable.call(SelfCallEliminatorCallable.kt:14)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.handleOriginalCall(JvmMockFactoryHelper.kt:96)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.access$handleOriginalCall(JvmMockFactoryHelper.kt:19)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1$invocation$1$1.invoke(JvmMockFactoryHelper.kt:28)
	at io.mockk.impl.stub.MockKStub$handleInvocation$originalPlusToString$1.invoke(MockKStub.kt:233)
	at io.mockk.impl.stub.SpyKStub.defaultAnswer(SpyKStub.kt:15)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:269)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:24)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
	at com.example.project.mqtt.service.MqttSubscriptionService.unsubscribe(MqttSubscriptionService.kt:81)
	at com.example.project.mqtt.service.MqttSubscriptionService.unsubscribeAll(MqttSubscriptionService.kt:104)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.mockk.proxy.jvm.advice.MethodCall.call(MethodCall.kt:14)
	at io.mockk.proxy.jvm.advice.SelfCallEliminatorCallable.call(SelfCallEliminatorCallable.kt:14)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.handleOriginalCall(JvmMockFactoryHelper.kt:96)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.access$handleOriginalCall(JvmMockFactoryHelper.kt:19)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1$invocation$1$1.invoke(JvmMockFactoryHelper.kt:28)
	at io.mockk.impl.stub.MockKStub$handleInvocation$originalPlusToString$1.invoke(MockKStub.kt:233)
	at io.mockk.impl.stub.SpyKStub.defaultAnswer(SpyKStub.kt:15)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:269)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:24)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
	at com.example.project.mqtt.service.MqttSubscriptionService.unsubscribeAll(MqttSubscriptionService.kt:106)
	at com.example.project.mqtt.Mqtt5ContainerTest.clear(Mqtt5ContainerTest.kt:57)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

In case this matters:
- I use hivemq for testcontainers instead of mosquitto (but I guess this won't make any difference) 
- in my test I call the unsubscribeAll() before and after each test
- my inboundAdapter is autowired: `mqttInboundAdapter: AbstractMqttMessageDrivenChannelAdapter` (I use the abstract channel adapter because of mqtt3 and mqtt5 compatibility, but only one version can be used at runtime because the configuration has a condition on the configured version in the application properties) 
- mockk is involved because I use a spy on my subscription service
- my unsubscribe method just calls `mqttInboundAdapter.removeTopic(topic)`
- my subscribe method looks like this: 
```
// if there is an existing subscribtion
 subscribedTopics[subscriptionId]?.let {
            unsubscribe(subscriptionId, topic)
        }
// add topic
        mqttInboundAdapter.addTopic(topic, qualityOfService)
```

Sorry, but I can't share the code because of company restrictions :(

**Comment by artembilan** [comment]
I'm not sure if that is useful, but I have reproduced it with this test:
```
@SpringJUnitConfig
@DirtiesContext
public class Gh9276Tests implements MosquittoContainerTest {

	@Autowired
	Mqttv5PahoMessageDrivenChannelAdapter messageDrivenChannelAdapter;

	@BeforeEach
	@AfterEach
	void setup() {
		this.messageDrivenChannelAdapter.removeTopic("topic1", "topic2");
	}

	@Test
	void noConcurrentModificationException() {
		this.messageDrivenChannelAdapter.addTopic("topic1", "topic2");
	}


	@Configuration
	@EnableIntegration
	public static class Config {

		@Bean
		Mqttv5PahoMessageDrivenChannelAdapter messageDrivenChannelAdapter() {
			Mqttv5PahoMessageDrivenChannelAdapter mqttv5PahoMessageDrivenChannelAdapter =
					new Mqttv5PahoMessageDrivenChannelAdapter(MosquittoContainerTest.mqttUrl(), "mqttv5SIin", "someTopic");
			mqttv5PahoMessageDrivenChannelAdapter.setOutputChannelName("nullChannel");
			return mqttv5PahoMessageDrivenChannelAdapter;
		}

	}

}
```

The failure looks similar to yours:
```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
	at org.eclipse.paho.mqttv5.client.internal.CommsCallback.removeMessageListener(CommsCallback.java:568)
	at org.eclipse.paho.mqttv5.client.internal.ClientComms.removeMessageListener(ClientComms.java:676)
	at org.eclipse.paho.mqttv5.client.MqttAsyncClient.unsubscribe(MqttAsyncClient.java:1394)
	at org.eclipse.paho.mqttv5.client.MqttAsyncClient.unsubscribe(MqttAsyncClient.java:1354)
	at org.springframework.integration.mqtt.inbound.Mqttv5PahoMessageDrivenChannelAdapter.removeTopic(Mqttv5PahoMessageDrivenChannelAdapter.java:364)
	at org.springframework.integration.mqtt.Gh9276Tests.setup(Gh9276Tests.java:25)
```

The problem is here in the Eclipse Paho Client:
```
	public void removeMessageListener(String topicFilter) {
		Integer callbackId = this.callbackTopicMap.get(topicFilter);
		this.callbackMap.remove(callbackId);
		this.callbackTopicMap.remove(topicFilter);

		// Reverse lookup the subscription ID if it exists to remove that as well
		for (Map.Entry<Integer, Integer> entry : this.subscriptionIdMap.entrySet()) {
			if (entry.getValue().equals(callbackId)) {
				this.subscriptionIdMap.remove(entry.getKey());
			}
		}
	}
```

We just cannot remove from Map during iteration: https://stackoverflow.com/questions/6092642/how-to-remove-a-key-from-hashmap-while-iterating-over-it.

I have no idea how we can workaround this, but apparently the fix has to be done in Paho client: https://github.com/eclipse/paho.mqtt.java/issues/986

**Comment by MarcelFadtke** [comment]
Thank you for the effort and information. 
Since I didn’t receive the error in my scenario when I used the version 6.3.0 I’m wondering if your test still fails with that older version or not. Could you check this? And it case you also won‘t get the exception with the older version, then I wonder what changed in between? 
best regards 
Marcel

**Comment by MarcelFadtke** [comment]
Having a second look on your test: 
If you’d like to cover the same scenario I used in my test, just go with: 
```
@Test
	void marcelsTest() {
		this.messageDrivenChannelAdapter.addTopic("topic1", 0);

this.messageDrivenChannelAdapter.addTopic("topic2", 0);

this.messageDrivenChannelAdapter.removeTopic("topic1");

	}

**Comment by artembilan** [comment]
This is the change you are talking about: https://github.com/spring-projects/spring-integration/issues/9214.
It leads to the logic in the Paho client:
```
			if (messageListener == null) {
				this.comms.removeMessageListener(subscription.getTopic());
			} else {
				this.comms.setMessageListener(subId, subscription.getTopic(), messageListener);
			}
```
So, that's where we add that listener to the mentioned "guilty" map.

Since we cannot take that logic back due to shared subscription requirements, it looks like a workaround is to not use several topic subscriptions. 🤷
